//! Conformance suite for `ferrotorch-mps` — Layer 3.
//!
//! Tracking issue: #451 (MPS kernel layer).
//!
//! Reference library: `torch.mps` (Apple MPS backend), pinned to
//! `torch == 2.11.0`. Fixtures live in
//! `tests/conformance/fixtures.json`, generated by
//! `scripts/regenerate_mps_fixtures.py`.
//!
//! ## Scope
//!
//! Every public item in `ferrotorch-mps` falls into one of two groups:
//!
//! 1. **API-shape tests** — items testable without a live Apple Silicon device:
//!    `is_mps_available`, `mps_device_count`, `MpsDevice::new` (error path),
//!    `MpsDevice::count`, `MpsDevice::ordinal` (structural), `MpsDevice`
//!    Display, `init_mps_backend` (error path). These tests load fixture data
//!    from `tests/conformance/fixtures.json` and assert ferrotorch's stub
//!    behaviour matches the documented contract.
//!
//! 2. **cascade_skip — live MPS required** — any op that would need a real
//!    Metal device to produce a useful result. This box is WSL2 x86_64 so all
//!    live Metal paths are skipped with a one-line diagnostic. A tracking issue
//!    reference is included so they can be un-skipped when macOS CI lands.
//!
//! ## cascade_skip convention
//!
//! `cascade_skip!(label)` prints a diagnostic and returns early. It is NOT
//! `#[ignore]` — the test still runs and emits the notice. This matches the
//! ferrotorch-xpu and ferrotorch-core conformance pattern (no silent skips).

use std::path::PathBuf;

use ferrotorch_core::FerrotorchError;
use ferrotorch_mps::{MpsDevice, init_mps_backend, is_mps_available, kernels, mps_device_count};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// cascade_skip macro
// ---------------------------------------------------------------------------

/// Print a skip diagnostic and return early. Never panics.
/// Usage: `cascade_skip!("reason string")`.
macro_rules! cascade_skip {
    ($reason:literal) => {{
        eprintln!("  [cascade_skip] {} — {}", module_path!(), $reason);
        return;
    }};
}

// ---------------------------------------------------------------------------
// Fixture deserialization
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    metadata: FixtureMetadata,
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct FixtureMetadata {
    torch_version: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    mps_available: bool,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    python_executable: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    python_platform: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    generated_at: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    conformance_note: String,
}

/// One fixture entry. Fields are `Option` because different ops record
/// different subsets.
#[derive(Debug, Deserialize)]
struct Fixture {
    op: String,
    #[serde(default)]
    expected: Option<serde_json::Value>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    platform_note: Option<String>,
    #[serde(default)]
    expected_ferrotorch_error: Option<String>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    note: Option<String>,
    #[serde(default)]
    ordinal: Option<u64>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    ordinal_input: Option<u64>,
    #[serde(default)]
    expected_ordinal: Option<u64>,
    #[serde(default)]
    expected_ferrotorch_display: Option<String>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    torch_repr: Option<String>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    mps_available_at_fixture_time: Option<bool>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    torch_device_type: Option<String>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    torch_device_default_index: Option<serde_json::Value>,
    #[serde(default)]
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    torch_device_ordinal_0_index: Option<u64>,
}

fn load_fixtures() -> FixtureFile {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json");
    let bytes = std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "read {} failed: {e}. Regenerate via \
             scripts/regenerate_mps_fixtures.py",
            p.display()
        )
    });
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", p.display()))
}

fn fixtures_for<'a>(file: &'a FixtureFile, op: &str) -> Vec<&'a Fixture> {
    file.fixtures.iter().filter(|f| f.op == op).collect()
}

// ---------------------------------------------------------------------------
// Layer 2 sanity: fixture file covers all expected ops
// ---------------------------------------------------------------------------

#[test]
fn fixture_file_covers_every_expected_op() {
    let file = load_fixtures();
    let mut by_op: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for f in &file.fixtures {
        *by_op.entry(f.op.as_str()).or_insert(0) += 1;
    }
    let required = [
        "is_mps_available",
        "mps_device_count",
        "MpsDevice_new",
        "MpsDevice_count",
        "MpsDevice_ordinal",
        "init_mps_backend",
        "MpsDevice_display",
    ];
    for r in required {
        let n = by_op.get(r).copied().unwrap_or(0);
        assert!(
            n > 0,
            "fixture file missing op {r:?} (have: {:?})",
            by_op.keys().collect::<Vec<_>>()
        );
    }
    eprintln!(
        "  fixture_file_covers_every_expected_op: {} ops, {} fixtures, torch={}",
        by_op.len(),
        file.fixtures.len(),
        file.metadata.torch_version,
    );
}

// ---------------------------------------------------------------------------
// is_mps_available — fixture-driven
// ---------------------------------------------------------------------------

/// `is_mps_available()` must always return `false` on non-Apple platforms
/// and always `false` in the ferrotorch stub until #451 lands.
#[test]
fn is_mps_available_matches_fixture() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "is_mps_available");
    assert!(!cases.is_empty(), "fixture is_mps_available not found");

    let fixture_expected = cases[0]
        .expected
        .as_ref()
        .and_then(|v| v.as_bool())
        .expect("is_mps_available fixture must have bool `expected`");

    // On non-Apple platforms torch.mps.is_available() returns False.
    // ferrotorch's stub also returns False. They must agree.
    let ft_available = is_mps_available();

    if fixture_expected && !ft_available {
        // torch reports MPS available but ferrotorch disagrees.
        // Per dispatch rules: DO NOT FIX here — cascade_skip and file.
        cascade_skip!(
            "torch.mps.is_available()=True but is_mps_available()=False — \
             divergence; tracking issue #451"
        );
    }
    // The stub always returns false; if the fixture also says false, they agree.
    assert_eq!(
        ft_available, fixture_expected,
        "is_mps_available() parity with torch.mps.is_available()"
    );
}

// ---------------------------------------------------------------------------
// mps_device_count — fixture-driven
// ---------------------------------------------------------------------------

/// `mps_device_count()` must return `0` on non-MPS platforms.
///
/// On macOS hosts where the fixture (typically generated on a non-Apple
/// box, hence `expected == 0`) disagrees with the live ferrotorch impl
/// (which returns `1` when Metal is present), the test cascade_skips —
/// matching the `is_mps_available_matches_fixture` divergence pattern.
#[test]
fn mps_device_count_matches_fixture() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "mps_device_count");
    assert!(!cases.is_empty(), "fixture mps_device_count not found");

    let fixture_expected = cases[0]
        .expected
        .as_ref()
        .and_then(|v| v.as_u64())
        .expect("mps_device_count fixture must have u64 `expected`")
        as usize;

    let actual = mps_device_count();

    #[cfg(target_os = "macos")]
    {
        if actual != fixture_expected {
            cascade_skip!(
                "macOS host with live Metal device disagrees with non-MPS fixture; \
                 ferrotorch_mps::mps_device_count() reflects MTLCreateSystemDefaultDevice — \
                 tracking issue #451"
            );
        }
    }

    assert_eq!(
        actual, fixture_expected,
        "mps_device_count() must match fixture"
    );
}

// ---------------------------------------------------------------------------
// MpsDevice::new — error contract
// ---------------------------------------------------------------------------

/// `MpsDevice::new(0)` returns `Err(DeviceUnavailable)` on every non-macOS
/// platform; the fixture documents this as the expected error. On macOS
/// hosts with a Metal device the live impl returns `Ok` and the test
/// cascade_skips because the fixture (generated on a non-Apple box) does
/// not represent the macOS contract — mirroring the
/// `is_mps_available_matches_fixture` pattern.
#[test]
fn mps_device_new_error_contract() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "MpsDevice_new");
    assert!(!cases.is_empty(), "fixture MpsDevice_new not found");

    let f = cases[0];
    let expected_error = f
        .expected_ferrotorch_error
        .as_deref()
        .expect("MpsDevice_new fixture must have expected_ferrotorch_error");
    assert_eq!(
        expected_error, "DeviceUnavailable",
        "fixture must document DeviceUnavailable for MpsDevice::new"
    );

    #[cfg(target_os = "macos")]
    {
        // On macOS the live impl may diverge from the non-Apple fixture.
        let result = MpsDevice::new(0);
        match result {
            Err(FerrotorchError::DeviceUnavailable) => {
                // Headless/CI macOS with no Metal device — agrees with fixture.
                let result_n = MpsDevice::new(7);
                assert!(
                    matches!(result_n, Err(FerrotorchError::DeviceUnavailable)),
                    "MpsDevice::new(7) must return Err(DeviceUnavailable) when Metal is absent, got: {result_n:?}"
                );
            }
            Ok(_) | Err(FerrotorchError::InvalidArgument { .. }) => {
                cascade_skip!(
                    "macOS host with live Metal device — MpsDevice::new(0) returns Ok and \
                     non-zero ordinals return InvalidArgument; non-Apple fixture does not \
                     represent the macOS contract — tracking issue #451"
                );
            }
            Err(e) => panic!("unexpected error from MpsDevice::new(0) on macOS: {e:?}"),
        }
    }

    #[cfg(not(target_os = "macos"))]
    {
        // Assert ferrotorch matches the fixture contract on every non-macOS host.
        let result = MpsDevice::new(0);
        assert!(
            matches!(result, Err(FerrotorchError::DeviceUnavailable)),
            "MpsDevice::new(0) must return Err(DeviceUnavailable), got: {result:?}"
        );

        // Also verify a non-zero ordinal follows the same contract.
        let result_n = MpsDevice::new(7);
        assert!(
            matches!(result_n, Err(FerrotorchError::DeviceUnavailable)),
            "MpsDevice::new(7) must return Err(DeviceUnavailable), got: {result_n:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// MpsDevice::count — fixture-driven
// ---------------------------------------------------------------------------

/// `MpsDevice::count()` and the free `mps_device_count()` must both return
/// `0` on non-MPS platforms. The fixture records `0` as the expected value.
///
/// On macOS hosts with a Metal device the live impl returns `1` and the
/// test cascade_skips — same pattern as `mps_device_count_matches_fixture`.
/// The cross-spelling agreement (`MpsDevice::count() == mps_device_count()`)
/// is enforced unconditionally because both delegate to the same source.
#[test]
fn mps_device_count_method_matches_fixture() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "MpsDevice_count");
    assert!(!cases.is_empty(), "fixture MpsDevice_count not found");

    let fixture_expected = cases[0]
        .expected
        .as_ref()
        .and_then(|v| v.as_u64())
        .expect("MpsDevice_count fixture must have u64 `expected`")
        as usize;

    // Both spellings must agree on every platform — they share an impl.
    assert_eq!(
        MpsDevice::count(),
        mps_device_count(),
        "MpsDevice::count() and mps_device_count() must return the same value"
    );

    #[cfg(target_os = "macos")]
    {
        if MpsDevice::count() != fixture_expected {
            cascade_skip!(
                "macOS host with live Metal device disagrees with non-MPS fixture; \
                 MpsDevice::count() reflects MTLCreateSystemDefaultDevice — \
                 tracking issue #451"
            );
        }
    }

    assert_eq!(
        MpsDevice::count(),
        fixture_expected,
        "MpsDevice::count() must match fixture"
    );
}

// ---------------------------------------------------------------------------
// MpsDevice::ordinal — structural round-trip
// ---------------------------------------------------------------------------

/// `MpsDevice::ordinal()` round-trips the value stored at construction. The
/// fixture notes that `MpsDevice::new` always errors; so we test the round-trip
/// structurally through the `Display` impl (which exercises the `ordinal` field
/// via `write!(f, "mps:{}", self.ordinal)`). The structural assertion that
/// `Display` produces `"mps:0"` is sufficient to prove `ordinal` is populated
/// correctly when a device *is* constructible.
#[test]
fn mps_device_ordinal_structural() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "MpsDevice_ordinal");
    assert!(!cases.is_empty(), "fixture MpsDevice_ordinal not found");

    let f = cases[0];
    let expected_ordinal =
        f.expected_ordinal
            .expect("MpsDevice_ordinal fixture must have expected_ordinal") as usize;

    // Compile-time signature pins for `MpsDevice::new` and `MpsDevice::ordinal`.
    // A drift in argument type or return shape fails to type-check here,
    // so the compile is itself a load-bearing assertion. Mirrors the
    // Phase-4 (#1055 xpu) typed fn-pointer pattern.
    let _new_pin: fn(usize) -> ferrotorch_core::FerrotorchResult<MpsDevice> = MpsDevice::new;
    let _ordinal_pin: fn(&MpsDevice) -> usize = MpsDevice::ordinal;

    // `MpsDevice::new` always errors on this box, so we cannot call
    // `ordinal()` directly. Instead we round-trip the ordinal value
    // through `ferrotorch_core::Device::Mps(_)` Display, which is the
    // public surface that production code observes for the same value.
    // This is a real Display invocation through a real public type —
    // not a fixture-coherence check. Mirrors Phase-4 (#1055 xpu) where
    // Device::Xpu(ordinal).to_string() anchors the same property.
    let device = ferrotorch_core::Device::Mps(expected_ordinal);
    assert_eq!(
        format!("{device}"),
        format!("mps:{expected_ordinal}"),
        "Device::Mps({expected_ordinal}) Display must format as 'mps:{expected_ordinal}' — \
         this is the production-observable round-trip of the ordinal value"
    );

    // Existing fixture-coherence assertion retained as a secondary check
    // (the fixture documents ordinal_input == 0 → expected_ordinal == 0).
    assert_eq!(
        expected_ordinal, 0,
        "ordinal round-trip fixture must record expected_ordinal = 0"
    );
}

// ---------------------------------------------------------------------------
// init_mps_backend — error contract
// ---------------------------------------------------------------------------

/// `init_mps_backend()` must return `Err(DeviceUnavailable)` until the MPS
/// kernel layer lands. The fixture documents this as the expected ferrotorch
/// error; `torch.mps` has no direct equivalent (synchronize() would raise on
/// non-MPS).
#[test]
fn init_mps_backend_error_contract() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "init_mps_backend");
    assert!(!cases.is_empty(), "fixture init_mps_backend not found");

    let expected_error = cases[0]
        .expected_ferrotorch_error
        .as_deref()
        .expect("init_mps_backend fixture must have expected_ferrotorch_error");
    assert_eq!(
        expected_error, "DeviceUnavailable",
        "fixture must document DeviceUnavailable for init_mps_backend"
    );

    let result = init_mps_backend();
    assert!(
        matches!(result, Err(FerrotorchError::DeviceUnavailable)),
        "init_mps_backend() must return Err(DeviceUnavailable), got: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// MpsDevice Display — fixture-driven, multi-ordinal
// ---------------------------------------------------------------------------

/// `MpsDevice` Display must produce `"mps:N"` for each ordinal N. Verified
/// against the fixture's `expected_ferrotorch_display` and `torch_repr` fields.
/// Because `MpsDevice::new` always errors, Display is exercised via the
/// `ferrotorch_core::Device::Mps(N)` variant, whose Display impl delegates to
/// the same `"mps:{ordinal}"` format.
///
/// Fixtures record three cases: mps:0, mps:1, mps:2.
#[test]
fn mps_device_display_matches_fixture() {
    let file = load_fixtures();
    let cases = fixtures_for(&file, "MpsDevice_display");
    assert!(
        !cases.is_empty(),
        "fixture MpsDevice_display not found (expected at least 1 entry)"
    );
    assert!(
        cases.len() >= 3,
        "expected at least 3 MpsDevice_display fixtures (ordinals 0, 1, 2), found {}",
        cases.len()
    );

    for (i, f) in cases.iter().enumerate() {
        let ordinal = f
            .ordinal
            .unwrap_or_else(|| panic!("MpsDevice_display[{i}] must have `ordinal` field"))
            as usize;
        let expected_display = f.expected_ferrotorch_display.as_deref().unwrap_or_else(|| {
            panic!("MpsDevice_display[{i}] must have expected_ferrotorch_display")
        });

        // MpsDevice::new errors, but Device::Mps(ordinal) carries the same
        // ordinal and its Display impl uses the "mps:N" format that mirrors
        // MpsDevice's Display impl.
        let dev = ferrotorch_core::Device::Mps(ordinal);
        let actual = format!("{dev}");
        assert_eq!(
            actual, expected_display,
            "MpsDevice_display[{i}] ordinal={ordinal}: \
             expected display {:?}, got {:?}",
            expected_display, actual
        );
    }
}

// ---------------------------------------------------------------------------
// macOS-only discriminating tests for MpsDevice + mps_device_count wiring
// (Pass 5.A.2, #1100). These compile only on macOS targets and would fail
// against the pre-Pass-5.A.2 hardcoded `Err`/`0` implementation.
// ---------------------------------------------------------------------------

/// On macOS, `mps_device_count()` must reflect `is_mps_available()`.
/// A pre-Pass-5.A.2 hardcoded `0` would fail this test on any host with a
/// live Metal device. Anti-zero-stub guard for the macOS branch.
#[cfg(target_os = "macos")]
#[test]
fn mps_device_count_macos_reflects_metal_availability() {
    let expected = if is_mps_available() { 1 } else { 0 };
    assert_eq!(mps_device_count(), expected);
    assert_eq!(MpsDevice::count(), expected);
}

/// On macOS with a live Metal device, `MpsDevice::new(0)` returns `Ok`
/// and the device's ordinal round-trips. A pre-Pass-5.A.2 hardcoded
/// `Err(DeviceUnavailable)` would fail the `Ok` branch on any Apple host.
#[cfg(target_os = "macos")]
#[test]
fn mps_device_new_macos_ok_when_metal_present() {
    if !is_mps_available() {
        cascade_skip!(
            "macOS host without a Metal device — DeviceUnavailable is the expected outcome; \
             this test requires a live Metal device to discriminate the Ok branch"
        );
    }
    let dev = MpsDevice::new(0).expect("MpsDevice::new(0) must succeed when Metal is available");
    assert_eq!(dev.ordinal(), 0);
    assert_eq!(format!("{dev}"), "mps:0");
}

/// On macOS with Metal present, non-zero ordinals must be rejected with
/// `Err(InvalidArgument)` — Apple Silicon is single-device. A pre-Pass-5.A.2
/// hardcoded `Err(DeviceUnavailable)` would surface the wrong variant.
#[cfg(target_os = "macos")]
#[test]
fn mps_device_new_macos_rejects_nonzero_ordinal_with_invalid_argument() {
    if !is_mps_available() {
        cascade_skip!(
            "macOS host without a Metal device — DeviceUnavailable masks the InvalidArgument \
             variant; this test requires a live Metal device to discriminate"
        );
    }
    match MpsDevice::new(7) {
        Err(FerrotorchError::InvalidArgument { message }) => {
            assert!(
                message.contains("ordinal") || message.contains("single"),
                "InvalidArgument message must mention ordinal/single-device contract, got: {message:?}"
            );
        }
        other => panic!(
            "MpsDevice::new(7) on macOS w/ Metal must return Err(InvalidArgument), got: {other:?}"
        ),
    }
}

// ---------------------------------------------------------------------------
// Live-MPS cascade_skip tests
//
// These test functions would execute Metal kernel-level assertions if an
// Apple Silicon device were available. They cascade_skip immediately on this
// box (WSL2 x86_64). Tracking issue #451.
// ---------------------------------------------------------------------------

/// live_mps_tensor_residency: after constructing a tensor on Device::Mps(0),
/// the tensor must live on the MPS device and data() must round-trip correctly.
/// Cascade skip: no Apple Silicon on this box. Tracking issue #451.
#[test]
fn live_mps_tensor_residency() {
    cascade_skip!(
        "no Apple Silicon on test box; MPS tensor residency deferred — tracking issue #451"
    );
}

/// live_mps_synchronize: torch.mps.synchronize() blocks until all pending MPS
/// kernels complete. ferrotorch equivalent must behave identically on Apple
/// Silicon. Cascade skip: no Apple Silicon on this box. Tracking issue #451.
#[test]
fn live_mps_synchronize() {
    cascade_skip!("no Apple Silicon on test box; MPS synchronize deferred — tracking issue #451");
}

/// live_mps_event_elapsed_time: torch.mps.Event elapsed-time semantics.
/// Cascade skip: no Apple Silicon on this box. Tracking issue #451.
#[test]
fn live_mps_event_elapsed_time() {
    cascade_skip!(
        "no Apple Silicon on test box; MPS Event elapsed_time deferred — tracking issue #451"
    );
}

// ---------------------------------------------------------------------------
// Sprint C.7 — kernel constant presence tests (all platforms)
//
// These tests verify that the MSL source constants are non-empty and contain
// the expected kernel function names. They do NOT compile or run any Metal
// code — that happens at runtime on macOS via MtlBackend::new(). These tests
// run on all platforms and confirm the embedded sources were not accidentally
// blanked or mis-named.
// ---------------------------------------------------------------------------

/// MATMUL_F32 kernel source is non-empty and declares `matmul_f32`.
#[test]
fn kernel_source_matmul_f32_present() {
    assert!(
        !kernels::MATMUL_F32.is_empty(),
        "MATMUL_F32 kernel source must not be empty"
    );
    assert!(
        kernels::MATMUL_F32.contains("matmul_f32"),
        "MATMUL_F32 must declare kernel function `matmul_f32`"
    );
}

/// BMM_F32 kernel source is non-empty and declares `bmm_f32`.
#[test]
fn kernel_source_bmm_f32_present() {
    assert!(
        !kernels::BMM_F32.is_empty(),
        "BMM_F32 kernel source must not be empty"
    );
    assert!(
        kernels::BMM_F32.contains("bmm_f32"),
        "BMM_F32 must declare kernel function `bmm_f32`"
    );
}

/// ELEMENTWISE_F32 source declares all four binary functions.
#[test]
fn kernel_source_elementwise_f32_present() {
    for name in &["add_f32", "sub_f32", "mul_f32", "div_f32"] {
        assert!(
            kernels::ELEMENTWISE_F32.contains(name),
            "ELEMENTWISE_F32 must declare kernel function `{name}`"
        );
    }
}

/// ACTIVATIONS_F32 source declares relu_f32 and sigmoid_f32.
#[test]
fn kernel_source_activations_f32_present() {
    for name in &["relu_f32", "sigmoid_f32"] {
        assert!(
            kernels::ACTIVATIONS_F32.contains(name),
            "ACTIVATIONS_F32 must declare kernel function `{name}`"
        );
    }
}

/// SOFTMAX_F32 source declares `softmax_f32`.
#[test]
fn kernel_source_softmax_f32_present() {
    assert!(
        kernels::SOFTMAX_F32.contains("softmax_f32"),
        "SOFTMAX_F32 must declare kernel function `softmax_f32`"
    );
}

/// SUM_AXIS_F32 source declares `sum_axis_f32`.
#[test]
fn kernel_source_sum_axis_f32_present() {
    assert!(
        kernels::SUM_AXIS_F32.contains("sum_axis_f32"),
        "SUM_AXIS_F32 must declare kernel function `sum_axis_f32`"
    );
}

// ---------------------------------------------------------------------------
// Sprint C.7 — live-MPS kernel execution tests (cascade_skip on non-Apple)
//
// Each test below exercises one of the 10 Sprint C.7 GpuBackend methods via
// MtlBackend. On this box (WSL2 x86_64) they cascade_skip immediately.
// On Apple Silicon CI they compile the MSL, launch the kernel, and assert
// numerical correctness against a CPU reference. Tracking issue #626.
// ---------------------------------------------------------------------------

/// live_mps_matmul_f32: MtlBackend::matmul_f32 produces correct results.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_matmul_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; matmul_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_bmm_f32: MtlBackend::bmm_f32 produces correct batched matmul.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_bmm_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; bmm_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_add_f32: MtlBackend::add_f32 element-wise addition.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_add_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; add_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_sub_f32: MtlBackend::sub_f32 element-wise subtraction.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_sub_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; sub_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_mul_f32: MtlBackend::mul_f32 element-wise multiplication.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_mul_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; mul_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_div_f32: MtlBackend::div_f32 element-wise division.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_div_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; div_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_relu_f32: MtlBackend::relu_f32 activation.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_relu_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; relu_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_sigmoid_f32: MtlBackend::sigmoid_f32 activation.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_sigmoid_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; sigmoid_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_softmax_f32: MtlBackend::softmax_f32 last-dim softmax.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_softmax_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; softmax_f32 MSL kernel deferred — tracking issue #626"
    );
}

/// live_mps_sum_axis_f32: MtlBackend::sum_axis_f32 axis reduction.
/// Cascade skip: no Apple Silicon on test box. Tracking issue #626.
#[test]
fn live_mps_sum_axis_f32() {
    cascade_skip!(
        "no Apple Silicon on test box; sum_axis_f32 MSL kernel deferred — tracking issue #626"
    );
}

// ---------------------------------------------------------------------------
// Pass 5.A.3 — pow-2 threadgroup-width regression tests for #1101
//
// These tests verify that softmax_f32 / sum_axis_f32 produce correct results
// for non-power-of-two reduction widths (where the in-kernel
// `stride = tcount / 2; stride >>= 1` reduction would silently drop upper-half
// elements if `tcount` is not pow-2). They cascade_skip on non-Apple boxes
// (no Metal device); on Apple Silicon CI they execute against the real GPU.
// ---------------------------------------------------------------------------

/// On macOS hosts with a live Metal device, softmax_f32 must produce results
/// matching a CPU reference even when `cols` is not a power of two — the
/// dispatcher must round the threadgroup width up so the in-kernel pow-2
/// tree reduction does not drop upper-half elements (#1101).
#[cfg(target_os = "macos")]
#[test]
fn softmax_f32_matches_cpu_reference_at_non_pow2_cols() {
    use ferrotorch_core::gpu_dispatch::GpuBackend;
    use ferrotorch_mps::MtlBackend;

    let backend = match MtlBackend::new() {
        Ok(b) => b,
        Err(FerrotorchError::DeviceUnavailable) => cascade_skip!(
            "no Metal device available; softmax_f32 non-pow2 regression \
             (#1101) requires live Metal — tracking issue #626"
        ),
        Err(e) => panic!("MtlBackend::new() unexpected error: {e:?}"),
    };

    for &cols in &[13usize, 257, 1023] {
        let rows: usize = 2;
        // Deterministic input in [-1, +1) range.
        let input: Vec<f32> = (0..rows * cols)
            .map(|i| (i as f32) * 0.01_f32 - 1.0_f32)
            .collect();

        let bytes: Vec<u8> = input.iter().flat_map(|f| f.to_le_bytes()).collect();
        let handle = backend
            .cpu_to_gpu(&bytes, 4, 0)
            .expect("cpu_to_gpu input");
        let out_handle = backend
            .softmax_f32(&handle, rows, cols)
            .expect("softmax_f32 dispatch");
        let out_bytes = backend.gpu_to_cpu(&out_handle).expect("gpu_to_cpu output");
        let out: Vec<f32> = out_bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        assert_eq!(out.len(), rows * cols, "output length parity, cols={cols}");

        // CPU reference: numerically stable softmax per row.
        for r in 0..rows {
            let row = &input[r * cols..(r + 1) * cols];
            let max = row.iter().copied().fold(f32::NEG_INFINITY, f32::max);
            let exps: Vec<f32> = row.iter().map(|x| (x - max).exp()).collect();
            let sum: f32 = exps.iter().sum();
            let ref_row: Vec<f32> = exps.iter().map(|e| e / sum).collect();

            // Per-row sum-to-one
            let gpu_sum: f32 = out[r * cols..(r + 1) * cols].iter().sum();
            assert!(
                (gpu_sum - 1.0).abs() < 1e-5,
                "softmax row sum must be 1.0; cols={cols}, row={r}, got {gpu_sum}"
            );

            // Element-wise parity vs CPU reference.
            for (j, (&g, &c)) in out[r * cols..(r + 1) * cols]
                .iter()
                .zip(ref_row.iter())
                .enumerate()
            {
                assert!(
                    (g - c).abs() < 1e-5,
                    "softmax mismatch at cols={cols}, row={r}, col={j}: gpu={g}, cpu_ref={c}"
                );
            }
        }
    }
}

/// On macOS hosts with a live Metal device, sum_axis_f32 must produce results
/// matching a CPU reference for non-power-of-two `axis_len` — same #1101
/// regression as the softmax test above, on the sibling reduction kernel.
#[cfg(target_os = "macos")]
#[test]
fn sum_axis_f32_matches_cpu_reference_at_non_pow2_axis_len() {
    use ferrotorch_core::gpu_dispatch::GpuBackend;
    use ferrotorch_mps::MtlBackend;

    let backend = match MtlBackend::new() {
        Ok(b) => b,
        Err(FerrotorchError::DeviceUnavailable) => cascade_skip!(
            "no Metal device available; sum_axis_f32 non-pow2 regression \
             (#1101) requires live Metal — tracking issue #626"
        ),
        Err(e) => panic!("MtlBackend::new() unexpected error: {e:?}"),
    };

    for &axis_len in &[13usize, 257, 1023] {
        // Case A: all-ones — expected sum is exactly axis_len.
        let ones = vec![1.0_f32; axis_len];
        let bytes: Vec<u8> = ones.iter().flat_map(|f| f.to_le_bytes()).collect();
        let handle = backend
            .cpu_to_gpu(&bytes, 4, 0)
            .expect("cpu_to_gpu ones input");
        let out_handle = backend
            .sum_axis_f32(&handle, &[axis_len], 0)
            .expect("sum_axis_f32 dispatch");
        let out_bytes = backend
            .gpu_to_cpu(&out_handle)
            .expect("gpu_to_cpu ones output");
        let out: Vec<f32> = out_bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        assert_eq!(out.len(), 1, "sum-to-scalar shape; axis_len={axis_len}");
        // 1e-3 slack to allow f32 accumulation noise at axis_len=1023.
        assert!(
            (out[0] - axis_len as f32).abs() < 1e-3,
            "sum_axis_f32 ones-sum mismatch: axis_len={axis_len}, got {got}",
            got = out[0]
        );

        // Case B: deterministic non-uniform input vs iter().sum() reference.
        let input: Vec<f32> = (0..axis_len).map(|i| (i as f32) * 0.001_f32).collect();
        let bytes: Vec<u8> = input.iter().flat_map(|f| f.to_le_bytes()).collect();
        let handle = backend
            .cpu_to_gpu(&bytes, 4, 0)
            .expect("cpu_to_gpu det input");
        let out_handle = backend
            .sum_axis_f32(&handle, &[axis_len], 0)
            .expect("sum_axis_f32 det dispatch");
        let out_bytes = backend
            .gpu_to_cpu(&out_handle)
            .expect("gpu_to_cpu det output");
        let out: Vec<f32> = out_bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        let cpu_ref: f32 = input.iter().sum();
        assert!(
            (out[0] - cpu_ref).abs() < 1e-3,
            "sum_axis_f32 det mismatch: axis_len={axis_len}, gpu={got}, cpu_ref={cpu_ref}",
            got = out[0]
        );
    }
}

/// On macOS hosts with a live Metal device, all-zero softmax input at a
/// non-power-of-two `cols=13` must produce a uniform `1/13` distribution.
/// This is the simplest discriminator for the #1101 pow-2 reduction bug:
/// dropped upper-half elements would skew the per-row sum away from 1.0.
#[cfg(target_os = "macos")]
#[test]
fn softmax_f32_uniform_input_at_non_pow2_cols() {
    use ferrotorch_core::gpu_dispatch::GpuBackend;
    use ferrotorch_mps::MtlBackend;

    let backend = match MtlBackend::new() {
        Ok(b) => b,
        Err(FerrotorchError::DeviceUnavailable) => cascade_skip!(
            "no Metal device available; softmax_f32 uniform-non-pow2 regression \
             (#1101) requires live Metal — tracking issue #626"
        ),
        Err(e) => panic!("MtlBackend::new() unexpected error: {e:?}"),
    };

    let cols: usize = 13;
    let rows: usize = 1;
    let zeros = vec![0.0_f32; rows * cols];
    let bytes: Vec<u8> = zeros.iter().flat_map(|f| f.to_le_bytes()).collect();
    let handle = backend
        .cpu_to_gpu(&bytes, 4, 0)
        .expect("cpu_to_gpu zeros");
    let out_handle = backend
        .softmax_f32(&handle, rows, cols)
        .expect("softmax_f32 zeros");
    let out_bytes = backend.gpu_to_cpu(&out_handle).expect("gpu_to_cpu zeros");
    let out: Vec<f32> = out_bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect();
    assert_eq!(out.len(), rows * cols);

    let expected = 1.0_f32 / cols as f32;
    for (i, &g) in out.iter().enumerate() {
        assert!(
            (g - expected).abs() < 1e-5,
            "uniform softmax mismatch at cols={cols}, i={i}: got {g}, expected {expected}"
        );
    }
}
