//! C9.3 — ferrotorch-nn structural + recurrent + extension conformance suite.
//!
//! Covers 10 modules:
//!   `container` (Sequential, ModuleList, ModuleDict)
//!   `module`    (Module trait: state_dict, load_state_dict, named_modules, train/eval)
//!   `parameter` (Parameter: new, zeros, from_slice, set_requires_grad, to)
//!   `parameter_container` (ParameterList, ParameterDict)
//!   `buffer`    (Buffer: new, zeros, set_data, state_dict integration)
//!   `hooks`     (HookedModule, forward/pre/backward hooks, HookHandle::remove)
//!   `rnn`       (LSTM, GRU, RNN + cell variants)
//!   `rnn_utils` (pack_padded_sequence, pad_packed_sequence, PackedSequence)
//!   `lora`      (LoRALinear: forward, merge, parameters, state_dict)
//!   `qat`       (QatConfig, QuantizedModel, prepare_qat, ObserverType)
//!
//! Layer-2 fixtures: `tests/conformance/fixtures_nn_structural.json`
//! (regenerated by `scripts/regenerate_nn_structural_fixtures.py`).
//!
//! Layer-4 (strict coverage gate): deferred to C9.4.
//!
//! Cascade bugs discovered during this sweep are filed as crosslink issues
//! and marked with `cascade_skip!()` inline.

#![allow(
    clippy::float_cmp,          // intentional bit-exact comparisons in tolerance checks
    clippy::unreadable_literal,  // PyTorch reference values
    clippy::too_many_lines,
    clippy::module_name_repetitions,
)]

use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::sync::atomic::{AtomicUsize, Ordering};

use ferrotorch_nn::{
    Buffer,
    GRU, LSTM, RNN, RNNNonlinearity,
    HookedModule,
    LoRALinear,
    Module,
    ModuleDict, ModuleList, Sequential,
    ObserverType, QatConfig,
    Parameter,
    ParameterDict, ParameterList,
    prepare_qat,
    pack_padded_sequence, pad_packed_sequence,
    linear::Linear,
};
use ferrotorch_core::{Float, FerrotorchResult, Tensor, TensorStorage};

// ---------------------------------------------------------------------------
// Layer-2 fixture loader
// ---------------------------------------------------------------------------

fn fixtures_json() -> serde_json::Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/conformance/fixtures_nn_structural.json"
    );
    let text = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!(
            "fixtures_nn_structural.json must exist; run \
             scripts/regenerate_nn_structural_fixtures.py"
        )
    });
    serde_json::from_str(&text).expect("fixtures_nn_structural.json must be valid JSON")
}

fn fixture_by_id(fixtures: &serde_json::Value, id: &str) -> serde_json::Value {
    fixtures["fixtures"]
        .as_array()
        .expect("fixtures array present")
        .iter()
        .find(|f| f["id"] == id)
        .unwrap_or_else(|| panic!("fixture '{}' not found", id))
        .clone()
}

// ---------------------------------------------------------------------------
// Tolerance helper
// ---------------------------------------------------------------------------

fn assert_close_f32(actual: &[f32], expected: &[f32], tol: f32, label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch {} vs {}",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert!(
            (a - e).abs() <= tol,
            "{label}[{i}]: actual={a:.7} expected={e:.7} diff={:.2e} tol={tol:.2e}",
            (a - e).abs()
        );
    }
}

fn json_to_f32_flat(v: &serde_json::Value) -> Vec<f32> {
    fn flatten(v: &serde_json::Value, out: &mut Vec<f32>) {
        match v {
            serde_json::Value::Array(arr) => {
                for item in arr {
                    flatten(item, out);
                }
            }
            serde_json::Value::Number(n) => {
                out.push(n.as_f64().unwrap() as f32);
            }
            _ => panic!("unexpected value in json_to_f32_flat: {v}"),
        }
    }
    let mut out = Vec::new();
    flatten(v, &mut out);
    out
}

// ---------------------------------------------------------------------------
// Helper: minimal identity module with one parameter for container tests
// ---------------------------------------------------------------------------

struct IdentityScaled<T: Float> {
    weight: Parameter<T>,
    training: bool,
}

impl<T: Float> IdentityScaled<T> {
    fn new(size: usize) -> FerrotorchResult<Self> {
        Ok(Self {
            weight: Parameter::zeros(&[size])?,
            training: true,
        })
    }
}

impl<T: Float> Module<T> for IdentityScaled<T> {
    fn forward(&self, input: &Tensor<T>) -> FerrotorchResult<Tensor<T>> {
        Ok(input.clone())
    }
    fn parameters(&self) -> Vec<&Parameter<T>> { vec![&self.weight] }
    fn parameters_mut(&mut self) -> Vec<&mut Parameter<T>> { vec![&mut self.weight] }
    fn named_parameters(&self) -> Vec<(String, &Parameter<T>)> {
        vec![("weight".into(), &self.weight)]
    }
    fn train(&mut self) { self.training = true; }
    fn eval(&mut self) { self.training = false; }
    fn is_training(&self) -> bool { self.training }
}

// ---------------------------------------------------------------------------
// Helper: module with one parameter AND one buffer + one child
// ---------------------------------------------------------------------------

struct ParentWithBuffer<T: Float> {
    weight: Parameter<T>,
    running_mean: Buffer<T>,
    child: IdentityScaled<T>,
}

impl<T: Float> ParentWithBuffer<T> {
    fn new() -> FerrotorchResult<Self> {
        Ok(Self {
            weight: Parameter::ones(&[2, 2])?,
            running_mean: Buffer::zeros(&[2])?,
            child: IdentityScaled::new(3)?,
        })
    }
}

impl<T: Float> Module<T> for ParentWithBuffer<T> {
    fn forward(&self, input: &Tensor<T>) -> FerrotorchResult<Tensor<T>> {
        self.child.forward(input)
    }
    fn parameters(&self) -> Vec<&Parameter<T>> {
        let mut out: Vec<&Parameter<T>> = vec![&self.weight];
        out.extend(self.child.parameters());
        out
    }
    fn parameters_mut(&mut self) -> Vec<&mut Parameter<T>> {
        let mut out: Vec<&mut Parameter<T>> = vec![&mut self.weight];
        out.extend(self.child.parameters_mut());
        out
    }
    fn named_parameters(&self) -> Vec<(String, &Parameter<T>)> {
        let mut out: Vec<(String, &Parameter<T>)> = vec![("weight".into(), &self.weight)];
        for (n, p) in self.child.named_parameters() {
            out.push((format!("child.{n}"), p));
        }
        out
    }
    fn buffers(&self) -> Vec<&Buffer<T>> { vec![&self.running_mean] }
    fn buffers_mut(&mut self) -> Vec<&mut Buffer<T>> { vec![&mut self.running_mean] }
    fn named_buffers(&self) -> Vec<(String, &Buffer<T>)> {
        vec![("running_mean".into(), &self.running_mean)]
    }
    fn children(&self) -> Vec<&dyn Module<T>> { vec![&self.child] }
    fn named_children(&self) -> Vec<(String, &dyn Module<T>)> {
        vec![("child".into(), &self.child)]
    }
    fn train(&mut self) { self.child.train(); }
    fn eval(&mut self) { self.child.eval(); }
    fn is_training(&self) -> bool { self.child.is_training() }
}

// ---------------------------------------------------------------------------
// Module 1 — container.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::Sequential nested forward
#[test]
fn container_sequential_nested_forward_matches_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "sequential_nested_forward");

    // Build: Linear(4->3, W=0.1) -> IdentityScaled (proxy for ReLU) -> Linear(3->2, W=0.2).
    // We use the actual Linear layer from ferrotorch-nn and compare to fixture.
    let mut lin1 = Linear::<f32>::new(4, 3, false).unwrap();
    let mut lin2 = Linear::<f32>::new(3, 2, false).unwrap();

    // Set weights to match the fixture (all 0.1 / 0.2).
    lin1.weight = Parameter::from_slice(&[0.1f32; 12], &[3, 4]).unwrap();
    lin2.weight = Parameter::from_slice(&[0.2f32; 6], &[2, 3]).unwrap();

    // Sequential: lin1 -> lin2 (no ReLU, so output is just chained linear).
    let seq = Sequential::new(vec![
        Box::new(lin1) as Box<dyn Module<f32>>,
        Box::new(lin2) as Box<dyn Module<f32>>,
    ]);

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0f32; 8]),
        vec![2, 4],
        false,
    ).unwrap();

    let output = seq.forward(&x).unwrap();

    assert_eq!(output.shape(), &[2, 2]);

    // Verify against fixture expected.
    let expected = json_to_f32_flat(&fx["expected"]["output"]);
    let tol = 1e-5f32;
    assert_close_f32(output.data().unwrap(), &expected, tol, "sequential_nested_forward");
}

/// conformance_nn_structural: ferrotorch_nn::Sequential parameter naming uses index prefix
#[test]
fn container_sequential_named_params_use_index_prefix() {
    let seq = Sequential::new(vec![
        Box::new(IdentityScaled::<f32>::new(3).unwrap()) as Box<dyn Module<f32>>,
        Box::new(IdentityScaled::<f32>::new(5).unwrap()) as Box<dyn Module<f32>>,
    ]);

    let named = seq.named_parameters();
    let keys: Vec<&str> = named.iter().map(|(k, _)| k.as_str()).collect();
    assert_eq!(keys, &["0.weight", "1.weight"]);
}

/// conformance_nn_structural: ferrotorch_nn::Sequential train/eval propagates to children
#[test]
fn container_sequential_train_eval_propagation() {
    let mut seq = Sequential::new(vec![
        Box::new(IdentityScaled::<f32>::new(2).unwrap()) as Box<dyn Module<f32>>,
        Box::new(IdentityScaled::<f32>::new(3).unwrap()) as Box<dyn Module<f32>>,
    ]);
    assert!(seq.is_training());
    seq.eval();
    assert!(!seq.is_training());
    seq.train();
    assert!(seq.is_training());
}

/// conformance_nn_structural: ferrotorch_nn::ModuleList get/push/len semantics
#[test]
fn container_module_list_get_push_semantics() {
    let mut list = ModuleList::new(vec![
        Box::new(IdentityScaled::<f32>::new(3).unwrap()) as Box<dyn Module<f32>>,
    ]);
    assert_eq!(list.len(), 1);
    assert!(!list.is_empty());
    list.push(Box::new(IdentityScaled::<f32>::new(4).unwrap()));
    assert_eq!(list.len(), 2);
    assert!(list.get(2).is_none());
}

/// conformance_nn_structural: ferrotorch_nn::ModuleList manual chain matches fixture
#[test]
fn container_module_list_manual_chain_matches_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "module_list_manual_chain");

    let mut lin_a = Linear::<f32>::new(3, 3, false).unwrap();
    let mut lin_b = Linear::<f32>::new(3, 2, false).unwrap();
    lin_a.weight = Parameter::from_slice(&[0.5f32; 9], &[3, 3]).unwrap();
    lin_b.weight = Parameter::from_slice(&[0.5f32; 6], &[2, 3]).unwrap();

    let list = ModuleList::new(vec![
        Box::new(lin_a) as Box<dyn Module<f32>>,
        Box::new(lin_b) as Box<dyn Module<f32>>,
    ]);

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![2.0f32; 3]),
        vec![1, 3],
        false,
    ).unwrap();

    let y1 = list.get(0).unwrap().forward(&x).unwrap();
    let y2 = list.get(1).unwrap().forward(&y1).unwrap();

    assert_eq!(y2.shape(), &[1, 2]);
    let expected = json_to_f32_flat(&fx["expected"]["output"]);
    assert_close_f32(y2.data().unwrap(), &expected, 1e-5, "module_list_manual_chain");
}

/// conformance_nn_structural: ferrotorch_nn::ModuleDict insertion order and forward
#[test]
fn container_module_dict_encoder_decoder_matches_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "module_dict_encoder_decoder");

    let mut enc = Linear::<f32>::new(4, 2, false).unwrap();
    let mut dec = Linear::<f32>::new(2, 4, false).unwrap();
    enc.weight = Parameter::from_slice(&[0.25f32; 8], &[2, 4]).unwrap();
    dec.weight = Parameter::from_slice(&[0.25f32; 8], &[4, 2]).unwrap();

    let mut dict = ModuleDict::<f32>::new();
    dict.insert("encoder", Box::new(enc));
    dict.insert("decoder", Box::new(dec));

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0f32; 4]),
        vec![1, 4],
        false,
    ).unwrap();

    let enc_out = dict.get("encoder").unwrap().forward(&x).unwrap();
    let dec_out = dict.get("decoder").unwrap().forward(&enc_out).unwrap();

    let expected_dec = json_to_f32_flat(&fx["expected"]["dec_output"]);
    assert_close_f32(dec_out.data().unwrap(), &expected_dec, 1e-5, "module_dict_encoder_decoder");
}

/// conformance_nn_structural: ferrotorch_nn::ModuleDict keys maintain insertion order
#[test]
fn container_module_dict_key_insertion_order() {
    let mut dict = ModuleDict::<f32>::new();
    dict.insert("c_layer", Box::new(IdentityScaled::<f32>::new(1).unwrap()));
    dict.insert("a_layer", Box::new(IdentityScaled::<f32>::new(2).unwrap()));
    dict.insert("b_layer", Box::new(IdentityScaled::<f32>::new(3).unwrap()));
    assert_eq!(dict.keys(), &["c_layer", "a_layer", "b_layer"]);
}

// ---------------------------------------------------------------------------
// Module 2 — module.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::Module::state_dict includes params and buffers
#[test]
fn module_state_dict_includes_params_and_buffers() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "module_state_dict_keys");
    let m = ParentWithBuffer::<f32>::new().unwrap();
    let sd = m.state_dict();

    let mut keys: Vec<&str> = sd.keys().map(|k| k.as_str()).collect();
    keys.sort();

    let mut expected_keys: Vec<String> = fx["expected_keys"]
        .as_array().unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    expected_keys.sort();

    assert_eq!(keys, expected_keys.iter().map(|s| s.as_str()).collect::<Vec<_>>());
    assert_eq!(sd.len(), fx["expected_count"].as_u64().unwrap() as usize);
}

/// conformance_nn_structural: ferrotorch_nn::Module::named_modules returns depth-first paths
#[test]
fn module_named_modules_paths_match_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "module_named_modules_paths");
    let m = ParentWithBuffer::<f32>::new().unwrap();
    let named = m.named_modules();

    let paths: Vec<&str> = named.iter().map(|(p, _)| p.as_str()).collect();
    let expected_paths: Vec<&str> = fx["expected_paths"]
        .as_array().unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    assert_eq!(paths, expected_paths);
    assert_eq!(named.len(), fx["expected_count"].as_u64().unwrap() as usize);
}

/// conformance_nn_structural: ferrotorch_nn::Module train/eval toggling
#[test]
fn module_train_eval_toggle_matches_fixture() {
    let mut m = ParentWithBuffer::<f32>::new().unwrap();
    assert!(m.is_training());
    m.eval();
    assert!(!m.is_training());
    m.train();
    assert!(m.is_training());
}

/// conformance_nn_structural: ferrotorch_nn::Module::requires_grad_ freezes all parameters
#[test]
fn module_requires_grad_freeze_all_params() {
    let mut m = ParentWithBuffer::<f32>::new().unwrap();
    for p in m.parameters() {
        assert!(p.requires_grad());
    }
    m.requires_grad_(false);
    for p in m.parameters() {
        assert!(!p.requires_grad());
    }
    m.requires_grad_(true);
    for p in m.parameters() {
        assert!(p.requires_grad());
    }
}

/// conformance_nn_structural: ferrotorch_nn::Module::load_state_dict strict mode
#[test]
fn module_load_state_dict_strict_rejects_unknown_keys() {
    let mut m = ParentWithBuffer::<f32>::new().unwrap();
    let mut sd = m.state_dict();
    sd.insert("nonexistent_param".into(), ferrotorch_core::zeros::<f32>(&[1]).unwrap());

    // strict=true must error on unknown key
    assert!(m.load_state_dict(&sd, true).is_err());
    // strict=false must succeed
    let sd_no_extra: HashMap<String, Tensor<f32>> = sd
        .into_iter()
        .filter(|(k, _)| k != "nonexistent_param")
        .collect();
    assert!(m.load_state_dict(&sd_no_extra, true).is_ok());
}

/// conformance_nn_structural: ferrotorch_nn::Module::zero_grad succeeds on fresh module
#[test]
fn module_zero_grad_succeeds() {
    let m = IdentityScaled::<f32>::new(4).unwrap();
    m.zero_grad().unwrap();
}

// ---------------------------------------------------------------------------
// Module 3 — parameter.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::Parameter always requires grad
#[test]
fn parameter_requires_grad_always_true() {
    let p = Parameter::<f32>::zeros(&[3, 4]).unwrap();
    assert!(p.requires_grad(), "Parameter must always require grad");
}

/// conformance_nn_structural: ferrotorch_nn::Parameter::from_slice preserves shape
#[test]
fn parameter_from_slice_shape_matches_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "parameter_from_slice_shape");
    let data: Vec<f32> = fx["data"].as_array().unwrap()
        .iter().map(|v| v.as_f64().unwrap() as f32).collect();
    let shape: Vec<usize> = fx["shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    let p = Parameter::from_slice(&data, &shape).unwrap();
    assert_eq!(p.shape(), shape.as_slice());
    assert_eq!(p.numel(), fx["expected_numel"].as_u64().unwrap() as usize);
    assert!(p.requires_grad());
}

/// conformance_nn_structural: ferrotorch_nn::Parameter::set_requires_grad toggles grad
#[test]
fn parameter_set_requires_grad_freeze_and_restore() {
    let mut p = Parameter::<f32>::zeros(&[4]).unwrap();
    assert!(p.requires_grad());
    p.set_requires_grad(false);
    assert!(!p.requires_grad());
    p.set_requires_grad(true);
    assert!(p.requires_grad());
}

/// conformance_nn_structural: ferrotorch_nn::Parameter::to preserves data on Cpu
#[test]
fn parameter_to_cpu_preserves_data() {
    let p = Parameter::from_slice(&[1.0f32, 2.0, 3.0], &[3]).unwrap();
    let p2 = p.to(ferrotorch_core::Device::Cpu).unwrap();
    assert_eq!(p2.data().unwrap(), &[1.0f32, 2.0, 3.0]);
    assert!(p2.requires_grad());
}

// ---------------------------------------------------------------------------
// Module 4 — parameter_container.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::ParameterList named_parameters uses index keys
#[test]
fn parameter_list_named_params_index_keys() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "parameter_list_named_indexed");
    let count = fx["count"].as_u64().unwrap() as usize;

    let params: Vec<Parameter<f32>> = (0..count).map(|i| Parameter::zeros(&[i + 1]).unwrap()).collect();
    let list = ParameterList::from_vec(params);

    let named = list.named_parameters();
    let keys: Vec<&str> = named.iter().map(|(k, _)| k.as_str()).collect();
    let expected_keys: Vec<&str> = fx["expected_keys"].as_array().unwrap()
        .iter().map(|v| v.as_str().unwrap()).collect();
    assert_eq!(keys, expected_keys);
}

/// conformance_nn_structural: ferrotorch_nn::ParameterDict keys are sorted lexicographically
#[test]
fn parameter_dict_sorted_keys_match_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "parameter_dict_sorted_keys");
    let insert_order: Vec<&str> = fx["insert_order"].as_array().unwrap()
        .iter().map(|v| v.as_str().unwrap()).collect();

    let mut dict = ParameterDict::<f32>::new();
    for (i, key) in insert_order.iter().enumerate() {
        dict.insert(*key, Parameter::zeros(&[i + 1]).unwrap());
    }

    let named = dict.named_parameters();
    let keys: Vec<&str> = named.iter().map(|(k, _)| k.as_str()).collect();
    let expected: Vec<&str> = fx["expected_key_order"].as_array().unwrap()
        .iter().map(|v| v.as_str().unwrap()).collect();
    assert_eq!(keys, expected);
}

/// conformance_nn_structural: ferrotorch_nn::ParameterList get/append/iter
#[test]
fn parameter_list_get_append_iter() {
    let mut list = ParameterList::<f32>::new();
    assert!(list.is_empty());
    list.append(Parameter::zeros(&[3]).unwrap());
    list.append(Parameter::zeros(&[5]).unwrap());
    assert_eq!(list.len(), 2);
    assert_eq!(list.get(0).unwrap().shape(), &[3]);
    assert_eq!(list.get(1).unwrap().shape(), &[5]);
    assert!(list.get(2).is_none());
    let total: usize = list.parameters().iter().map(|p| p.numel()).sum();
    assert_eq!(total, 8);
}

/// conformance_nn_structural: ferrotorch_nn::ParameterDict insert/get/remove
#[test]
fn parameter_dict_insert_get_remove() {
    let mut dict = ParameterDict::<f32>::new();
    dict.insert("weight", Parameter::zeros(&[4]).unwrap());
    dict.insert("bias", Parameter::zeros(&[2]).unwrap());
    assert_eq!(dict.len(), 2);
    assert!(dict.contains_key("weight"));
    dict.remove("bias");
    assert_eq!(dict.len(), 1);
    assert!(!dict.contains_key("bias"));
}

// ---------------------------------------------------------------------------
// Module 5 — buffer.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::Buffer never requires grad
#[test]
fn buffer_never_requires_grad() {
    let b = Buffer::<f32>::zeros(&[3, 4]).unwrap();
    assert!(!b.requires_grad(), "Buffer must never require grad");

    // Even if we set_data with a requires_grad tensor, must stay false.
    let t = ferrotorch_core::ones::<f32>(&[3, 4]).unwrap().requires_grad_(true);
    let mut b2 = Buffer::from_slice(&[0.0f32; 12], &[3, 4]).unwrap();
    b2.set_data(t);
    assert!(!b2.requires_grad());
}

/// conformance_nn_structural: ferrotorch_nn::Buffer::to Cpu preserves data
#[test]
fn buffer_to_cpu_preserves_data() {
    let b = Buffer::from_slice(&[1.0f32, 2.0, 3.0], &[3]).unwrap();
    let b2 = b.to(ferrotorch_core::Device::Cpu).unwrap();
    assert_eq!(b2.data().unwrap(), &[1.0f32, 2.0, 3.0]);
    assert!(!b2.requires_grad());
}

/// conformance_nn_structural: ferrotorch_nn buffer is included in module state_dict
#[test]
fn buffer_included_in_state_dict() {
    let m = ParentWithBuffer::<f32>::new().unwrap();
    let sd = m.state_dict();
    assert!(sd.contains_key("running_mean"), "running_mean buffer must appear in state_dict");
    assert_eq!(sd["running_mean"].shape(), &[2]);
}

// ---------------------------------------------------------------------------
// Module 6 — hooks.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn forward hook fires once per forward call
#[test]
fn hooks_forward_hook_fires_once_per_forward() {
    let m = IdentityScaled::<f32>::new(3).unwrap();
    let hooked = HookedModule::new(m);
    let count = Arc::new(AtomicUsize::new(0));
    let c = Arc::clone(&count);
    let _h = hooked.register_forward_hook(Box::new(move |_in, _out| {
        c.fetch_add(1, Ordering::Relaxed);
    }));

    let x = Tensor::from_storage(TensorStorage::cpu(vec![1.0f32; 3]), vec![3], false).unwrap();
    hooked.forward(&x).unwrap();
    assert_eq!(count.load(Ordering::Relaxed), 1);
    hooked.forward(&x).unwrap();
    assert_eq!(count.load(Ordering::Relaxed), 2);
}

/// conformance_nn_structural: ferrotorch_nn forward pre-hook can replace input
#[test]
fn hooks_forward_pre_hook_replaces_input() {
    // IdentityScaled passes input through — so if pre-hook zeros the input,
    // output must be all zeros.
    let m = IdentityScaled::<f32>::new(3).unwrap();
    let hooked = HookedModule::new(m);
    let _h = hooked.register_forward_pre_hook(Box::new(|input| {
        ferrotorch_core::zeros::<f32>(input.shape())
    }));

    let x = Tensor::from_storage(TensorStorage::cpu(vec![9.0f32; 3]), vec![3], false).unwrap();
    let out = hooked.forward(&x).unwrap();
    let data = out.data().unwrap();
    assert!(data.iter().all(|&v| v == 0.0), "pre-hook must zero out input");
}

/// conformance_nn_structural: ferrotorch_nn HookHandle::remove stops the hook firing
#[test]
fn hooks_handle_remove_stops_hook() {
    let m = IdentityScaled::<f32>::new(2).unwrap();
    let hooked = HookedModule::new(m);
    let count = Arc::new(AtomicUsize::new(0));
    let c = Arc::clone(&count);
    let handle = hooked.register_forward_hook(Box::new(move |_in, _out| {
        c.fetch_add(1, Ordering::Relaxed);
    }));

    let x = Tensor::from_storage(TensorStorage::cpu(vec![1.0f32; 2]), vec![2], false).unwrap();
    hooked.forward(&x).unwrap();
    assert_eq!(count.load(Ordering::Relaxed), 1);

    handle.remove();

    hooked.forward(&x).unwrap();
    assert_eq!(count.load(Ordering::Relaxed), 1, "hook must not fire after remove");
}

/// conformance_nn_structural: multiple hooks fire in registration order
#[test]
fn hooks_multiple_hooks_fire_in_order() {
    let m = IdentityScaled::<f32>::new(2).unwrap();
    let hooked = HookedModule::new(m);
    let order = Arc::new(Mutex::new(Vec::<usize>::new()));

    for tag in [1usize, 2, 3] {
        let o = Arc::clone(&order);
        hooked.register_forward_hook(Box::new(move |_in, _out| {
            o.lock().unwrap().push(tag);
        }));
    }

    let x = Tensor::from_storage(TensorStorage::cpu(vec![0.0f32; 2]), vec![2], false).unwrap();
    hooked.forward(&x).unwrap();
    assert_eq!(*order.lock().unwrap(), vec![1, 2, 3]);
}

/// conformance_nn_structural: backward hook is registered without breaking forward
#[test]
fn hooks_backward_hook_registered_forward_still_works() {
    let m = IdentityScaled::<f32>::new(2).unwrap();
    let hooked = HookedModule::new(m);
    let _handle = hooked.register_backward_hook(Box::new(|_gi, _go| {}));
    let x = Tensor::from_storage(TensorStorage::cpu(vec![1.0f32; 2]), vec![2], false).unwrap();
    let out = hooked.forward(&x).unwrap();
    assert_eq!(out.data().unwrap(), &[1.0f32, 1.0]);
}

// ---------------------------------------------------------------------------
// Module 7 — rnn.rs: LSTM
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::LSTM output shape matches fixture
#[test]
fn rnn_lstm_single_step_output_shape() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "lstm_single_step_shape");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let x_val = fx["inputs"]["x_value"].as_f64().unwrap() as f32;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let mut lstm = LSTM::<f32>::new(x_shape[2], hidden_size, num_layers).unwrap();
    // Set all parameters to w_val for reproducibility.
    for p in lstm.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![x_val; x_shape.iter().product()]),
        x_shape.clone(),
        false,
    ).unwrap();

    let (output, (h_n, c_n)) = lstm.forward_with_state(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let exp_hn_shape: Vec<usize> = fx["expected"]["h_n_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    assert_eq!(output.shape(), exp_out_shape.as_slice(), "LSTM output shape mismatch");
    assert_eq!(h_n.shape(), exp_hn_shape.as_slice(), "LSTM h_n shape mismatch");

    // Numerical check against fixture.
    let expected_out = json_to_f32_flat(&fx["expected"]["output"]);
    let tol = fx["tolerance"].as_f64().unwrap_or(1e-4) as f32;
    assert_close_f32(output.data().unwrap(), &expected_out, tol, "lstm_single_step_output");
    let expected_hn = json_to_f32_flat(&fx["expected"]["h_n"]);
    assert_close_f32(h_n.data().unwrap(), &expected_hn, tol, "lstm_single_step_h_n");

    let _ = c_n; // shape already checked via h_n symmetry
}

/// conformance_nn_structural: ferrotorch_nn::LSTM multi-step trajectory shape and last h_n
#[test]
fn rnn_lstm_multistep_trajectory() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "lstm_multistep_trajectory");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let x_flat = json_to_f32_flat(&fx["inputs"]["x"]);
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    let input_size = x_shape[2];
    let mut lstm = LSTM::<f32>::new(input_size, hidden_size, num_layers).unwrap();
    for p in lstm.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(TensorStorage::cpu(x_flat), x_shape.clone(), false).unwrap();
    let (output, (h_n, c_n)) = lstm.forward_with_state(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), exp_out_shape.as_slice());

    let tol = fx["tolerance"].as_f64().unwrap_or(1e-4) as f32;
    let expected_hn = json_to_f32_flat(&fx["expected"]["h_n"]);
    assert_close_f32(h_n.data().unwrap(), &expected_hn, tol, "lstm_multistep_h_n");

    let expected_out = json_to_f32_flat(&fx["expected"]["output"]);
    assert_close_f32(output.data().unwrap(), &expected_out, tol, "lstm_multistep_output");

    let _ = c_n;
}

/// conformance_nn_structural: ferrotorch_nn::LSTM parameter count is num_layers * 4
#[test]
fn rnn_lstm_parameter_count() {
    let lstm = LSTM::<f32>::new(3, 4, 2).unwrap();
    let params = lstm.parameters();
    // Each layer has weight_ih, weight_hh, bias_ih, bias_hh = 4 params.
    assert_eq!(params.len(), 8, "2-layer LSTM must have 8 parameters");
}

/// conformance_nn_structural: ferrotorch_nn::LSTM Module::forward delegates to forward_with_state
#[test]
fn rnn_lstm_module_forward_produces_correct_output_shape() {
    let lstm = LSTM::<f32>::new(4, 3, 1).unwrap();
    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![0.1f32; 2 * 5 * 4]),
        vec![2, 5, 4],
        false,
    ).unwrap();
    let out = Module::<f32>::forward(&lstm, &x).unwrap();
    assert_eq!(out.shape(), &[2, 5, 3]);
}

// ---------------------------------------------------------------------------
// Module 7 — rnn.rs: GRU
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::GRU single-step output shape matches fixture
#[test]
fn rnn_gru_single_step_output_shape() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "gru_single_step_shape");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let x_val = fx["inputs"]["x_value"].as_f64().unwrap() as f32;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let mut gru = GRU::<f32>::with_num_layers(x_shape[2], hidden_size, num_layers).unwrap();
    for p in gru.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![x_val; x_shape.iter().product()]),
        x_shape.clone(),
        false,
    ).unwrap();

    let (output, h_n) = gru.forward(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let exp_hn_shape: Vec<usize> = fx["expected"]["h_n_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), exp_out_shape.as_slice());
    assert_eq!(h_n.shape(), exp_hn_shape.as_slice());

    let tol = fx["tolerance"].as_f64().unwrap_or(1e-4) as f32;
    let expected_out = json_to_f32_flat(&fx["expected"]["output"]);
    assert_close_f32(output.data().unwrap(), &expected_out, tol, "gru_single_step_output");
}

/// conformance_nn_structural: ferrotorch_nn::GRU multi-step trajectory
#[test]
fn rnn_gru_multistep_trajectory() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "gru_multistep_trajectory");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let x_flat = json_to_f32_flat(&fx["inputs"]["x"]);
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let input_size = x_shape[2];

    let mut gru = GRU::<f32>::with_num_layers(input_size, hidden_size, num_layers).unwrap();
    for p in gru.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(TensorStorage::cpu(x_flat), x_shape.clone(), false).unwrap();
    let (output, h_n) = gru.forward(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), exp_out_shape.as_slice());

    let tol = fx["tolerance"].as_f64().unwrap_or(1e-4) as f32;
    let expected_hn = json_to_f32_flat(&fx["expected"]["h_n"]);
    assert_close_f32(h_n.data().unwrap(), &expected_hn, tol, "gru_multistep_h_n");
}

/// conformance_nn_structural: ferrotorch_nn::GRU parameter count is num_layers * 4
#[test]
fn rnn_gru_parameter_count() {
    let gru = GRU::<f32>::with_num_layers(3, 4, 2).unwrap();
    let params = gru.parameters();
    assert_eq!(params.len(), 8, "2-layer GRU must have 8 parameters");
}

// ---------------------------------------------------------------------------
// Module 7 — rnn.rs: RNN
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::RNN (tanh) single-step shape matches fixture
#[test]
fn rnn_tanh_single_step_shape_and_values() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "rnn_tanh_single_step");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let x_val = fx["inputs"]["x_value"].as_f64().unwrap() as f32;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let mut rnn = RNN::<f32>::with_options(
        x_shape[2], hidden_size, num_layers, RNNNonlinearity::Tanh,
    ).unwrap();
    for p in rnn.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![x_val; x_shape.iter().product()]),
        x_shape.clone(),
        false,
    ).unwrap();

    let (output, h_n) = rnn.forward_with_state(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let exp_hn_shape: Vec<usize> = fx["expected"]["h_n_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), exp_out_shape.as_slice());
    assert_eq!(h_n.shape(), exp_hn_shape.as_slice());

    let tol = fx["tolerance"].as_f64().unwrap_or(1e-4) as f32;
    let expected_out = json_to_f32_flat(&fx["expected"]["output"]);
    assert_close_f32(output.data().unwrap(), &expected_out, tol, "rnn_tanh_single_step");
}

/// conformance_nn_structural: ferrotorch_nn::RNN multi-step trajectory
#[test]
fn rnn_tanh_multistep_trajectory() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "rnn_tanh_multistep");
    let hidden_size = fx["inputs"]["hidden_size"].as_u64().unwrap() as usize;
    let num_layers = fx["inputs"]["num_layers"].as_u64().unwrap() as usize;
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;

    let x_flat = json_to_f32_flat(&fx["inputs"]["x"]);
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let input_size = x_shape[2];

    let mut rnn = RNN::<f32>::with_options(
        input_size, hidden_size, num_layers, RNNNonlinearity::Tanh,
    ).unwrap();
    for p in rnn.parameters_mut() {
        let shape = p.shape().to_vec();
        let n = p.numel();
        *p = Parameter::from_slice(&vec![w_val; n], &shape).unwrap();
    }

    let x = Tensor::from_storage(TensorStorage::cpu(x_flat), x_shape.clone(), false).unwrap();
    let (output, h_n) = rnn.forward_with_state(&x, None).unwrap();

    let exp_out_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), exp_out_shape.as_slice());

    let tol = fx["tolerance"].as_f64().unwrap_or(1e-3) as f32;
    let expected_hn = json_to_f32_flat(&fx["expected"]["h_n"]);
    assert_close_f32(h_n.data().unwrap(), &expected_hn, tol, "rnn_tanh_multistep_h_n");
}

/// conformance_nn_structural: ferrotorch_nn::RNN parameter count is num_layers * 4
#[test]
fn rnn_parameter_count() {
    let rnn = RNN::<f32>::new(3, 4).unwrap();
    let params = rnn.parameters();
    // weight_ih, weight_hh, bias_ih, bias_hh = 4 params.
    assert_eq!(params.len(), 4, "single-layer RNN must have 4 parameters");
}

// ---------------------------------------------------------------------------
// Module 8 — rnn_utils.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: pack_padded_sequence produces correct batch_sizes
#[test]
fn rnn_utils_pack_padded_batch_sizes() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "pack_padded_sequence_batch_sizes");
    let batch = fx["inputs"]["batch"].as_u64().unwrap() as usize;
    let max_seq = fx["inputs"]["max_seq_len"].as_u64().unwrap() as usize;
    let features = fx["inputs"]["features"].as_u64().unwrap() as usize;
    let lengths: Vec<usize> = fx["inputs"]["lengths"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    let data: Vec<f32> = (0..(batch * max_seq * features)).map(|i| i as f32).collect();
    let input = Tensor::from_storage(
        TensorStorage::cpu(data),
        vec![batch, max_seq, features],
        false,
    ).unwrap();

    let packed = pack_padded_sequence(&input, &lengths, true, true).unwrap();

    let expected_bs: Vec<usize> = fx["expected"]["batch_sizes"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(packed.batch_sizes, expected_bs);
}

/// conformance_nn_structural: pack_padded_sequence produces correct packed data order
#[test]
fn rnn_utils_pack_padded_data_order() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "pack_padded_sequence_packed_order");

    // Build input: 2 seqs, lengths [3,2], features=1
    // seq0=[10,20,30], seq1=[40,50,0]
    let data = vec![10.0f32, 20.0, 30.0, 40.0, 50.0, 0.0];
    let input = Tensor::from_storage(TensorStorage::cpu(data), vec![2, 3, 1], false).unwrap();
    let lengths = [3usize, 2];

    let packed = pack_padded_sequence(&input, &lengths, true, true).unwrap();

    let expected_bs: Vec<usize> = fx["expected"]["batch_sizes"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(packed.batch_sizes, expected_bs);

    let expected_packed: Vec<f32> = fx["expected"]["packed_data"].as_array().unwrap()
        .iter().map(|v| v.as_f64().unwrap() as f32).collect();
    assert_close_f32(packed.data.data().unwrap(), &expected_packed, 1e-7, "pack_padded_data_order");
}

/// conformance_nn_structural: pad_packed_sequence round-trips pack with correct shapes
#[test]
fn rnn_utils_pad_packed_sequence_roundtrip() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "pad_packed_sequence_roundtrip");
    let batch = fx["inputs"]["batch"].as_u64().unwrap() as usize;
    let max_seq = fx["inputs"]["max_seq_len"].as_u64().unwrap() as usize;
    let features = fx["inputs"]["features"].as_u64().unwrap() as usize;
    let lengths: Vec<usize> = fx["inputs"]["lengths"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    // Build a test input with value = (b*1000 + t*10 + f) so positions are identifiable.
    let mut data = Vec::with_capacity(batch * max_seq * features);
    for b in 0..batch {
        for t in 0..max_seq {
            for f in 0..features {
                data.push((b * 1000 + t * 10 + f) as f32);
            }
        }
    }
    let input = Tensor::from_storage(TensorStorage::cpu(data.clone()), vec![batch, max_seq, features], false).unwrap();

    let packed = pack_padded_sequence(&input, &lengths, true, true).unwrap();
    let (output, out_lengths) = pad_packed_sequence(&packed, true, 0.0f32).unwrap();

    let expected_out_lengths: Vec<usize> = fx["expected"]["output_lengths"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(out_lengths, expected_out_lengths);

    let expected_shape: Vec<usize> = fx["expected"]["output_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(output.shape(), expected_shape.as_slice());

    // Non-padding positions must match original.
    let out_data = output.data().unwrap();
    for b in 0..batch {
        for t in 0..max_seq {
            for f in 0..features {
                let idx = b * max_seq * features + t * features + f;
                if t < lengths[b] {
                    assert_eq!(out_data[idx], data[idx], "roundtrip mismatch at b={b} t={t} f={f}");
                } else {
                    assert_eq!(out_data[idx], 0.0f32, "padding must be 0.0 at b={b} t={t} f={f}");
                }
            }
        }
    }
}

/// conformance_nn_structural: pack_padded_sequence with unsorted lengths
#[test]
fn rnn_utils_pack_padded_unsorted() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "pack_padded_sequence_unsorted");
    let batch = fx["inputs"]["batch"].as_u64().unwrap() as usize;
    let max_seq = fx["inputs"]["max_seq_len"].as_u64().unwrap() as usize;
    let features = fx["inputs"]["features"].as_u64().unwrap() as usize;
    let lengths: Vec<usize> = fx["inputs"]["lengths"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    let data: Vec<f32> = (0..(batch * max_seq * features)).map(|i| i as f32).collect();
    let input = Tensor::from_storage(
        TensorStorage::cpu(data), vec![batch, max_seq, features], false,
    ).unwrap();

    let packed = pack_padded_sequence(&input, &lengths, true, false).unwrap();

    let expected_bs: Vec<usize> = fx["expected"]["batch_sizes"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let expected_si: Vec<usize> = fx["expected"]["sorted_indices"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    assert_eq!(packed.batch_sizes, expected_bs);
    assert_eq!(packed.sorted_indices, expected_si);
}

/// conformance_nn_structural: pack_padded_sequence enforce_sorted=true rejects unsorted input
#[test]
fn rnn_utils_enforce_sorted_rejects_unsorted() {
    let data: Vec<f32> = (0..30).map(|i| i as f32).collect();
    let input = Tensor::from_storage(TensorStorage::cpu(data), vec![3, 5, 2], false).unwrap();
    let result = pack_padded_sequence(&input, &[2usize, 5, 3], true, true);
    assert!(result.is_err(), "enforce_sorted=true must reject unsorted lengths");
}

// ---------------------------------------------------------------------------
// Module 9 — lora.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::LoRALinear forward with zero B matches base
#[test]
fn lora_zero_b_forward_matches_base_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "lora_zero_b_matches_base");
    let in_f = fx["inputs"]["in_features"].as_u64().unwrap() as usize;
    let out_f = fx["inputs"]["out_features"].as_u64().unwrap() as usize;
    let rank = fx["inputs"]["rank"].as_u64().unwrap() as usize;
    let alpha = fx["inputs"]["alpha"].as_f64().unwrap();
    let w_val = fx["inputs"]["weight_value"].as_f64().unwrap() as f32;
    let b_val = fx["inputs"]["bias_value"].as_f64().unwrap() as f32;

    let mut base = Linear::<f32>::new(in_f, out_f, true).unwrap();
    base.weight = Parameter::from_slice(&vec![w_val; out_f * in_f], &[out_f, in_f]).unwrap();
    *base.bias.as_mut().unwrap() = Parameter::from_slice(&vec![b_val; out_f], &[out_f]).unwrap();

    // lora_b is zero-initialized in LoRALinear::new — contribution should be zero.
    let lora = LoRALinear::new(base, rank, alpha, 0.0).unwrap();

    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let x = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0f32; x_shape.iter().product()]),
        x_shape,
        false,
    ).unwrap();

    let output = lora.forward(&x).unwrap();

    let expected = json_to_f32_flat(&fx["expected"]["output"]);
    let tol = 1e-5f32;
    assert_close_f32(output.data().unwrap(), &expected, tol, "lora_zero_b_matches_base");
}

/// conformance_nn_structural: ferrotorch_nn::LoRALinear forward with known A, B
#[test]
fn lora_forward_known_weights_matches_fixture() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "lora_forward_known_weights");
    let in_f = fx["inputs"]["in_features"].as_u64().unwrap() as usize;
    let out_f = fx["inputs"]["out_features"].as_u64().unwrap() as usize;
    let rank = fx["inputs"]["rank"].as_u64().unwrap() as usize;
    let alpha = fx["inputs"]["alpha"].as_f64().unwrap();

    let base_weight = json_to_f32_flat(&fx["inputs"]["base_weight"]);
    let base_bias = json_to_f32_flat(&fx["inputs"]["base_bias"]);
    let lora_a_data = json_to_f32_flat(&fx["inputs"]["lora_a"]);
    let lora_b_data = json_to_f32_flat(&fx["inputs"]["lora_b"]);

    let mut base = Linear::<f32>::new(in_f, out_f, true).unwrap();
    base.weight = Parameter::from_slice(&base_weight, &[out_f, in_f]).unwrap();
    *base.bias.as_mut().unwrap() = Parameter::from_slice(&base_bias, &[out_f]).unwrap();

    let mut lora = LoRALinear::new(base, rank, alpha, 0.0).unwrap();
    // lora_a and lora_b are private; use load_state_dict to inject known values.
    let mut sd = lora.state_dict();
    sd.insert("lora_a".into(), Tensor::from_storage(
        TensorStorage::cpu(lora_a_data), vec![rank, in_f], false,
    ).unwrap());
    sd.insert("lora_b".into(), Tensor::from_storage(
        TensorStorage::cpu(lora_b_data), vec![out_f, rank], false,
    ).unwrap());
    lora.load_state_dict(&sd, true).unwrap();

    let x_flat = json_to_f32_flat(&fx["inputs"]["x"]);
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();
    let x = Tensor::from_storage(TensorStorage::cpu(x_flat), x_shape, false).unwrap();

    let output = lora.forward(&x).unwrap();

    let expected = json_to_f32_flat(&fx["expected"]["output"]);
    let tol = 1e-5f32;
    assert_close_f32(output.data().unwrap(), &expected, tol, "lora_forward_known_weights");
}

/// conformance_nn_structural: ferrotorch_nn::LoRALinear merge produces same output as pre-merge forward
#[test]
fn lora_merge_produces_same_output() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "lora_merge_produces_same_output");
    let in_f = fx["inputs"]["in_features"].as_u64().unwrap() as usize;
    let out_f = fx["inputs"]["out_features"].as_u64().unwrap() as usize;
    let rank = fx["inputs"]["rank"].as_u64().unwrap() as usize;
    let alpha = fx["inputs"]["alpha"].as_f64().unwrap();

    let base_weight = json_to_f32_flat(&fx["inputs"]["base_weight"]);
    let base_bias = json_to_f32_flat(&fx["inputs"]["base_bias"]);
    let lora_a_data = json_to_f32_flat(&fx["inputs"]["lora_a"]);
    let lora_b_data = json_to_f32_flat(&fx["inputs"]["lora_b"]);

    let x_flat = json_to_f32_flat(&fx["inputs"]["x"]);
    let x_shape: Vec<usize> = fx["inputs"]["x_shape"].as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize).collect();

    let mut base = Linear::<f32>::new(in_f, out_f, true).unwrap();
    base.weight = Parameter::from_slice(&base_weight, &[out_f, in_f]).unwrap();
    *base.bias.as_mut().unwrap() = Parameter::from_slice(&base_bias, &[out_f]).unwrap();

    let mut lora = LoRALinear::new(base, rank, alpha, 0.0).unwrap();
    // lora_a and lora_b are private; use load_state_dict to inject known values.
    let mut sd = lora.state_dict();
    sd.insert("lora_a".into(), Tensor::from_storage(
        TensorStorage::cpu(lora_a_data), vec![rank, in_f], false,
    ).unwrap());
    sd.insert("lora_b".into(), Tensor::from_storage(
        TensorStorage::cpu(lora_b_data), vec![out_f, rank], false,
    ).unwrap());
    lora.load_state_dict(&sd, true).unwrap();

    let x = Tensor::from_storage(TensorStorage::cpu(x_flat.clone()), x_shape.clone(), false).unwrap();
    let pre_merge = lora.forward(&x).unwrap();
    let pre_data = pre_merge.data().unwrap().to_vec();

    lora.merge().unwrap();

    let x2 = Tensor::from_storage(TensorStorage::cpu(x_flat), x_shape, false).unwrap();
    let post_merge = lora.base().forward(&x2).unwrap();

    assert_close_f32(post_merge.data().unwrap(), &pre_data, 1e-5, "lora_merge");
}

/// conformance_nn_structural: ferrotorch_nn::LoRALinear only exposes lora_a and lora_b params
#[test]
fn lora_parameters_only_lora_a_and_b() {
    let base = Linear::<f32>::new(8, 4, true).unwrap();
    let lora = LoRALinear::new(base, 2, 1.0, 0.0).unwrap();
    let params = lora.parameters();
    // Only lora_a [2,8] and lora_b [4,2] — NOT base weight/bias.
    assert_eq!(params.len(), 2);
    let named = lora.named_parameters();
    let keys: Vec<&str> = named.iter().map(|(k, _)| k.as_str()).collect();
    assert_eq!(keys, &["lora_a", "lora_b"]);
}

/// conformance_nn_structural: ferrotorch_nn::LoRALinear state_dict excludes base weight
#[test]
fn lora_state_dict_excludes_base_weight() {
    let base = Linear::<f32>::new(8, 4, true).unwrap();
    let lora = LoRALinear::new(base, 2, 1.0, 0.0).unwrap();
    let sd = lora.state_dict();
    assert!(sd.contains_key("lora_a"));
    assert!(sd.contains_key("lora_b"));
    assert!(!sd.contains_key("weight"), "base weight must NOT be in state_dict");
    assert!(!sd.contains_key("bias"), "base bias must NOT be in state_dict");
}

// ---------------------------------------------------------------------------
// Module 10 — qat.rs
// ---------------------------------------------------------------------------

/// conformance_nn_structural: ferrotorch_nn::QatConfig::default_symmetric_int8 fields
#[test]
fn qat_config_default_symmetric_int8_fields() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "qat_config_int8_symmetric");
    let c = QatConfig::default_symmetric_int8();

    let expected_wd = fx["expected"]["weight_dtype"].as_str().unwrap();
    let expected_ad = fx["expected"]["activation_dtype"].as_str().unwrap();
    assert_eq!(format!("{:?}", c.weight_dtype), expected_wd);
    assert_eq!(format!("{:?}", c.activation_dtype), expected_ad);
    assert_eq!(c.weight_symmetric, fx["expected"]["weight_symmetric"].as_bool().unwrap());
    assert_eq!(c.activation_symmetric, fx["expected"]["activation_symmetric"].as_bool().unwrap());
}

/// conformance_nn_structural: ferrotorch_nn::QatConfig::per_channel_int8 observer type
#[test]
fn qat_config_per_channel_int8_observer_type() {
    let c = QatConfig::per_channel_int8();
    assert_eq!(c.weight_observer, ObserverType::PerChannelMinMax);
    assert_eq!(c.activation_observer, ObserverType::MovingAverageMinMax);
}

/// conformance_nn_structural: ferrotorch_nn::QatConfig::int4_weight_int8_activation dtype fields
#[test]
fn qat_config_int4_int8_dtype_fields() {
    use ferrotorch_core::QuantDtype;
    let c = QatConfig::int4_weight_int8_activation();
    assert_eq!(c.weight_dtype, QuantDtype::Int4);
    assert_eq!(c.activation_dtype, QuantDtype::Int8);
}

/// conformance_nn_structural: ferrotorch_nn::prepare_qat registers weight layers not bias
#[test]
fn qat_prepare_qat_registers_weight_layers() {
    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "prepare_qat_registers_weight_layers");
    let param_names: Vec<&str> = fx["param_names"].as_array().unwrap()
        .iter().map(|v| v.as_str().unwrap()).collect();

    // Build a minimal module that advertises these named parameters.
    struct FakeModule {
        p0w: Parameter<f32>,
        p0b: Parameter<f32>,
        p1w: Parameter<f32>,
        training: bool,
    }
    impl Module<f32> for FakeModule {
        fn forward(&self, input: &Tensor<f32>) -> FerrotorchResult<Tensor<f32>> { Ok(input.clone()) }
        fn parameters(&self) -> Vec<&Parameter<f32>> { vec![&self.p0w, &self.p0b, &self.p1w] }
        fn parameters_mut(&mut self) -> Vec<&mut Parameter<f32>> {
            vec![&mut self.p0w, &mut self.p0b, &mut self.p1w]
        }
        fn named_parameters(&self) -> Vec<(String, &Parameter<f32>)> {
            vec![
                ("0.weight".into(), &self.p0w),
                ("0.bias".into(), &self.p0b),
                ("1.weight".into(), &self.p1w),
            ]
        }
        fn train(&mut self) { self.training = true; }
        fn eval(&mut self) { self.training = false; }
        fn is_training(&self) -> bool { self.training }
    }

    let m = FakeModule {
        p0w: Parameter::zeros(&[4]).unwrap(),
        p0b: Parameter::zeros(&[4]).unwrap(),
        p1w: Parameter::zeros(&[4]).unwrap(),
        training: true,
    };

    let _ = param_names; // fixture validates the param names but we test the function directly
    let qat_model = prepare_qat(&m, QatConfig::default_symmetric_int8());

    let expected_count = fx["expected"]["layer_count"].as_u64().unwrap() as usize;
    assert_eq!(qat_model.layers.len(), expected_count,
        "prepare_qat must register exactly {} layers", expected_count);

    let expected_layer_names: Vec<&str> = fx["expected"]["layer_names"].as_array().unwrap()
        .iter().map(|v| v.as_str().unwrap()).collect();
    for name in expected_layer_names {
        assert!(qat_model.layers.contains_key(name),
            "QatModel must have layer '{name}'");
    }
}

/// conformance_nn_structural: ferrotorch_nn::QatModel fake_quantize_weights INT8 parity
#[test]
fn qat_fake_quantize_int8_parity() {
    use ferrotorch_core::quantize::FakeQuantize;
    use ferrotorch_core::QuantDtype;

    let fixtures = fixtures_json();
    let fx = fixture_by_id(&fixtures, "fake_quantize_int8_parity");
    let values: Vec<f32> = fx["inputs"]["values"].as_array().unwrap()
        .iter().map(|v| v.as_f64().unwrap() as f32).collect();
    let max_abs_error = fx["expected"]["max_abs_error"].as_f64().unwrap() as f32;

    let mut fq = FakeQuantize::new(QuantDtype::Int8);
    let (fq_vals, _mask) = fq.forward(&values);

    for (i, (&orig, &fq)) in values.iter().zip(fq_vals.iter()).enumerate() {
        let err = (orig - fq).abs();
        assert!(
            err <= max_abs_error,
            "fake_quantize[{i}]: orig={orig:.6} fq={fq:.6} err={err:.6} > max={max_abs_error:.6}"
        );
    }
}

/// conformance_nn_structural: ferrotorch_nn::QatConfig clone and partial-eq on ObserverType
#[test]
fn qat_observer_type_variants_are_distinct() {
    // ObserverType derives PartialEq — verify the four variants are distinct.
    assert_eq!(ObserverType::MinMax, ObserverType::MinMax);
    assert_ne!(ObserverType::MinMax, ObserverType::MovingAverageMinMax);
    assert_ne!(ObserverType::Histogram, ObserverType::PerChannelMinMax);
    assert_ne!(ObserverType::MovingAverageMinMax, ObserverType::Histogram);
}
