//! Probe-before-fix for Phase 5: groups + dilation on Conv2d::new_full.
//!
//! This test asserts that `Conv2d::new_full(in, out, kernel, stride, padding,
//! dilation, groups, bias)` exists and that the CPU forward correctly handles
//! a combined (groups=2, dilation=(2,2)) configuration on a small synthetic
//! input, elementwise-matching a hand-computed reference.
//!
//! Hand-computed reference values are derived in the inline comments below;
//! they are NOT generated by the implementation under test (see failure mode
//! #12 — Tautological reference).
//!
//! When the API does not yet exist (compile failure) or when the forward
//! ignores groups/dilation (wrong output values), this test fails. Once
//! the implementation lands and the GPU-dispatch gate is correct, it passes.

use ferrotorch_core::storage::TensorStorage;
use ferrotorch_core::tensor::Tensor;
use ferrotorch_nn::Conv2d;
use ferrotorch_nn::module::Module;
use ferrotorch_nn::parameter::Parameter;

/// Build a CPU tensor `[B, C, H, W]` from a flat slice.
fn t(data: &[f32], shape: &[usize]) -> Tensor<f32> {
    Tensor::from_storage(TensorStorage::cpu(data.to_vec()), shape.to_vec(), false).unwrap()
}

#[test]
fn probe_groups2_dilation2_combined_forward() {
    // Configuration:
    //   in_channels  = 2  (one input channel per group)
    //   out_channels = 2  (one output channel per group)
    //   groups       = 2  (each output filter sees only its own input channel)
    //   kernel       = (2, 2)
    //   stride       = (1, 1)
    //   padding      = (0, 0)
    //   dilation     = (2, 2)
    //
    // Input H = W = 4, so the dilated kernel (2x2 with dilation=2) effectively
    // covers a 3x3 region per filter.
    //   H_out = (H + 2*pad - dil*(k-1) - 1) / stride + 1
    //         = (4 + 0   - 2*(2-1)   - 1) / 1      + 1 = 2
    //   W_out = 2
    //
    // Input layout: [B=1, C=2, H=4, W=4] = 32 values total.
    // Channel 0 (c=0) — values 0..16 reshaped row-major:
    //    0  1  2  3
    //    4  5  6  7
    //    8  9 10 11
    //   12 13 14 15
    // Channel 1 (c=1) — values 100..115 reshaped:
    //  100 101 102 103
    //  104 105 106 107
    //  108 109 110 111
    //  112 113 114 115
    let mut input = Vec::with_capacity(2 * 4 * 4);
    for v in 0..16 {
        input.push(v as f32);
    }
    for v in 0..16 {
        input.push(100.0 + v as f32);
    }

    // Weight layout: [C_out=2, C_in_per_group=1, kH=2, kW=2] (since groups=2,
    // each filter sees only `in_channels / groups = 1` input channel).
    // Filter 0 (out_ch=0, group=0, looks at input channel 0):
    //   [[1, 2],
    //    [3, 4]]
    // Filter 1 (out_ch=1, group=1, looks at input channel 1):
    //   [[10, 20],
    //    [30, 40]]
    let weight: Vec<f32> = vec![
        1.0, 2.0, 3.0, 4.0, // filter 0
        10.0, 20.0, 30.0, 40.0, // filter 1
    ];

    let conv = Conv2d::<f32>::new_full(
        2,      // in_channels
        2,      // out_channels
        (2, 2), // kernel_size
        (1, 1), // stride
        (0, 0), // padding
        (2, 2), // dilation
        2,      // groups
        false,  // bias
    )
    .expect("Conv2d::new_full must exist and accept these params");

    // Replace the random Kaiming weight with our deterministic one.
    let mut conv = conv;
    let weight_param = Parameter::from_slice(&weight, &[2, 1, 2, 2]).unwrap();
    conv.set_weight(weight_param)
        .expect("must be able to set weight after new_full");

    let x = t(&input, &[1, 2, 4, 4]);
    let out = conv.forward(&x).expect("forward must succeed");

    assert_eq!(
        out.shape(),
        &[1, 2, 2, 2],
        "output spatial shape must be 2x2 for dilation=2 kernel=2 over 4x4"
    );

    // Hand-computed reference values (NOT generated by the impl under test):
    //
    // Output channel 0 (filter 0, looks at channel 0 only):
    //   For each output position (oh, ow), the effective kernel taps the
    //   input at positions:
    //     (oh + 0*2, ow + 0*2)  weight 1
    //     (oh + 0*2, ow + 1*2)  weight 2
    //     (oh + 1*2, ow + 0*2)  weight 3
    //     (oh + 1*2, ow + 1*2)  weight 4
    //
    //   (oh=0, ow=0): in[0,0,0]*1 + in[0,0,2]*2 + in[0,2,0]*3 + in[0,2,2]*4
    //               = 0*1 + 2*2 + 8*3 + 10*4 = 0 + 4 + 24 + 40 = 68
    //   (oh=0, ow=1): in[0,0,1]*1 + in[0,0,3]*2 + in[0,2,1]*3 + in[0,2,3]*4
    //               = 1 + 6 + 27 + 44 = 78
    //   (oh=1, ow=0): in[0,1,0]*1 + in[0,1,2]*2 + in[0,3,0]*3 + in[0,3,2]*4
    //               = 4 + 12 + 36 + 56 = 108
    //   (oh=1, ow=1): in[0,1,1]*1 + in[0,1,3]*2 + in[0,3,1]*3 + in[0,3,3]*4
    //               = 5 + 14 + 39 + 60 = 118
    //
    // Output channel 1 (filter 1, looks at channel 1 only):
    //   weights are 10x channel-0's pattern, applied to (100+v) inputs.
    //   (oh=0, ow=0): 100*10 + 102*20 + 108*30 + 110*40
    //               = 1000 + 2040 + 3240 + 4400 = 10680
    //   (oh=0, ow=1): 101*10 + 103*20 + 109*30 + 111*40
    //               = 1010 + 2060 + 3270 + 4440 = 10780
    //   (oh=1, ow=0): 104*10 + 106*20 + 112*30 + 114*40
    //               = 1040 + 2120 + 3360 + 4560 = 11080
    //   (oh=1, ow=1): 105*10 + 107*20 + 113*30 + 115*40
    //               = 1050 + 2140 + 3390 + 4600 = 11180
    let expected: [f32; 8] = [
        68.0, 78.0, 108.0, 118.0, // out_ch 0
        10680.0, 10780.0, 11080.0, 11180.0, // out_ch 1
    ];
    let got = out.data().unwrap();
    for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
        let diff = (g - e).abs();
        assert!(
            diff < 1e-3,
            "mismatch at flat index {i}: got={g} expected={e} diff={diff}"
        );
    }
}
