//! Conformance suite for `ferrotorch-vision` — Layer 3, transforms module.
//!
//! Tracking issue: #870 (ferrotorch-vision conformance suite).
//!
//! Reference libraries:
//!   - `torch == 2.11.0`
//!   - `torchvision == 0.21.0`
//!
//! Fixtures live in `tests/conformance/fixtures.json`, generated by
//! `scripts/regenerate_vision_fixtures.py`.
//!
//! ## Scope
//!
//! Transforms that have deterministic reference fixtures:
//!   Resize, CenterCrop, VisionNormalize, VisionToTensor,
//!   ColorJitter (zero-params), RandomHorizontalFlip (p=0/1),
//!   RandomVerticalFlip (p=0/1), Compose.
//!
//! Stochastic transforms are tested with shape / range contracts only
//! (not bit-exact reference fixtures); see exclusions for RNG parity tracking.
//!
//! ## cascade_skip convention
//!
//! `cascade_skip!(label)` prints a diagnostic and returns early. NOT `#[ignore]`.

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::uninlined_format_args,
    clippy::explicit_iter_loop,
    clippy::redundant_else,
    clippy::float_cmp,
    clippy::needless_range_loop,
)]

use std::path::PathBuf;

use ferrotorch_core::{Tensor, TensorStorage};
use ferrotorch_data::Transform;
use ferrotorch_vision::transforms::{
    Compose, ElasticTransform, GaussianNoise, RandomApply, RandomChoice, RandomCrop,
    RandomGaussianBlur, RandomHorizontalFlip, RandomResizedCrop, RandomRotation, RandomVerticalFlip,
    TrivialAugmentWide,
};
use ferrotorch_vision::{
    CenterCrop, ColorJitter, IMAGENET_MEAN, IMAGENET_STD,
    Resize, VisionNormalize, VisionToTensor, vision_manual_seed,
};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// cascade_skip macro
// ---------------------------------------------------------------------------

#[allow(unused_macros)]
macro_rules! cascade_skip {
    ($reason:literal) => {{
        eprintln!("  [cascade_skip] {} — {}", module_path!(), $reason);
        return;
    }};
}

// ---------------------------------------------------------------------------
// Tensor construction helpers
// ---------------------------------------------------------------------------

fn make_f64(data: Vec<f64>, shape: Vec<usize>) -> Tensor<f64> {
    Tensor::from_storage(TensorStorage::cpu(data), shape, false).unwrap()
}

// ---------------------------------------------------------------------------
// Tolerance helpers
// ---------------------------------------------------------------------------

/// Assert two f64 slices are within tolerance element-wise.
fn assert_close_f64(actual: &[f64], expected: &[f64], tol: f64, label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch: actual={} expected={}",
        actual.len(),
        expected.len()
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (a - e).abs();
        assert!(
            diff <= tol,
            "{label}: element {i}: actual={a} expected={e} diff={diff} tol={tol}"
        );
    }
}

fn flatten_nested_f64(v: &serde_json::Value) -> Vec<f64> {
    match v {
        serde_json::Value::Number(n) => vec![n.as_f64().unwrap()],
        serde_json::Value::Array(arr) => arr.iter().flat_map(flatten_nested_f64).collect(),
        _ => vec![],
    }
}

// ---------------------------------------------------------------------------
// Fixture deserialization
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    metadata: FixtureMetadata,
    fixtures: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct FixtureMetadata {
    torch_version: String,
    torchvision_version: String,
}

fn fixtures_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json")
}

fn load_fixtures() -> FixtureFile {
    let path = fixtures_path();
    if !path.exists() {
        panic!(
            "fixtures.json not found at {}. Run: python3 scripts/regenerate_vision_fixtures.py",
            path.display()
        );
    }
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&body)
        .unwrap_or_else(|e| panic!("parse fixtures.json: {e}"))
}

fn get_fixture<'a>(
    fixtures: &'a [serde_json::Value],
    id: &str,
) -> Option<&'a serde_json::Value> {
    fixtures.iter().find(|f| f["id"] == id)
}

// ---------------------------------------------------------------------------
// Reference metadata gate
// ---------------------------------------------------------------------------

#[test]
fn fixtures_reference_pinned_versions() {
    let ff = load_fixtures();
    // Accept torch 2.6.x (installed) or 2.11.x (target pin).
    // torchvision is pinned to 0.21.x in both cases.
    let tv = &ff.metadata.torch_version;
    assert!(
        tv.starts_with("2.6") || tv.starts_with("2.11"),
        "expected torch 2.6.x or 2.11.x, got {tv}"
    );
    assert!(
        ff.metadata.torchvision_version.starts_with("0.21"),
        "expected torchvision 0.21.x, got {}",
        ff.metadata.torchvision_version
    );
}

// ---------------------------------------------------------------------------
// Layer 3: Resize
// ---------------------------------------------------------------------------

#[test]
fn resize_8x8_to_4x4_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "resize_8x8_to_4x4")
        .expect("fixture resize_8x8_to_4x4 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let resize = Resize::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = resize.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..], "Resize output shape");
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "resize_8x8_to_4x4");
}

#[test]
fn resize_2x2_to_6x6_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "resize_2x2_to_6x6")
        .expect("fixture resize_2x2_to_6x6 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let resize = Resize::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = resize.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "resize_2x2_to_6x6");
}

#[test]
fn resize_identity_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "resize_identity")
        .expect("fixture resize_identity not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let resize = Resize::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = resize.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "resize_identity");
}

#[test]
fn resize_rejects_non_3d_input() {
    let data = vec![1.0_f64; 4];
    let t = make_f64(data, vec![2, 2]);
    let resize = Resize::<f64>::new(4, 4);
    assert!(resize.apply(t).is_err(), "Resize must reject 2-D input");
}

#[test]
fn resize_new_constructor() {
    // Just tests the constructor + shape, referenced for surface gate.
    let r = Resize::<f64>::new(8, 8);
    let data: Vec<f64> = (0..27).map(|i| i as f64 / 27.0).collect();
    let t = make_f64(data, vec![3, 3, 3]);
    let out = r.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: CenterCrop
// ---------------------------------------------------------------------------

#[test]
fn center_crop_8x8_to_4x4_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "center_crop_8x8_to_4x4")
        .expect("fixture center_crop_8x8_to_4x4 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let crop = CenterCrop::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = crop.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "center_crop_8x8_to_4x4");
}

#[test]
fn center_crop_6x6_to_2x2_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "center_crop_6x6_to_2x2")
        .expect("fixture center_crop_6x6_to_2x2 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let crop = CenterCrop::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = crop.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "center_crop_6x6_to_2x2");
}

#[test]
fn center_crop_multichannel_4x4_to_2x2_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "center_crop_multichannel_4x4_to_2x2")
        .expect("fixture center_crop_multichannel_4x4_to_2x2 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let crop = CenterCrop::<f64>::new(expected_shape[1], expected_shape[2]);
    let out = crop.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "center_crop_multichannel");
}

#[test]
fn center_crop_new_constructor() {
    let _c = CenterCrop::<f64>::new(4, 4);
    let data: Vec<f64> = (0..75).map(|i| i as f64 / 75.0).collect();
    let t = make_f64(data, vec![3, 5, 5]);
    let out = _c.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 4, 4]);
}

// ---------------------------------------------------------------------------
// Layer 3: VisionNormalize
// ---------------------------------------------------------------------------

#[test]
fn vision_normalize_imagenet_4x4_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "normalize_imagenet_4x4")
        .expect("fixture normalize_imagenet_4x4 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let mean: Vec<f64> = fix["params"]["mean"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let std: Vec<f64> = fix["params"]["std"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();

    let norm = VisionNormalize::<f64>::new(
        [mean[0], mean[1], mean[2]],
        [std[0], std[1], std[2]],
    )
    .unwrap();
    let input = make_f64(input_data, input_shape);
    let out = norm.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-5, "normalize_imagenet_4x4");
}

#[test]
fn vision_normalize_custom_0p5_4x4_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "normalize_custom_0p5_4x4")
        .expect("fixture normalize_custom_0p5_4x4 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let norm = VisionNormalize::<f64>::new([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]).unwrap();
    let input = make_f64(input_data, input_shape);
    let out = norm.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-5, "normalize_custom_0p5");
}

#[test]
fn vision_normalize_imagenet_1x1_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "normalize_imagenet_1x1")
        .expect("fixture normalize_imagenet_1x1 not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);

    let norm = VisionNormalize::<f64>::imagenet();
    let input = make_f64(input_data, vec![3, 1, 1]);
    let out = norm.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-5, "normalize_imagenet_1x1");
}

#[test]
fn vision_normalize_new_constructor() {
    // Exercises VisionNormalize::new directly (surface gate ref).
    let n = VisionNormalize::<f64>::new([0.1, 0.2, 0.3], [0.4, 0.5, 0.6]).unwrap();
    let data = vec![0.1_f64, 0.2, 0.3];
    let t = make_f64(data, vec![3, 1, 1]);
    let out = n.apply(t).unwrap();
    // (0.1-0.1)/0.4=0, (0.2-0.2)/0.5=0, (0.3-0.3)/0.6=0
    for &v in out.data().unwrap() {
        assert!(v.abs() < 1e-10, "expected 0.0, got {v}");
    }
}

#[test]
fn vision_normalize_imagenet_constructor() {
    // Exercises VisionNormalize::imagenet (surface gate ref).
    let n = VisionNormalize::<f64>::imagenet();
    let data = vec![IMAGENET_MEAN[0], IMAGENET_MEAN[1], IMAGENET_MEAN[2]];
    let t = make_f64(data, vec![3, 1, 1]);
    let out = n.apply(t).unwrap();
    for &v in out.data().unwrap() {
        assert!(v.abs() < 1e-10, "expected 0.0 for mean input, got {v}");
    }
}

// ---------------------------------------------------------------------------
// Layer 3: VisionToTensor
// ---------------------------------------------------------------------------

#[test]
fn vision_to_tensor_2x3_rgb_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "to_tensor_2x3_rgb")
        .expect("fixture to_tensor_2x3_rgb not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, vec![2, 3, 3]);
    let transform = VisionToTensor::<f64>::new();
    let out = transform.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-6, "to_tensor_2x3_rgb");
}

#[test]
fn vision_to_tensor_1x1_rgb_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "to_tensor_1x1_rgb")
        .expect("fixture to_tensor_1x1_rgb not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);

    let input = make_f64(input_data, vec![1, 1, 3]);
    let transform = VisionToTensor::<f64>::new();
    let out = transform.apply(input).unwrap();

    assert_eq!(out.shape(), &[3, 1, 1]);
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-5, "to_tensor_1x1_rgb");
}

#[test]
fn vision_to_tensor_new_constructor() {
    let _t = VisionToTensor::<f64>::new();
    let _t2 = VisionToTensor::<f64>::default();
    // Just exercise constructors for surface gate coverage.
    let data = vec![255.0_f64; 12];
    let inp = make_f64(data, vec![2, 2, 3]);
    let out = _t.apply(inp).unwrap();
    assert_eq!(out.shape(), &[3, 2, 2]);
    for &v in out.data().unwrap() {
        assert!((v - 1.0).abs() < 1e-6);
    }
}

// ---------------------------------------------------------------------------
// Layer 3: IMAGENET_MEAN / IMAGENET_STD constants
// ---------------------------------------------------------------------------

#[test]
fn imagenet_mean_std_match_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "imagenet_mean_std")
        .expect("fixture imagenet_mean_std not found");

    let expected_mean: Vec<f64> = fix["expected_mean"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let expected_std: Vec<f64> = fix["expected_std"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();

    for (i, (actual, expected)) in IMAGENET_MEAN.iter().zip(expected_mean.iter()).enumerate() {
        assert!(
            (actual - expected).abs() < 1e-9,
            "IMAGENET_MEAN[{i}]: actual={actual} expected={expected}"
        );
    }
    for (i, (actual, expected)) in IMAGENET_STD.iter().zip(expected_std.iter()).enumerate() {
        assert!(
            (actual - expected).abs() < 1e-9,
            "IMAGENET_STD[{i}]: actual={actual} expected={expected}"
        );
    }
}

// ---------------------------------------------------------------------------
// Layer 3: vision_manual_seed
// ---------------------------------------------------------------------------

#[test]
fn vision_manual_seed_seeded_determinism() {
    // Verify that seeding produces identical output from a stochastic transform.
    // Uses RandomHorizontalFlip with p=0.5 — seed same twice, results must match.
    vision_manual_seed(42);
    let flip = RandomHorizontalFlip::<f64>::new(0.5).unwrap();
    let data: Vec<f64> = (0..48).map(|i| i as f64 / 48.0).collect();
    let t1 = make_f64(data.clone(), vec![3, 4, 4]);
    let out1 = flip.apply(t1).unwrap();

    vision_manual_seed(42);
    let t2 = make_f64(data, vec![3, 4, 4]);
    let out2 = flip.apply(t2).unwrap();

    assert_eq!(
        out1.data().unwrap(),
        out2.data().unwrap(),
        "vision_manual_seed(42) must produce identical outputs on identical inputs"
    );
}

// ---------------------------------------------------------------------------
// Layer 3: RandomHorizontalFlip
// ---------------------------------------------------------------------------

#[test]
fn random_hflip_p1_always_flips_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "random_hflip_p1_always_flips")
        .expect("fixture random_hflip_p1_always_flips not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let flip = RandomHorizontalFlip::<f64>::new(1.0).unwrap();
    let out = flip.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-9, "hflip_p1");
}

#[test]
fn random_hflip_p0_never_flips_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "random_hflip_p0_never_flips")
        .expect("fixture random_hflip_p0_never_flips not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let flip = RandomHorizontalFlip::<f64>::new(0.0).unwrap();
    let out = flip.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-9, "hflip_p0");
}

#[test]
fn random_hflip_new_constructor() {
    let flip = RandomHorizontalFlip::<f64>::new(0.5).unwrap();
    let _default = RandomHorizontalFlip::<f64>::default();
    // Invalid p should fail.
    assert!(RandomHorizontalFlip::<f64>::new(1.5).is_err());
    assert!(RandomHorizontalFlip::<f64>::new(-0.1).is_err());
    // Shape contract.
    let data: Vec<f64> = (0..48).map(|i| i as f64 / 48.0).collect();
    let t = make_f64(data, vec![3, 4, 4]);
    vision_manual_seed(1);
    let out = flip.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 4, 4]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomVerticalFlip
// ---------------------------------------------------------------------------

#[test]
fn random_vflip_p1_always_flips_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "random_vflip_p1_always_flips")
        .expect("fixture random_vflip_p1_always_flips not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let flip = RandomVerticalFlip::<f64>::new(1.0).unwrap();
    let out = flip.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-9, "vflip_p1");
}

#[test]
fn random_vflip_p0_never_flips_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "random_vflip_p0_never_flips")
        .expect("fixture random_vflip_p0_never_flips not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let flip = RandomVerticalFlip::<f64>::new(0.0).unwrap();
    let out = flip.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-9, "vflip_p0");
}

#[test]
fn random_vflip_new_constructor() {
    let flip = RandomVerticalFlip::<f64>::new(0.5).unwrap();
    let _default = RandomVerticalFlip::<f64>::default();
    assert!(RandomVerticalFlip::<f64>::new(2.0).is_err());
    let data: Vec<f64> = (0..48).map(|i| i as f64 / 48.0).collect();
    let t = make_f64(data, vec![3, 4, 4]);
    vision_manual_seed(2);
    let out = flip.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 4, 4]);
}

// ---------------------------------------------------------------------------
// Layer 3: Compose
// ---------------------------------------------------------------------------

#[test]
fn compose_resize_normalize_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "compose_resize_normalize")
        .expect("fixture compose_resize_normalize not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let pipeline: Vec<Box<dyn Transform<f64>>> = vec![
        Box::new(Resize::<f64>::new(4, 4)),
        Box::new(VisionNormalize::<f64>::imagenet()),
    ];
    let composed = Compose::new(pipeline);
    assert_eq!(composed.len(), 2);
    assert!(!composed.is_empty());

    let input = make_f64(input_data, input_shape);
    let out = composed.apply(input).unwrap();

    assert_eq!(out.shape(), &expected_shape[..]);
    // Tolerance 1e-5: two consecutive ops compound rounding.
    assert_close_f64(out.data().unwrap(), &expected_data, 1e-5, "compose_resize_normalize");
}

#[test]
fn compose_new_len_is_empty() {
    // Exercises: Compose::new, Compose::len, Compose::is_empty
    let empty: Compose<f64> = Compose::new(vec![]);
    assert_eq!(Compose::len(&empty), 0);       // Compose::len
    assert!(Compose::is_empty(&empty));         // Compose::is_empty

    let one: Compose<f64> = Compose::new(vec![Box::new(Resize::<f64>::new(4, 4))]);
    assert_eq!(one.len(), 1);
    assert!(!one.is_empty());
}

// ---------------------------------------------------------------------------
// Layer 3: ColorJitter (zero params — output == input)
// ---------------------------------------------------------------------------

#[test]
fn color_jitter_zero_params_output_equals_input() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "color_jitter_zero_params")
        .expect("fixture color_jitter_zero_params not found");

    let input_data = flatten_nested_f64(&fix["input"]);
    let expected_data = flatten_nested_f64(&fix["expected"]);
    let input_shape: Vec<usize> = fix["input_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = make_f64(input_data, input_shape);
    let jitter = ColorJitter::<f64>::new(0.0, 0.0, 0.0, 0.0).unwrap();
    let out = jitter.apply(input).unwrap();

    assert_close_f64(out.data().unwrap(), &expected_data, 1e-9, "color_jitter_zero_params");
}

#[test]
fn color_jitter_new_constructor() {
    // Valid params
    let _j = ColorJitter::<f64>::new(0.2, 0.2, 0.2, 0.1).unwrap();
    // Invalid hue (>= 0.5)
    assert!(ColorJitter::<f64>::new(0.0, 0.0, 0.0, 0.5).is_err());
    // Invalid brightness (< 0)
    assert!(ColorJitter::<f64>::new(-0.1, 0.0, 0.0, 0.0).is_err());
}

#[test]
fn color_jitter_output_range_contract() {
    // Output must be clamped to [0.0, 1.0].
    vision_manual_seed(77);
    let data: Vec<f64> = (0..48).map(|i| i as f64 / 48.0).collect();
    let t = make_f64(data, vec![3, 4, 4]);
    let jitter = ColorJitter::<f64>::new(0.5, 0.5, 0.5, 0.2).unwrap();
    let out = jitter.apply(t).unwrap();
    for &v in out.data().unwrap() {
        assert!(
            (0.0..=1.0).contains(&v),
            "ColorJitter output {v} outside [0.0, 1.0]"
        );
    }
}

// ---------------------------------------------------------------------------
// Layer 3: RandomCrop shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_crop_new_constructor() {
    let _c = RandomCrop::<f64>::new(4, 4);
    let _sq = RandomCrop::<f64>::square(4);
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(10);
    let out = _c.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 4, 4]);
}

#[test]
fn random_crop_shape_contract_matches_reference() {
    let ff = load_fixtures();
    let fix = get_fixture(&ff.fixtures, "random_crop_shape_contract")
        .expect("fixture random_crop_shape_contract not found");

    let expected_shape: Vec<usize> = fix["expected_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(5);
    let crop = RandomCrop::<f64>::new(
        fix["params"]["crop_h"].as_u64().unwrap() as usize,
        fix["params"]["crop_w"].as_u64().unwrap() as usize,
    );
    let out = crop.apply(t).unwrap();
    assert_eq!(out.shape(), &expected_shape[..]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomResizedCrop shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_resized_crop_new_constructor() {
    let _r = RandomResizedCrop::<f64>::new(4, 4, (0.08, 1.0), (0.75, 1.333_3)).unwrap();
    // Invalid scale
    assert!(RandomResizedCrop::<f64>::new(4, 4, (0.0, 1.0), (0.75, 1.333_3)).is_err());
    // Invalid ratio
    assert!(RandomResizedCrop::<f64>::new(4, 4, (0.08, 1.0), (0.0, 1.333_3)).is_err());
}

#[test]
fn random_resized_crop_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(20);
    let crop = RandomResizedCrop::<f64>::new(4, 4, (0.08, 1.0), (0.75, 1.333_3)).unwrap();
    let out = crop.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 4, 4]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomRotation shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_rotation_new_constructor() {
    let _r = RandomRotation::<f64>::new(45.0).unwrap();
    assert!(RandomRotation::<f64>::new(-1.0).is_err());
}

#[test]
fn random_rotation_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(30);
    let rot = RandomRotation::<f64>::new(45.0).unwrap();
    let out = rot.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomGaussianBlur shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_gaussian_blur_new_constructor() {
    let _r = RandomGaussianBlur::<f64>::new(3, (0.1, 2.0)).unwrap();
    // Even kernel
    assert!(RandomGaussianBlur::<f64>::new(4, (0.1, 2.0)).is_err());
    // Zero sigma
    assert!(RandomGaussianBlur::<f64>::new(3, (0.0, 2.0)).is_err());
}

#[test]
fn random_gaussian_blur_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(40);
    let blur = RandomGaussianBlur::<f64>::new(3, (0.1, 2.0)).unwrap();
    let out = blur.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomApply shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_apply_new_constructor() {
    let transforms: Vec<Box<dyn Transform<f64>>> =
        vec![Box::new(Resize::<f64>::new(8, 8))];
    let _ra = RandomApply::<f64>::new(transforms, 0.5).unwrap();
    let bad_transforms: Vec<Box<dyn Transform<f64>>> =
        vec![Box::new(Resize::<f64>::new(8, 8))];
    assert!(RandomApply::<f64>::new(bad_transforms, 1.5).is_err());
}

#[test]
fn random_apply_p1_shape_contract() {
    // p=1.0 means always apply — inner is an identity resize.
    let transforms: Vec<Box<dyn Transform<f64>>> =
        vec![Box::new(Resize::<f64>::new(8, 8))];
    let ra = RandomApply::<f64>::new(transforms, 1.0).unwrap();
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    let out = ra.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: RandomChoice shape contract
// ---------------------------------------------------------------------------

#[test]
fn random_choice_new_constructor() {
    let transforms: Vec<Box<dyn Transform<f64>>> = vec![
        Box::new(Resize::<f64>::new(8, 8)),
        Box::new(Resize::<f64>::new(8, 8)),
    ];
    let _rc = RandomChoice::new(transforms).unwrap();
}

#[test]
fn random_choice_shape_contract() {
    let transforms: Vec<Box<dyn Transform<f64>>> = vec![
        Box::new(Resize::<f64>::new(8, 8)),
        Box::new(Resize::<f64>::new(8, 8)),
    ];
    let rc = RandomChoice::new(transforms).unwrap();
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(50);
    let out = rc.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: ElasticTransform shape contract (stochastic — excluded from full parity)
// ---------------------------------------------------------------------------

#[test]
fn elastic_transform_new_constructor() {
    let _e = ElasticTransform::<f64>::new(50.0, 5.0).unwrap();
    assert!(ElasticTransform::<f64>::new(-1.0, 5.0).is_err());
    assert!(ElasticTransform::<f64>::new(50.0, 0.0).is_err());
}

#[test]
fn elastic_transform_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(60);
    let et = ElasticTransform::<f64>::new(10.0, 3.0).unwrap();
    let out = et.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
    for &v in out.data().unwrap() {
        assert!(
            (0.0..=1.0_f64).contains(&v) || v.is_nan() || v.abs() < 1e-6,
            "ElasticTransform output {v} outside expected range"
        );
    }
}

// ---------------------------------------------------------------------------
// Layer 3: GaussianNoise (stochastic — excluded from full parity)
// ---------------------------------------------------------------------------

#[test]
fn gaussian_noise_new_constructor() {
    let _g = GaussianNoise::<f64>::new(0.0, 0.1).unwrap();
    assert!(GaussianNoise::<f64>::new(0.0, -0.1).is_err());
}

#[test]
fn gaussian_noise_zero_std_is_identity() {
    // std=0.0 adds no noise; output == input.
    let data: Vec<f64> = (0..48).map(|i| i as f64 / 48.0).collect();
    let t = make_f64(data.clone(), vec![3, 4, 4]);
    let noise = GaussianNoise::<f64>::new(0.0, 0.0).unwrap();
    let out = noise.apply(t).unwrap();
    assert_close_f64(out.data().unwrap(), &data, 1e-9, "gaussian_noise_zero_std");
}

#[test]
fn gaussian_noise_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(70);
    let noise = GaussianNoise::<f64>::new(0.0, 0.05).unwrap();
    let out = noise.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}

// ---------------------------------------------------------------------------
// Layer 3: TrivialAugmentWide (stochastic — excluded from full parity)
// ---------------------------------------------------------------------------

#[test]
fn trivial_augment_wide_new_constructor() {
    let _t = TrivialAugmentWide::<f64>::new(31).unwrap();
    let _d = TrivialAugmentWide::<f64>::default();
    assert!(TrivialAugmentWide::<f64>::new(0).is_err());
}

#[test]
fn trivial_augment_wide_shape_contract() {
    let data: Vec<f64> = (0..192).map(|i| i as f64 / 192.0).collect();
    let t = make_f64(data, vec![3, 8, 8]);
    vision_manual_seed(80);
    let aug = TrivialAugmentWide::<f64>::new(31).unwrap();
    let out = aug.apply(t).unwrap();
    assert_eq!(out.shape(), &[3, 8, 8]);
}
