//! Conformance suite for `ferrotorch-serialize` — Layer 3.
//!
//! Tracking issue: #857 (ferrotorch-serialize conformance suite).
//!
//! Reference libraries:
//!   - `torch == 2.11.0`          (pytorch save/load, pickle format)
//!   - `safetensors == 0.4.x`     (HuggingFace safetensors format)
//!
//! Fixtures live in `tests/conformance/fixtures.json`, generated by
//! `scripts/regenerate_serialize_fixtures.py`.
//!
//! ## Scope
//!
//! Every public item in `ferrotorch-serialize` that can be exercised
//! without a live GGUF binary, ONNX IR graph, or async runtime falls into:
//!
//! 1. **Fixture-driven tests** — items whose correct behaviour is fully
//!    determined by reference outputs in `fixtures.json`.
//!
//! 2. **cascade_skip** — items that require unavailable infrastructure
//!    (GGUF files, JIT IR graph, mmap on WSL2, sharded checkpoints).
//!    Each skip carries a tracking issue reference.
//!
//! ## cascade_skip convention
//!
//! `cascade_skip!(label)` prints a diagnostic and returns early. NOT
//! `#[ignore]` — the test still runs and emits the notice. Matches the
//! ferrotorch-mps / ferrotorch-train pattern (no silent skips).

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::uninlined_format_args,
    clippy::explicit_iter_loop,
    clippy::redundant_else
)]

use std::collections::HashMap;
use std::io::Read;
use std::ops::Add;
use std::path::PathBuf;

use ferrotorch_core::{FerrotorchError, Tensor, TensorStorage};
use ferrotorch_jit::graph::{IrGraph, IrOpKind};
use ferrotorch_nn::StateDict;
use ferrotorch_serialize::{
    GgmlType, GgufFile, GgufMetadata, GgufTensorInfo, GgufValue, OnnxExportConfig, PickleValue,
    TrainingCheckpoint, dequantize_gguf_tensor, export_from_program, export_ir_graph_to_onnx,
    export_onnx, ir_graph_to_onnx, load_checkpoint, load_gguf, load_gguf_mmap,
    load_gguf_state_dict, load_gguf_state_dict_mmap, load_pytorch_state_dict, load_safetensors,
    load_state_dict, parse_gguf_bytes, parse_pickle, save_checkpoint, save_pytorch,
    save_safetensors, save_state_dict, validate_checkpoint,
};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// cascade_skip macro
// ---------------------------------------------------------------------------

/// Print a skip diagnostic and return early. Never panics.
/// Kept for future cascade_skip additions; currently all items are covered.
#[allow(unused_macros)]
macro_rules! cascade_skip {
    ($reason:literal) => {{
        eprintln!("  [cascade_skip] {} — {}", module_path!(), $reason);
        return;
    }};
}

// ---------------------------------------------------------------------------
// Tensor construction helpers
// ---------------------------------------------------------------------------

fn make_f32(data: Vec<f32>, shape: Vec<usize>) -> Tensor<f32> {
    let storage = TensorStorage::cpu(data);
    Tensor::from_storage(storage, shape, false).unwrap()
}

fn make_f64(data: Vec<f64>, shape: Vec<usize>) -> Tensor<f64> {
    let storage = TensorStorage::cpu(data);
    Tensor::from_storage(storage, shape, false).unwrap()
}

fn state32(pairs: &[(&str, Vec<f32>, Vec<usize>)]) -> StateDict<f32> {
    let mut m: StateDict<f32> = HashMap::new();
    for (name, data, shape) in pairs {
        m.insert((*name).to_string(), make_f32(data.clone(), shape.clone()));
    }
    m
}

fn state64(pairs: &[(&str, Vec<f64>, Vec<usize>)]) -> StateDict<f64> {
    let mut m: StateDict<f64> = HashMap::new();
    for (name, data, shape) in pairs {
        m.insert((*name).to_string(), make_f64(data.clone(), shape.clone()));
    }
    m
}

// ---------------------------------------------------------------------------
// Fixture deserialization
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    metadata: FixtureMetadata,
    save_safetensors: Vec<serde_json::Value>,
    load_safetensors: Vec<serde_json::Value>,
    save_pytorch: Vec<serde_json::Value>,
    load_pytorch: Vec<serde_json::Value>,
    parse_pickle: Vec<serde_json::Value>,
    validate_checkpoint: Vec<serde_json::Value>,
    save_state_dict: Vec<serde_json::Value>,
    save_checkpoint: Vec<serde_json::Value>,
    training_checkpoint: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct FixtureMetadata {
    torch_version: String,
    safetensors_version: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    generated_at: String,
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    conformance_note: String,
}

fn load_fixtures() -> FixtureFile {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json");
    let bytes = std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "read {} failed: {e}. Regenerate via \
             scripts/regenerate_serialize_fixtures.py",
            p.display()
        )
    });
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", p.display()))
}

fn fixture_by_kind<'a>(arr: &'a [serde_json::Value], kind: &str) -> Option<&'a serde_json::Value> {
    arr.iter()
        .find(|v| v.get("kind").and_then(|k| k.as_str()) == Some(kind))
}

// ---------------------------------------------------------------------------
// Layer 2 sanity: fixture file covers expected sections
// ---------------------------------------------------------------------------

#[test]
fn fixture_file_has_all_sections() {
    let file = load_fixtures();
    eprintln!(
        "  fixture_file_has_all_sections: torch={}, safetensors={}, \
         {} save_safetensors, {} load_safetensors, {} save_pytorch, \
         {} load_pytorch, {} parse_pickle, {} validate_checkpoint, \
         {} save_state_dict, {} save_checkpoint, {} training_checkpoint",
        file.metadata.torch_version,
        file.metadata.safetensors_version,
        file.save_safetensors.len(),
        file.load_safetensors.len(),
        file.save_pytorch.len(),
        file.load_pytorch.len(),
        file.parse_pickle.len(),
        file.validate_checkpoint.len(),
        file.save_state_dict.len(),
        file.save_checkpoint.len(),
        file.training_checkpoint.len(),
    );
    assert!(
        !file.save_safetensors.is_empty(),
        "save_safetensors fixtures missing"
    );
    assert!(
        !file.load_safetensors.is_empty(),
        "load_safetensors fixtures missing"
    );
    assert!(
        !file.save_pytorch.is_empty(),
        "save_pytorch fixtures missing"
    );
    assert!(
        !file.load_pytorch.is_empty(),
        "load_pytorch fixtures missing"
    );
    assert!(
        !file.parse_pickle.is_empty(),
        "parse_pickle fixtures missing"
    );
    assert!(
        !file.validate_checkpoint.is_empty(),
        "validate_checkpoint fixtures missing"
    );
    assert!(
        !file.save_state_dict.is_empty(),
        "save_state_dict fixtures missing"
    );
    assert!(
        !file.save_checkpoint.is_empty(),
        "save_checkpoint fixtures missing"
    );
    assert!(
        !file.training_checkpoint.is_empty(),
        "training_checkpoint fixtures missing"
    );
}

// ---------------------------------------------------------------------------
// save_safetensors / load_safetensors — fixture-driven
// ---------------------------------------------------------------------------

/// save_safetensors + load_safetensors round-trips an f32 2D tensor
/// with byte-exact data preservation.
#[test]
fn save_load_safetensors_f32_2d() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_safetensors, "round_trip_f32_2d")
        .expect("round_trip_f32_2d fixture not found");

    let data: Vec<f32> = f["data_f32"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let name = f["tensor_name"].as_str().unwrap();
    let expected_numel = f["expected_numel"].as_u64().unwrap() as usize;
    let expected_bytes = f["expected_byte_length"].as_u64().unwrap() as usize;

    let state = state32(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("model.safetensors");

    save_safetensors(&state, &path).expect("save_safetensors failed");

    let file_bytes = std::fs::metadata(&path).unwrap().len() as usize;
    assert!(
        file_bytes >= expected_bytes,
        "safetensors file too small: {file_bytes} < {expected_bytes} tensor bytes"
    );

    let loaded: StateDict<f32> = load_safetensors(&path).expect("load_safetensors failed");
    let t = &loaded[name];
    assert_eq!(t.shape(), shape.as_slice(), "[{name}] shape mismatch");
    assert_eq!(t.numel(), expected_numel, "[{name}] numel mismatch");

    let got = t.data().unwrap();
    assert_eq!(got.len(), data.len(), "[{name}] data length mismatch");
    for (i, (&g, &exp)) in got.iter().zip(data.iter()).enumerate() {
        assert!(
            (g - exp).abs() < 1e-6,
            "[{name}][{i}]: expected {exp}, got {g}"
        );
    }
    eprintln!(
        "  save_load_safetensors_f32_2d: {} tensor, {} elements, {} bytes",
        name, expected_numel, expected_bytes
    );
}

/// save_safetensors + load_safetensors round-trips an f32 1D bias tensor.
#[test]
fn save_load_safetensors_f32_1d_bias() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_safetensors, "round_trip_f32_1d")
        .expect("round_trip_f32_1d fixture not found");

    let data: Vec<f32> = f["data_f32"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let name = f["tensor_name"].as_str().unwrap();

    let state = state32(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("bias.safetensors");

    save_safetensors(&state, &path).expect("save_safetensors failed");
    let loaded: StateDict<f32> = load_safetensors(&path).expect("load_safetensors failed");

    let got = loaded[name].data().unwrap();
    for (i, (&g, &exp)) in got.iter().zip(data.iter()).enumerate() {
        assert!(
            (g - exp).abs() < 1e-6,
            "[{name}][{i}]: expected {exp}, got {g}"
        );
    }
}

/// save_safetensors + load_safetensors round-trips an f64 2D tensor.
#[test]
fn save_load_safetensors_f64_2d() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_safetensors, "round_trip_f64_2d")
        .expect("round_trip_f64_2d fixture not found");

    let data: Vec<f64> = f["data_f64"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let name = f["tensor_name"].as_str().unwrap();

    let state = state64(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("param.safetensors");

    save_safetensors(&state, &path).expect("save_safetensors f64 failed");
    let loaded: StateDict<f64> = load_safetensors(&path).expect("load_safetensors f64 failed");

    let got = loaded[name].data().unwrap();
    for (i, (&g, &exp)) in got.iter().zip(data.iter()).enumerate() {
        assert!(
            (g - exp).abs() < 1e-12,
            "[{name}][{i}]: expected {exp}, got {g}"
        );
    }
}

/// save_safetensors preserves NaN and Inf values.
#[test]
fn save_load_safetensors_nan_inf() {
    let file = load_fixtures();
    let _f = fixture_by_kind(&file.save_safetensors, "nan_inf_preserved")
        .expect("nan_inf_preserved fixture not found");

    let data = vec![f32::NAN, f32::INFINITY, f32::NEG_INFINITY];
    let state = state32(&[("special", data.clone(), vec![3])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("special.safetensors");

    save_safetensors(&state, &path).expect("save_safetensors NaN/Inf failed");
    let loaded: StateDict<f32> = load_safetensors(&path).expect("load_safetensors NaN/Inf failed");

    let got = loaded["special"].data().unwrap();
    assert!(got[0].is_nan(), "NaN not preserved");
    assert!(got[1].is_infinite() && got[1] > 0.0, "+Inf not preserved");
    assert!(got[2].is_infinite() && got[2] < 0.0, "-Inf not preserved");
}

/// save_safetensors with empty state dict produces a valid file.
#[test]
fn save_load_safetensors_empty_state_dict() {
    let _file = load_fixtures();
    let state: StateDict<f32> = HashMap::new();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("empty.safetensors");

    save_safetensors(&state, &path).expect("save_safetensors empty failed");
    assert!(path.exists(), "file not created for empty state dict");

    let loaded: StateDict<f32> = load_safetensors(&path).expect("load_safetensors empty failed");
    assert!(loaded.is_empty(), "loaded state dict should be empty");
}

/// save_safetensors writes keys in sorted order.
#[test]
fn save_safetensors_deterministic_key_ordering() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_safetensors, "multi_tensor_sorted_keys")
        .expect("multi_tensor_sorted_keys fixture not found");

    let tensors = f["tensors"].as_array().unwrap();
    let expected_order: Vec<&str> = f["expected_key_order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    let mut state: StateDict<f32> = HashMap::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name, make_f32(data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("multi.safetensors");
    save_safetensors(&state, &path).expect("save_safetensors multi failed");

    // Load with safetensors raw to check key order.
    let loaded: StateDict<f32> = load_safetensors(&path).expect("load multi failed");
    let mut keys: Vec<&str> = loaded.keys().map(String::as_str).collect();
    keys.sort();
    assert_eq!(keys, expected_order, "key order mismatch after round-trip");
}

/// load_safetensors returns DtypeMismatch when the file dtype does not match T.
#[test]
fn load_safetensors_dtype_mismatch_error() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.load_safetensors, "dtype_mismatch_error")
        .expect("dtype_mismatch_error fixture not found");

    let expected_error = f["expected_error"].as_str().unwrap();
    assert_eq!(expected_error, "DtypeMismatch");

    // Write an f32 file.
    let state: StateDict<f32> = state32(&[("x", vec![1.0, 2.0], vec![2])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("dtype.safetensors");
    save_safetensors(&state, &path).expect("save failed");

    // Attempt to load as f64 — must fail with DtypeMismatch.
    let result: Result<StateDict<f64>, _> = load_safetensors(&path);
    assert!(
        result.is_err(),
        "load_safetensors should fail when loading f32 file as f64"
    );
    assert!(
        matches!(result.unwrap_err(), FerrotorchError::DtypeMismatch { .. }),
        "expected DtypeMismatch error"
    );
}

/// load_safetensors returns an error for a nonexistent file.
#[test]
fn load_safetensors_missing_file_error() {
    let file = load_fixtures();
    let _f = fixture_by_kind(&file.load_safetensors, "missing_file_error")
        .expect("missing_file_error fixture not found");

    let result: Result<StateDict<f32>, _> = load_safetensors("/nonexistent/model.safetensors");
    assert!(result.is_err(), "expected error for nonexistent file");
}

// ---------------------------------------------------------------------------
// save_pytorch / load_pytorch_state_dict — fixture-driven
// ---------------------------------------------------------------------------

/// save_pytorch produces a ZIP with the required structure and pickle content.
#[test]
fn save_pytorch_zip_structure_and_pickle() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_pytorch, "round_trip_f32")
        .expect("round_trip_f32 fixture not found");

    let data: Vec<f32> = f["data_f32"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let name = f["tensor_name"].as_str().unwrap();
    let expected_contains: Vec<&str> = f["expected_pickle_contains"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();
    let expected_storage_bytes = f["expected_storage_bytes"].as_u64().unwrap() as usize;

    let state = state32(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("model.pt");

    save_pytorch(&state, &path).expect("save_pytorch failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).expect("ZIP open failed");

    let names: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .collect();

    assert!(
        names.contains(&"archive/data.pkl".to_string()),
        "archive/data.pkl missing from ZIP"
    );
    assert!(
        names.iter().any(|n| n.starts_with("archive/data/")),
        "no archive/data/* storage blob in ZIP"
    );

    let pkl_bytes = {
        let mut e = archive.by_name("archive/data.pkl").unwrap();
        let mut v = Vec::new();
        e.read_to_end(&mut v).unwrap();
        v
    };

    // Pickle protocol 2 header.
    assert_eq!(
        pkl_bytes[0], 0x80,
        "pickle must start with PROTO opcode (0x80)"
    );
    assert_eq!(pkl_bytes[1], 0x02, "pickle must be protocol 2 (0x02)");
    // STOP opcode.
    assert_eq!(
        *pkl_bytes.last().unwrap(),
        0x2e,
        "pickle must end with STOP (0x2e)"
    );

    let pkl_str = String::from_utf8_lossy(&pkl_bytes);
    for token in &expected_contains {
        assert!(
            pkl_str.contains(token),
            "pickle missing expected token: {token:?}"
        );
    }

    // Verify storage blob size.
    let blob = {
        let mut e = archive.by_name("archive/data/0").unwrap();
        let mut v = Vec::new();
        e.read_to_end(&mut v).unwrap();
        v
    };
    assert_eq!(
        blob.len(),
        expected_storage_bytes,
        "storage blob size mismatch: expected {expected_storage_bytes}, got {}",
        blob.len()
    );

    // Verify tensor bytes are correct (little-endian f32).
    let values: Vec<f32> = blob
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect();
    for (i, (&got, &exp)) in values.iter().zip(data.iter()).enumerate() {
        assert!(
            (got - exp).abs() < 1e-7,
            "storage blob[{i}]: expected {exp}, got {got}"
        );
    }

    eprintln!(
        "  save_pytorch_zip_structure_and_pickle: {} entries in ZIP, {} pickle bytes, {} storage bytes",
        names.len(),
        pkl_bytes.len(),
        expected_storage_bytes
    );
}

/// save_pytorch uses DoubleStorage for f64.
#[test]
fn save_pytorch_f64_double_storage() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_pytorch, "round_trip_f64")
        .expect("round_trip_f64 fixture not found");

    let data: Vec<f64> = f["data_f64"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let name = f["tensor_name"].as_str().unwrap();
    let expected_contains: Vec<&str> = f["expected_pickle_contains"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    let state = state64(&[(name, data, shape)]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("model_f64.pt");

    save_pytorch(&state, &path).expect("save_pytorch f64 failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let mut pkl_entry = archive.by_name("archive/data.pkl").unwrap();
    let mut pkl_bytes = Vec::new();
    pkl_entry.read_to_end(&mut pkl_bytes).unwrap();
    let pkl_str = String::from_utf8_lossy(&pkl_bytes);

    for token in &expected_contains {
        assert!(
            pkl_str.contains(token),
            "f64 pickle missing token: {token:?}"
        );
    }
}

/// save_pytorch with two tensors produces two numbered storage entries.
#[test]
fn save_pytorch_multi_tensor_zip_entries() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_pytorch, "zip_structure")
        .expect("zip_structure fixture not found");

    let tensors = f["tensors"].as_array().unwrap();
    let expected_entries: Vec<&str> = f["expected_zip_entries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    let mut state: StateDict<f32> = HashMap::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name, make_f32(data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("multi.pt");
    save_pytorch(&state, &path).expect("save_pytorch multi failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let names: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .collect();

    for entry in &expected_entries {
        assert!(
            names.contains(&entry.to_string()),
            "ZIP missing entry: {entry}"
        );
    }
}

/// save_pytorch with empty state dict produces a valid ZIP with data.pkl.
#[test]
fn save_pytorch_empty_state_dict() {
    let _file = load_fixtures();
    let state: StateDict<f32> = HashMap::new();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("empty.pt");

    save_pytorch(&state, &path).expect("save_pytorch empty failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let names: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .collect();
    assert!(
        names.contains(&"archive/data.pkl".to_string()),
        "empty .pt missing data.pkl"
    );
}

/// save_pytorch uses pickle protocol 2 header and STOP opcode.
#[test]
fn save_pytorch_pickle_protocol_header() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_pytorch, "pickle_protocol")
        .expect("pickle_protocol fixture not found");

    let header_bytes: Vec<u8> = f["pickle_header_bytes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u8)
        .collect();
    let stop_byte = f["pickle_stop_byte"].as_u64().unwrap() as u8;

    // Build any minimal state dict and check pickle bytes.
    let state = state32(&[("x", vec![1.0_f32], vec![1])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("proto.pt");
    save_pytorch(&state, &path).expect("save_pytorch proto failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let mut pkl_entry = archive.by_name("archive/data.pkl").unwrap();
    let mut pkl_bytes = Vec::new();
    pkl_entry.read_to_end(&mut pkl_bytes).unwrap();

    assert_eq!(pkl_bytes[0], header_bytes[0], "PROTO opcode byte mismatch");
    assert_eq!(
        pkl_bytes[1], header_bytes[1],
        "protocol version byte mismatch"
    );
    assert_eq!(
        *pkl_bytes.last().unwrap(),
        stop_byte,
        "STOP opcode byte mismatch"
    );
}

/// save_pytorch writes keys in sorted (alphabetical) order in the pickle.
#[test]
fn save_pytorch_deterministic_key_ordering() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_pytorch, "deterministic_ordering")
        .expect("deterministic_ordering fixture not found");

    let tensors = f["tensors"].as_array().unwrap();
    let expected_order: Vec<&str> = f["expected_key_order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    let mut state: StateDict<f32> = HashMap::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name, make_f32(data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("order.pt");
    save_pytorch(&state, &path).expect("save_pytorch order failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let mut pkl_entry = archive.by_name("archive/data.pkl").unwrap();
    let mut pkl_bytes = Vec::new();
    pkl_entry.read_to_end(&mut pkl_bytes).unwrap();
    let pkl_str = String::from_utf8_lossy(&pkl_bytes);

    let positions: Vec<usize> = expected_order
        .iter()
        .map(|key| {
            pkl_str
                .find(key)
                .unwrap_or_else(|| panic!("key {key:?} not found in pickle"))
        })
        .collect();

    for i in 1..positions.len() {
        assert!(
            positions[i - 1] < positions[i],
            "key order violated: {:?} ({}) appears after {:?} ({})",
            expected_order[i - 1],
            positions[i - 1],
            expected_order[i],
            positions[i]
        );
    }
}

/// load_pytorch_state_dict round-trips a save_pytorch file.
#[test]
fn load_pytorch_state_dict_round_trip() {
    let file = load_fixtures();
    let f =
        fixture_by_kind(&file.load_pytorch, "round_trip").expect("round_trip fixture not found");

    let tensors = f["tensors"].as_array().unwrap();
    let mut state: StateDict<f32> = HashMap::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name, make_f32(data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("rt.pt");
    save_pytorch(&state, &path).expect("save_pytorch failed");

    let loaded: StateDict<f32> = load_pytorch_state_dict(&path).expect("load_pytorch failed");
    assert_eq!(loaded.len(), state.len(), "tensor count mismatch");

    for t in tensors {
        let name = t["name"].as_str().unwrap();
        let orig_data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let orig_shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();

        let lt = &loaded[name];
        assert_eq!(lt.shape(), orig_shape.as_slice(), "[{name}] shape mismatch");
        let got = lt.data().unwrap();
        for (i, (&g, &exp)) in got.iter().zip(orig_data.iter()).enumerate() {
            assert!(
                (g - exp).abs() < 1e-6,
                "[{name}][{i}]: expected {exp}, got {g}"
            );
        }
    }
}

/// load_pytorch_state_dict returns an error for a nonexistent file.
#[test]
fn load_pytorch_state_dict_missing_file_error() {
    let _file = load_fixtures();
    let result: Result<StateDict<f32>, _> = load_pytorch_state_dict("/nonexistent/model.pt");
    assert!(result.is_err(), "expected error for missing .pt file");
}

// ---------------------------------------------------------------------------
// parse_pickle — fixture-driven
// ---------------------------------------------------------------------------

/// parse_pickle accepts the pickle bytes produced by save_pytorch (protocol 2).
#[test]
fn parse_pickle_accepts_protocol_2() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.parse_pickle, "protocol_check")
        .expect("protocol_check fixture not found");

    let expected_protocol = f["expected_protocol"].as_u64().unwrap() as u8;
    assert_eq!(expected_protocol, 2);

    // Build a minimal .pt file and extract its pickle bytes.
    let state = state32(&[("w", vec![1.0_f32, 2.0], vec![2])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("parse.pt");
    save_pytorch(&state, &path).expect("save_pytorch failed");

    let zip_file = std::fs::File::open(&path).unwrap();
    let mut archive = zip::ZipArchive::new(zip_file).unwrap();
    let mut pkl_entry = archive.by_name("archive/data.pkl").unwrap();
    let mut pkl_bytes = Vec::new();
    pkl_entry.read_to_end(&mut pkl_bytes).unwrap();

    // parse_pickle must not return an error.
    let result = parse_pickle(&pkl_bytes);
    assert!(
        result.is_ok(),
        "parse_pickle failed on protocol-2 bytes: {:?}",
        result.unwrap_err()
    );

    // The parsed value must be a PickleValue.
    let _pv: PickleValue = result.unwrap();
    eprintln!(
        "  parse_pickle_accepts_protocol_2: {} pickle bytes parsed",
        pkl_bytes.len()
    );
}

// ---------------------------------------------------------------------------
// validate_checkpoint — fixture-driven
// ---------------------------------------------------------------------------

/// validate_checkpoint returns Ok(()) for a freshly written .pt file.
#[test]
fn validate_checkpoint_valid_file_passes() {
    let _file = load_fixtures();
    let state = state32(&[("x", vec![1.0_f32, 2.0], vec![2])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("valid.pt");

    save_pytorch(&state, &path).expect("save_pytorch failed");
    validate_checkpoint(&path).expect("validate_checkpoint should pass for valid file");
}

/// validate_checkpoint returns an error for a nonexistent file.
#[test]
fn validate_checkpoint_missing_file_error() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.validate_checkpoint, "missing_file_error")
        .expect("missing_file_error fixture not found");

    let path = f["path"].as_str().unwrap();
    let result = validate_checkpoint(path);
    assert!(
        result.is_err(),
        "expected error for missing checkpoint file"
    );
}

/// validate_checkpoint returns an error for a corrupt (non-ZIP) file.
#[test]
fn validate_checkpoint_corrupt_file_error() {
    let _file = load_fixtures();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("corrupt.pt");
    std::fs::write(&path, b"this is not a ZIP file").unwrap();

    let result = validate_checkpoint(&path);
    assert!(
        result.is_err(),
        "expected error for corrupt checkpoint file"
    );
}

// ---------------------------------------------------------------------------
// save_state_dict / load_state_dict — fixture-driven
// ---------------------------------------------------------------------------

/// save_state_dict + load_state_dict round-trips an f32 state dict.
#[test]
fn save_load_state_dict_f32_round_trip() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "round_trip_f32")
        .expect("round_trip_f32 fixture not found");
    let label = f["label"].as_str().unwrap();

    let tensors = f["tensors"].as_array().unwrap();
    let mut state: StateDict<f32> = HashMap::new();
    let mut expected: Vec<(String, Vec<f32>, Vec<usize>)> = Vec::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name.clone(), make_f32(data.clone(), shape.clone()));
        expected.push((name, data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("state.fts");

    save_state_dict(&state, &path).expect("save_state_dict f32 failed");
    let loaded: StateDict<f32> = load_state_dict(&path).expect("load_state_dict f32 failed");

    assert_eq!(loaded.len(), state.len(), "[{label}] tensor count mismatch");
    for (name, exp_data, exp_shape) in &expected {
        let t = &loaded[name];
        assert_eq!(
            t.shape(),
            exp_shape.as_slice(),
            "[{label}][{name}] shape mismatch"
        );
        let got = t.data().unwrap();
        for (i, (&g, &exp)) in got.iter().zip(exp_data.iter()).enumerate() {
            assert!(
                (g - exp).abs() < 1e-6,
                "[{label}][{name}][{i}]: expected {exp}, got {g}"
            );
        }
    }
}

/// save_state_dict + load_state_dict round-trips an f64 state dict.
#[test]
fn save_load_state_dict_f64_round_trip() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "round_trip_f64")
        .expect("round_trip_f64 fixture not found");
    let label = f["label"].as_str().unwrap();

    let tensors = f["tensors"].as_array().unwrap();
    let mut state: StateDict<f64> = HashMap::new();
    let mut expected: Vec<(String, Vec<f64>, Vec<usize>)> = Vec::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f64> = t["data_f64"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name.clone(), make_f64(data.clone(), shape.clone()));
        expected.push((name, data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("state64.fts");

    save_state_dict(&state, &path).expect("save_state_dict f64 failed");
    let loaded: StateDict<f64> = load_state_dict(&path).expect("load_state_dict f64 failed");

    for (name, exp_data, _) in &expected {
        let got = loaded[name].data().unwrap();
        for (i, (&g, &exp)) in got.iter().zip(exp_data.iter()).enumerate() {
            assert!(
                (g - exp).abs() < 1e-12,
                "[{label}][{name}][{i}]: expected {exp}, got {g}"
            );
        }
    }
}

/// save_state_dict uses dtype tag "f32" for Float=f32.
#[test]
fn save_state_dict_dtype_tag_f32() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "dtype_tag_f32")
        .expect("dtype_tag_f32 fixture not found");
    let expected_tag = f["expected_dtype_tag"].as_str().unwrap();
    assert_eq!(expected_tag, "f32");

    let state = state32(&[("w", vec![1.0_f32], vec![1])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("tag.fts");
    save_state_dict(&state, &path).expect("save_state_dict failed");

    // The state_dict file is binary after `\n---\n`; read raw bytes and
    // inspect only the header portion (before the separator).
    let raw = std::fs::read(&path).unwrap();
    let sep = b"\n---\n";
    let sep_pos = raw
        .windows(sep.len())
        .position(|w| w == sep)
        .unwrap_or(raw.len());
    let header = std::str::from_utf8(&raw[..sep_pos]).expect("header is valid UTF-8");
    assert!(
        header.contains("\"dtype\":\"f32\""),
        "header must contain dtype=f32, got: {header}"
    );
}

/// save_state_dict uses dtype tag "f64" for Float=f64.
#[test]
fn save_state_dict_dtype_tag_f64() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "dtype_tag_f64")
        .expect("dtype_tag_f64 fixture not found");
    let expected_tag = f["expected_dtype_tag"].as_str().unwrap();
    assert_eq!(expected_tag, "f64");

    let state = state64(&[("p", vec![1.0_f64], vec![1])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("tag64.fts");
    save_state_dict(&state, &path).expect("save_state_dict f64 failed");

    let bytes = std::fs::read(&path).unwrap();
    let sep_pos = bytes
        .windows(5)
        .position(|w| w == b"\n---\n")
        .unwrap_or(bytes.len());
    let header = std::str::from_utf8(&bytes[..sep_pos]).unwrap();
    assert!(
        header.contains("\"dtype\":\"f64\""),
        "header must contain dtype=f64"
    );
}

/// save_state_dict preserves scalar (empty-shape) tensors.
#[test]
fn save_state_dict_scalar_shape() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "scalar_shape")
        .expect("scalar_shape fixture not found");

    let name = f["tensor_name"].as_str().unwrap();
    let data: Vec<f64> = f["data_f64"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let state = state64(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("scalar.fts");

    save_state_dict(&state, &path).expect("save scalar failed");
    let loaded: StateDict<f64> = load_state_dict(&path).expect("load scalar failed");

    assert_eq!(
        loaded[name].shape(),
        shape.as_slice(),
        "scalar shape must be []"
    );
    assert!(
        (loaded[name].data().unwrap()[0] - data[0]).abs() < 1e-12,
        "scalar value mismatch"
    );
}

/// save_state_dict preserves a 4D tensor shape.
#[test]
fn save_state_dict_high_rank_shape() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "high_rank_shape")
        .expect("high_rank_shape fixture not found");

    let name = f["tensor_name"].as_str().unwrap();
    let shape: Vec<usize> = f["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_numel = f["numel"].as_u64().unwrap() as usize;

    // Data is generated from numel (0..N as f64); the fixture records only
    // the shape and element count — not the raw values.
    let data: Vec<f64> = (0..expected_numel).map(|i| i as f64).collect();

    let state = state64(&[(name, data.clone(), shape.clone())]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("high_rank.fts");

    save_state_dict(&state, &path).expect("save high_rank failed");
    let loaded: StateDict<f64> = load_state_dict(&path).expect("load high_rank failed");

    assert_eq!(loaded[name].shape(), shape.as_slice(), "4D shape mismatch");
    assert_eq!(loaded[name].numel(), expected_numel, "numel mismatch");
}

/// save_state_dict writes keys in sorted alphabetical order.
#[test]
fn save_state_dict_deterministic_key_ordering() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "deterministic_key_ordering")
        .expect("deterministic_key_ordering fixture not found");

    let tensors = f["tensors"].as_array().unwrap();
    let expected_order: Vec<&str> = f["expected_key_order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();

    let mut state: StateDict<f64> = HashMap::new();
    for t in tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f64> = t["data_f64"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        state.insert(name, make_f64(data, shape));
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("order.fts");
    save_state_dict(&state, &path).expect("save_state_dict order failed");

    let bytes = std::fs::read(&path).unwrap();
    let sep_pos = bytes
        .windows(5)
        .position(|w| w == b"\n---\n")
        .unwrap_or(bytes.len());
    let header = std::str::from_utf8(&bytes[..sep_pos]).unwrap();

    let positions: Vec<usize> = expected_order
        .iter()
        .map(|key| {
            header
                .find(key)
                .unwrap_or_else(|| panic!("key {key:?} not in header"))
        })
        .collect();

    for i in 1..positions.len() {
        assert!(
            positions[i - 1] < positions[i],
            "key order violated: {:?} appears after {:?} in header",
            expected_order[i - 1],
            expected_order[i]
        );
    }
}

/// load_state_dict returns DtypeMismatch for f32-file loaded as f64.
#[test]
fn load_state_dict_dtype_mismatch_error() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_state_dict, "dtype_mismatch_error_on_load")
        .expect("dtype_mismatch_error_on_load fixture not found");

    let expected_error = f["expected_error"].as_str().unwrap();
    assert_eq!(expected_error, "DtypeMismatch");

    let state: StateDict<f32> = state32(&[("x", vec![1.0, 2.0], vec![2])]);
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("mismatch.fts");
    save_state_dict(&state, &path).expect("save failed");

    let result: Result<StateDict<f64>, _> = load_state_dict(&path);
    assert!(result.is_err(), "expected DtypeMismatch error");
    assert!(
        matches!(result.unwrap_err(), FerrotorchError::DtypeMismatch { .. }),
        "error must be DtypeMismatch"
    );
}

/// load_state_dict returns an error for a nonexistent file.
#[test]
fn load_state_dict_missing_file_error() {
    let _file = load_fixtures();
    let result: Result<StateDict<f32>, _> = load_state_dict("/nonexistent/state.fts");
    assert!(
        result.is_err(),
        "expected error for missing state dict file"
    );
    let msg = format!("{}", result.unwrap_err());
    assert!(
        msg.contains("failed to open file"),
        "error message should mention 'failed to open file', got: {msg}"
    );
}

/// save_state_dict + load_state_dict round-trips an empty dict.
#[test]
fn save_load_state_dict_empty_round_trip() {
    let _file = load_fixtures();
    let state: StateDict<f64> = HashMap::new();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("empty.fts");

    save_state_dict(&state, &path).expect("save empty state dict failed");
    let loaded: StateDict<f64> = load_state_dict(&path).expect("load empty state dict failed");
    assert!(loaded.is_empty(), "loaded empty dict should be empty");
}

// ---------------------------------------------------------------------------
// save_checkpoint / load_checkpoint — fixture-driven
// ---------------------------------------------------------------------------

/// save_checkpoint + load_checkpoint round-trips model state, epoch, and step.
#[test]
fn save_load_checkpoint_f32_round_trip() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_checkpoint, "round_trip_f32")
        .expect("round_trip_f32 checkpoint fixture not found");
    let label = f["label"].as_str().unwrap();

    let model_tensors = f["model_tensors"].as_array().unwrap();
    let epoch = f["epoch"].as_u64().unwrap() as usize;
    let step = f["step"].as_u64().unwrap() as usize;

    let mut model_state: StateDict<f32> = HashMap::new();
    let mut expected: Vec<(String, Vec<f32>, Vec<usize>)> = Vec::new();
    for t in model_tensors {
        let name = t["name"].as_str().unwrap().to_string();
        let data: Vec<f32> = t["data_f32"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let shape: Vec<usize> = t["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        model_state.insert(name.clone(), make_f32(data.clone(), shape.clone()));
        expected.push((name, data, shape));
    }

    let checkpoint = TrainingCheckpoint::new(
        model_state,
        ferrotorch_optim::OptimizerState::default(),
        epoch,
        step,
    );

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("ckpt.ft");

    save_checkpoint(&checkpoint, &path).expect("save_checkpoint failed");
    let loaded: TrainingCheckpoint<f32> = load_checkpoint(&path).expect("load_checkpoint failed");

    assert_eq!(loaded.epoch, epoch, "[{label}] epoch mismatch");
    assert_eq!(loaded.step, step, "[{label}] step mismatch");

    for (name, exp_data, exp_shape) in &expected {
        let t = &loaded.model_state[name];
        assert_eq!(
            t.shape(),
            exp_shape.as_slice(),
            "[{label}][{name}] shape mismatch"
        );
        let got = t.data().unwrap();
        for (i, (&g, &exp)) in got.iter().zip(exp_data.iter()).enumerate() {
            assert!(
                (g - exp).abs() < 1e-6,
                "[{label}][{name}][{i}]: expected {exp}, got {g}"
            );
        }
    }

    eprintln!("  save_load_checkpoint_f32_round_trip: epoch={epoch}, step={step}");
}

/// load_checkpoint preserves epoch and step independently.
#[test]
fn load_checkpoint_epoch_step_preserved() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.save_checkpoint, "epoch_step_preserved")
        .expect("epoch_step_preserved fixture not found");
    let label = f["label"].as_str().unwrap();

    let epoch = f["epoch"].as_u64().unwrap() as usize;
    let step = f["step"].as_u64().unwrap() as usize;

    let state: StateDict<f32> = state32(&[("w", vec![0.0_f32], vec![1])]);
    let checkpoint = TrainingCheckpoint::new(
        state,
        ferrotorch_optim::OptimizerState::default(),
        epoch,
        step,
    );

    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("epoch_step.ft");

    save_checkpoint(&checkpoint, &path).expect("save failed");
    let loaded: TrainingCheckpoint<f32> = load_checkpoint(&path).expect("load failed");

    assert_eq!(loaded.epoch, epoch, "[{label}] epoch must be {epoch}");
    assert_eq!(loaded.step, step, "[{label}] step must be {step}");
}

/// load_checkpoint returns an error for a nonexistent file.
#[test]
fn load_checkpoint_missing_file_error() {
    let _file = load_fixtures();
    let result: Result<TrainingCheckpoint<f32>, _> = load_checkpoint("/nonexistent/checkpoint.ft");
    assert!(
        result.is_err(),
        "expected error for missing checkpoint file"
    );
}

// ---------------------------------------------------------------------------
// TrainingCheckpoint — fixture-driven
// ---------------------------------------------------------------------------

/// TrainingCheckpoint::new stores epoch and step.
#[test]
fn training_checkpoint_new_stores_fields() {
    let file = load_fixtures();
    let f = fixture_by_kind(&file.training_checkpoint, "constructor")
        .expect("constructor fixture not found");

    let epoch = f["epoch"].as_u64().unwrap() as usize;
    let step = f["step"].as_u64().unwrap() as usize;

    let state: StateDict<f32> = state32(&[("p", vec![1.0_f32], vec![1])]);
    let ckpt = TrainingCheckpoint::new(
        state,
        ferrotorch_optim::OptimizerState::default(),
        epoch,
        step,
    );

    assert_eq!(
        ckpt.epoch, epoch,
        "TrainingCheckpoint::new must store epoch"
    );
    assert_eq!(ckpt.step, step, "TrainingCheckpoint::new must store step");
    assert_eq!(ckpt.model_state.len(), 1, "model_state must have 1 tensor");
}

// ---------------------------------------------------------------------------
// GGUF conformance tests (#848)
//
// Fixture: tests/conformance/fixtures/serialize_gguf.bin
// Generated by: scripts/regenerate_serialize_gguf_fixtures.py
//
// Fixture contents:
//   metadata: "general.architecture" = "llama", "general.name" = "test_model"
//   tensors:  weights.0 [4,4] F32, weights.1 [8] F32, weights.q8 [32] Q8_0
// ---------------------------------------------------------------------------

fn gguf_fixture_path() -> std::path::PathBuf {
    let manifest = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest.join("tests/conformance/fixtures/serialize_gguf.bin")
}

fn gguf_fixture_bytes() -> Vec<u8> {
    let path = gguf_fixture_path();
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("Failed to read GGUF fixture at {}: {e}", path.display()))
}

/// parse_gguf_bytes: parse in-memory bytes, check metadata + tensor counts.
#[test]
fn gguf_parse_gguf_bytes() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).expect("parse_gguf_bytes must succeed on valid fixture");
    assert_eq!(file.version, 3, "GGUF version must be 3");
    assert_eq!(
        file.metadata.entries.len(),
        2,
        "fixture has 2 metadata entries"
    );
    assert_eq!(file.tensors.len(), 3, "fixture has 3 tensors");
}

/// load_gguf: load via path, same structural assertions as parse_gguf_bytes.
#[test]
fn gguf_load_gguf() {
    let path = gguf_fixture_path();
    let file = load_gguf(&path).expect("load_gguf must succeed on valid fixture");
    assert_eq!(file.version, 3);
    assert_eq!(file.metadata.entries.len(), 2);
    assert_eq!(file.tensors.len(), 3);
}

/// load_gguf_mmap: same assertions, exercising the mmap code path.
#[test]
fn gguf_load_gguf_mmap() {
    let path = gguf_fixture_path();
    let file = load_gguf_mmap(&path).expect("load_gguf_mmap must succeed on valid fixture");
    assert_eq!(file.version, 3);
    assert_eq!(file.metadata.entries.len(), 2);
    assert_eq!(file.tensors.len(), 3);
}

/// load_gguf_state_dict: state dict must contain all 3 tensor names as keys.
#[test]
fn gguf_load_gguf_state_dict() {
    let path = gguf_fixture_path();
    let sd = load_gguf_state_dict(&path).expect("load_gguf_state_dict must succeed");
    assert!(
        sd.contains_key("weights.0"),
        "state dict must have weights.0"
    );
    assert!(
        sd.contains_key("weights.1"),
        "state dict must have weights.1"
    );
    assert!(
        sd.contains_key("weights.q8"),
        "state dict must have weights.q8"
    );
    assert_eq!(sd.len(), 3);
}

/// load_gguf_state_dict_mmap: same via mmap path.
#[test]
fn gguf_load_gguf_state_dict_mmap() {
    let path = gguf_fixture_path();
    let sd = load_gguf_state_dict_mmap(&path).expect("load_gguf_state_dict_mmap must succeed");
    assert!(sd.contains_key("weights.0"));
    assert!(sd.contains_key("weights.1"));
    assert!(sd.contains_key("weights.q8"));
    assert_eq!(sd.len(), 3);
}

/// GgufFile: structural field access — version, metadata, tensors.
#[test]
fn gguf_file_struct_fields() {
    let bytes = gguf_fixture_bytes();
    let file: GgufFile = parse_gguf_bytes(&bytes).unwrap();
    // version is a pub field on GgufFile
    let _version: u32 = file.version;
    // metadata is a pub field of type GgufMetadata
    let _meta: &GgufMetadata = &file.metadata;
    // tensors is a pub Vec<GgufTensorInfo>
    let _tensors: &Vec<GgufTensorInfo> = &file.tensors;
    assert_eq!(file.version, 3);
}

/// GgufMetadata: entries HashMap is accessible.
#[test]
fn gguf_metadata_entries() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).unwrap();
    let meta: &GgufMetadata = &file.metadata;
    assert!(
        meta.entries.contains_key("general.architecture"),
        "metadata must contain general.architecture"
    );
    assert_eq!(
        meta.entries.get("general.architecture"),
        Some(&GgufValue::String("llama".to_string()))
    );
    assert_eq!(
        meta.entries.get("general.name"),
        Some(&GgufValue::String("test_model".to_string()))
    );
}

/// GgufTensorInfo: name, dims, ggml_type, offset fields accessible.
#[test]
fn gguf_tensor_info_fields() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).unwrap();
    let info: &GgufTensorInfo = file
        .tensors
        .iter()
        .find(|t| t.name == "weights.0")
        .expect("weights.0 tensor info must exist");
    let _name: &str = &info.name;
    let _dims: &Vec<u64> = &info.dims;
    let _gtype: GgmlType = info.ggml_type;
    let _offset: u64 = info.offset;
    assert_eq!(info.dims, vec![4, 4]);
    assert_eq!(info.ggml_type, GgmlType::F32);
}

/// GgufValue: variant construction and matching.
#[test]
fn gguf_value_variants() {
    // Exercise several GgufValue variants.
    let sv = GgufValue::String("hello".to_string());
    let uv = GgufValue::Uint32(42);
    let fv = GgufValue::Float32(1.5);
    let bv = GgufValue::Bool(true);
    let av = GgufValue::Array(vec![GgufValue::Uint32(1), GgufValue::Uint32(2)]);

    assert!(matches!(sv, GgufValue::String(_)));
    assert!(matches!(uv, GgufValue::Uint32(42)));
    assert!(matches!(fv, GgufValue::Float32(_)));
    assert!(matches!(bv, GgufValue::Bool(true)));
    assert!(matches!(av, GgufValue::Array(_)));
}

/// GgmlType: variant matching on parsed tensor type.
#[test]
fn gguf_ggml_type_variant() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).unwrap();
    let w0 = file.tensors.iter().find(|t| t.name == "weights.0").unwrap();
    assert_eq!(w0.ggml_type, GgmlType::F32);
    let wq = file
        .tensors
        .iter()
        .find(|t| t.name == "weights.q8")
        .unwrap();
    assert_eq!(wq.ggml_type, GgmlType::Q8_0);
}

/// dequantize_gguf_tensor: F32 passthrough — shape and finite values.
#[test]
fn gguf_dequantize_gguf_tensor_f32() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).unwrap();
    let tensor = dequantize_gguf_tensor(&file, "weights.0")
        .expect("dequantize_gguf_tensor must succeed for F32 tensor");
    assert_eq!(tensor.shape(), &[4, 4]);
    let data: &[f32] = tensor.data().expect("tensor data must be accessible");
    assert_eq!(data.len(), 16);
    assert!(
        data.iter().all(|v| v.is_finite()),
        "all dequantized F32 values must be finite"
    );
    // Deterministic values: row-major 0.0 .. 15.0
    for (i, &v) in data.iter().enumerate() {
        assert!(
            (v - i as f32).abs() < 1e-6,
            "weights.0[{i}] expected {}, got {v}",
            i as f32
        );
    }
}

/// dequantize_gguf_tensor: Q8_0 tensor — shape and finite values.
#[test]
fn gguf_dequantize_gguf_tensor_q8_0() {
    let bytes = gguf_fixture_bytes();
    let file = parse_gguf_bytes(&bytes).unwrap();
    let tensor = dequantize_gguf_tensor(&file, "weights.q8")
        .expect("dequantize_gguf_tensor must succeed for Q8_0 tensor");
    assert_eq!(tensor.shape(), &[32]);
    let data: &[f32] = tensor.data().expect("tensor data must be accessible");
    assert_eq!(data.len(), 32);
    assert!(
        data.iter().all(|v| v.is_finite()),
        "all dequantized Q8_0 values must be finite"
    );
}

// ---------------------------------------------------------------------------
// ONNX export conformance tests (#849)
//
// IrGraph is constructed directly (no tracing required).  The public API
// `IrGraph::new / add_input / add_node / set_outputs` matches what the
// onnx_export unit tests use internally.
// ---------------------------------------------------------------------------

/// Build a minimal add graph: val_0 + val_0 → val_1.
fn make_add_graph_for_onnx() -> IrGraph {
    let mut g = IrGraph::new();
    let x = g.add_input(vec![2, 3]);
    let (_, outs) = g.add_node(IrOpKind::Add, vec![x, x], vec![vec![2, 3]]);
    g.set_outputs(vec![outs[0]]);
    g
}

/// Assert ONNX byte-stream discrimination beyond `bytes[0] == 0x08`.
///
/// This is the canonical no-deps idiom mirrored from the src-side internal
/// `test_roundtrip_structure` (`onnx_export.rs:1478-1524`): byte-window
/// substring searches for known field-tag bytes, the configured model_name,
/// the graph helper's value-name labels (`val_0`, `val_1`), and the
/// `make_add_graph_for_onnx` op-type (`Add`). A 1-byte (or 200-byte all-0x08)
/// stub fails every needle but the leading-tag check, locking in
/// real-vs-stub discrimination without pulling `prost` or an ONNX schema crate
/// into the workspace.
///
/// `expected_model_name` is the `OnnxExportConfig::model_name` value the
/// caller passed (default: `"ferrotorch_model"`). `expected_op_type` is the
/// emitted ONNX op string (`"Add"` for the helpers used here).
fn assert_onnx_discriminating(bytes: &[u8], expected_model_name: &str, expected_op_type: &str) {
    // Existing tautology check — retained, not replaced.
    assert_eq!(
        bytes[0], 0x08,
        "first byte of ONNX ModelProto must be 0x08 (protobuf tag for ir_version)"
    );
    // ir_version value byte: `encode_model` writes `ir_version = 8`
    // (`onnx_export.rs:1017`). Encoded as varint, value 8 fits in one byte.
    assert_eq!(
        bytes[1], 0x08,
        "second byte must be 0x08 (varint value 8 for ir_version, per onnx_export.rs:1017)"
    );
    // Size floor: a real ONNX export of a 2-input, 1-op graph is hundreds of
    // bytes. A trivial stub (`vec![0x08]` or `vec![0x08; N]` for small N) fails
    // here. We pick 32 because that is far below any plausible real export
    // and far above any plausible magic-byte stub.
    assert!(
        bytes.len() > 32,
        "real ONNX export must exceed 32 bytes (stub guard); got {}",
        bytes.len()
    );
    // Default OnnxExportConfig sets model_name = "ferrotorch_model"
    // (`onnx_export.rs:67`). The string is embedded in the GraphProto.
    let mn = expected_model_name.as_bytes();
    assert!(
        bytes.windows(mn.len()).any(|w| w == mn),
        "ONNX bytes must contain configured model_name `{expected_model_name}`"
    );
    // Graph value names are `val_{id}` (`onnx_export.rs:738`). For a single
    // Add node fed by one input, val_0 is the input and val_1 is the output.
    assert!(
        bytes.windows(5).any(|w| w == b"val_0"),
        "ONNX bytes must contain input value name `val_0`"
    );
    assert!(
        bytes.windows(5).any(|w| w == b"val_1"),
        "ONNX bytes must contain output value name `val_1`"
    );
    // Op-type string for the emitted node. `IrOpKind::Add` maps to ONNX `Add`.
    let op = expected_op_type.as_bytes();
    assert!(
        bytes.windows(op.len()).any(|w| w == op),
        "ONNX bytes must contain op-type `{expected_op_type}`"
    );
    // Inline sabotage probe: a known-WRONG model_name string MUST NOT appear.
    // This confirms the `windows().any()` discrimination idiom actually
    // filters — if the substring matcher were broken (e.g. always-true),
    // this assertion would catch it.
    assert!(
        !bytes
            .windows(b"sabotage_marker".len())
            .any(|w| w == b"sabotage_marker"),
        "sabotage probe: bytes must NOT contain `sabotage_marker` \
         (confirms substring matcher actually discriminates)"
    );
}

/// ir_graph_to_onnx: returns Ok bytes; first byte is 0x08 (protobuf varint
/// field tag for IR version in ModelProto — wire type 0, field 1). Beyond
/// that magic-byte tautology, the bytes must contain the configured
/// `model_name`, the graph value names (`val_0`, `val_1`), and the emitted
/// op-type (`Add`); see `assert_onnx_discriminating`.
#[test]
fn onnx_ir_graph_to_onnx() {
    let graph = make_add_graph_for_onnx();
    let config = OnnxExportConfig::default();
    let bytes = ir_graph_to_onnx(&graph, &config, 1 /* ONNX_FLOAT */)
        .expect("ir_graph_to_onnx must succeed on valid graph");
    assert!(!bytes.is_empty(), "ONNX output must be non-empty");
    assert_onnx_discriminating(&bytes, &config.model_name, "Add");
}

/// export_ir_graph_to_onnx: writes ONNX bytes to a temp file. Discrimination
/// guarantees: see `assert_onnx_discriminating`.
#[test]
fn onnx_export_ir_graph_to_onnx() {
    let graph = make_add_graph_for_onnx();
    let config = OnnxExportConfig::default();
    let expected_model_name = config.model_name.clone();
    let dir = tempfile::tempdir().expect("tempdir must succeed");
    let path = dir.path().join("model.onnx");
    export_ir_graph_to_onnx(&graph, &path, config, 1 /* ONNX_FLOAT */)
        .expect("export_ir_graph_to_onnx must succeed");
    let written = std::fs::read(&path).expect("written ONNX file must be readable");
    assert!(!written.is_empty());
    assert_onnx_discriminating(&written, &expected_model_name, "Add");
}

/// export_onnx: trace-and-export via closure; writes valid ONNX to a file.
/// The closure `inputs[0].clone().add(&inputs[0])` produces a tracer-built
/// graph with a single ONNX `Add` op (`IrOpKind::Add` → ONNX op-type
/// `"Add"`). Tracer-built value IDs start at 0, so the input is `val_0` and
/// the Add output is `val_1`, matching `make_add_graph_for_onnx`.
#[test]
fn onnx_export_onnx() {
    use ferrotorch_core::TensorStorage;
    let dir = tempfile::tempdir().expect("tempdir must succeed");
    let path = dir.path().join("traced.onnx");
    // example input with requires_grad=true so the autograd tracer captures ops.
    let x_storage = TensorStorage::cpu(vec![1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0]);
    let x = Tensor::from_storage(x_storage, vec![2, 3], true).unwrap();
    let config = OnnxExportConfig::default();
    let expected_model_name = config.model_name.clone();
    export_onnx(
        |inputs: &[Tensor<f32>]| inputs[0].clone().add(&inputs[0]),
        &[x],
        &path,
        config,
    )
    .expect("export_onnx must succeed");
    let written = std::fs::read(&path).expect("written ONNX file must be readable");
    assert!(!written.is_empty());
    assert_onnx_discriminating(&written, &expected_model_name, "Add");
}

/// export_from_program: build an ExportedProgram from an IrGraph and export.
/// Discrimination guarantees: see `assert_onnx_discriminating`.
#[test]
fn onnx_export_from_program() {
    use ferrotorch_jit::export::{ExportedProgram, InputSpec};
    let graph = make_add_graph_for_onnx();
    let program = ExportedProgram {
        graph,
        state_dict: std::collections::HashMap::new(),
        input_shapes: vec![vec![2, 3]],
        input_specs: vec![InputSpec::all_static(&[2, 3])],
        output_shape: vec![2, 3],
    };
    let dir = tempfile::tempdir().expect("tempdir must succeed");
    let path = dir.path().join("program.onnx");
    let config = OnnxExportConfig::default();
    let expected_model_name = config.model_name.clone();
    export_from_program(&program, &path, config).expect("export_from_program must succeed");
    let written = std::fs::read(&path).expect("written ONNX file must be readable");
    assert!(!written.is_empty());
    assert_onnx_discriminating(&written, &expected_model_name, "Add");
}

/// OnnxExportConfig: default construction and public field access.
#[test]
fn onnx_export_config_struct() {
    let cfg = OnnxExportConfig::default();
    // opset_version is a pub field
    assert_eq!(cfg.opset_version, 17);
    // model_name is a pub String field
    assert!(!cfg.model_name.is_empty());
    // dynamic_axes is a pub HashMap field
    assert!(cfg.dynamic_axes.is_empty());

    // Mutate through fields (verifies they are publicly writable).
    let mut cfg2 = OnnxExportConfig::default();
    cfg2.opset_version = 18;
    cfg2.model_name = "my_model".to_string();
    assert_eq!(cfg2.opset_version, 18);
    assert_eq!(cfg2.model_name, "my_model");
}

// cascade_skip entries for #850 (mmap), #851 (sharded), and #852 (async)
// have been removed. Full integration tests now live in:
//   - conformance_serialize_mmap.rs    (#850)
//   - conformance_serialize_sharded.rs (#851)
//   - conformance_serialize_async.rs   (#852)

// ---------------------------------------------------------------------------
// Surface-anchor block
//
// The Layer 4 gate scans test sources for `Type::method` strings.
// Items exercised above via method-call syntax need their coverage key here
// so the gate can find them without false-positive failures.
// ---------------------------------------------------------------------------

/// Explicit surface anchors for items referenced via variable calls or
/// type/re-export references that the gate's substring search may miss.
#[test]
fn surface_anchors() {
    // These string literals are scanned by the coverage gate.
    // They name items exercised in the tests above.
    let _ = [
        "save_safetensors",
        "load_safetensors",
        "save_pytorch",
        "load_pytorch_state_dict",
        "parse_pickle",
        "validate_checkpoint",
        "save_state_dict",
        "load_state_dict",
        "save_checkpoint",
        "load_checkpoint",
        "TrainingCheckpoint::new",
        "PickleValue",
        // GGUF items now under live coverage (#848):
        "GgufFile",
        "GgufMetadata",
        "GgufTensorInfo",
        "GgufValue",
        "GgmlType",
        "dequantize_gguf_tensor",
        "load_gguf",
        "load_gguf_mmap",
        "load_gguf_state_dict",
        "load_gguf_state_dict_mmap",
        "parse_gguf_bytes",
        // ONNX items now under live coverage (#849):
        "OnnxExportConfig",
        "export_onnx",
        "export_from_program",
        "export_ir_graph_to_onnx",
        "ir_graph_to_onnx",
        //
        // Items now covered by dedicated conformance files (no longer excluded):
        // "load_pytorch_state_dict_mmap" — conformance_serialize_mmap.rs (#850)
        // "load_safetensors_mmap"        — conformance_serialize_mmap.rs (#850)
        // "load_safetensors_sharded_mmap" — conformance_serialize_mmap.rs (#850)
        // "AsyncCheckpointer"            — conformance_serialize_async.rs (#852)
        // "ShardProgress"                — conformance_serialize_sharded.rs (#851)
        // "load_safetensors_sharded"     — conformance_serialize_sharded.rs (#851)
        // "load_safetensors_sharded_filtered" — conformance_serialize_sharded.rs (#851)
        // "load_safetensors_sharded_with_progress" — conformance_serialize_sharded.rs (#851)
        // "load_safetensors_auto"        — conformance_serialize_sharded.rs (#851)
    ];
}
