//! Conformance tests — `ferrotorch_ml::adapter` module.
//!
//! Tracking issue: <https://github.com/dollspace-gay/ferrotorch/issues/840>.
//!
//! Reference: scikit-learn 1.5.2 (adapter tests are numeric-identity; no
//! sklearn computation is involved — the reference is round-trip equality).
//!
//! Tests verify that the six public adapter functions preserve element values
//! through the `Tensor ↔ ndarray` boundary. Fixtures come from
//! `tests/conformance/fixtures.json` (generated by
//! `scripts/regenerate_ml_fixtures.py`).

use std::path::PathBuf;

use ferrotorch_core::{Tensor, TensorStorage};
use ferrotorch_ml::adapter::{
    array1_to_tensor, array1_usize_to_tensor, array2_to_tensor, tensor_to_array1,
    tensor_to_array1_usize, tensor_to_array2,
};
use ndarray::{Array1, Array2};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    metadata: serde_json::Value,
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    op: String,
    #[serde(default)]
    input_flat: Option<Vec<f64>>,
    #[serde(default)]
    shape: Option<Vec<usize>>,
    #[serde(default)]
    expected_flat: Option<Vec<f64>>,
    #[serde(default)]
    input_labels: Option<Vec<usize>>,
    #[serde(default)]
    expected_labels: Option<Vec<usize>>,
    #[serde(flatten)]
    _rest: serde_json::Value,
}

fn load_fixtures() -> FixtureFile {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json");
    let bytes = std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "read {} failed: {e}. Run python3 scripts/regenerate_ml_fixtures.py first.",
            p.display()
        )
    });
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", p.display()))
}

fn find(file: &FixtureFile, op: &str) -> Fixture {
    file.fixtures
        .iter()
        .find(|f| f.op == op)
        .unwrap_or_else(|| panic!("no fixture with op={op:?}"))
        .clone()
}

// Allow clone for test convenience.
impl Clone for Fixture {
    fn clone(&self) -> Self {
        Self {
            op: self.op.clone(),
            input_flat: self.input_flat.clone(),
            shape: self.shape.clone(),
            expected_flat: self.expected_flat.clone(),
            input_labels: self.input_labels.clone(),
            expected_labels: self.expected_labels.clone(),
            _rest: self._rest.clone(),
        }
    }
}

// ---------------------------------------------------------------------------
// Tolerance helpers
// ---------------------------------------------------------------------------

fn assert_close_f64(actual: &[f64], expected: &[f64], tol: f64, label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: length mismatch");
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (a - e).abs();
        assert!(
            diff <= tol,
            "{label}: index {i} diff {diff:.3e} > tol {tol:.3e} (actual={a}, expected={e})"
        );
    }
}

// ---------------------------------------------------------------------------
// tensor_to_array1 — 1-D Tensor<f64> → Array1<f64>
// ---------------------------------------------------------------------------

#[test]
fn tensor_to_array1_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_tensor_to_array1");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let shape = f.shape.as_ref().expect("shape");
    let expected_flat = f.expected_flat.as_ref().expect("expected_flat");

    let t = Tensor::from_storage(
        TensorStorage::cpu(input_flat.clone()),
        shape.clone(),
        false,
    )
    .expect("build tensor");
    let arr = tensor_to_array1(&t).expect("tensor_to_array1");

    assert_eq!(arr.len(), expected_flat.len(), "tensor_to_array1: length");
    let actual: Vec<f64> = arr.to_vec();
    assert_close_f64(&actual, expected_flat, 1e-15, "tensor_to_array1");
}

// ---------------------------------------------------------------------------
// array1_to_tensor — Array1<f64> → Tensor<f64>
// ---------------------------------------------------------------------------

#[test]
fn array1_to_tensor_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_array1_to_tensor");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let expected_flat = f.expected_flat.as_ref().expect("expected_flat");

    let arr = Array1::from(input_flat.clone());
    let t = array1_to_tensor(arr).expect("array1_to_tensor");

    assert_eq!(t.shape(), &[input_flat.len()], "shape");
    let actual = t.data().expect("data").to_vec();
    assert_close_f64(&actual, expected_flat, 1e-15, "array1_to_tensor");
}

// ---------------------------------------------------------------------------
// tensor_to_array2 — 2-D Tensor<f64> → Array2<f64>
// ---------------------------------------------------------------------------

#[test]
fn tensor_to_array2_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_tensor_to_array2");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let shape = f.shape.as_ref().expect("shape");
    let expected_flat = f.expected_flat.as_ref().expect("expected_flat");

    let t = Tensor::from_storage(
        TensorStorage::cpu(input_flat.clone()),
        shape.clone(),
        false,
    )
    .expect("build tensor");
    let arr = tensor_to_array2(&t).expect("tensor_to_array2");

    assert_eq!(arr.shape(), shape.as_slice(), "array shape");
    let actual: Vec<f64> = arr.iter().copied().collect();
    assert_close_f64(&actual, expected_flat, 1e-15, "tensor_to_array2");
}

// ---------------------------------------------------------------------------
// array2_to_tensor — Array2<f64> → Tensor<f64>
// ---------------------------------------------------------------------------

#[test]
fn array2_to_tensor_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_array2_to_tensor");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let shape = f.shape.as_ref().expect("shape");
    let expected_flat = f.expected_flat.as_ref().expect("expected_flat");

    let arr = Array2::from_shape_vec((shape[0], shape[1]), input_flat.clone())
        .expect("Array2::from_shape_vec");
    let t = array2_to_tensor(arr).expect("array2_to_tensor");

    assert_eq!(t.shape(), shape.as_slice(), "tensor shape");
    let actual = t.data().expect("data").to_vec();
    assert_close_f64(&actual, expected_flat, 1e-15, "array2_to_tensor");
}

// ---------------------------------------------------------------------------
// array1_usize_to_tensor — Array1<usize> → Tensor<f64>
// ---------------------------------------------------------------------------

#[test]
fn array1_usize_to_tensor_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_array1_usize_to_tensor");
    let input_labels = f.input_labels.as_ref().expect("input_labels");
    let expected_flat = f.expected_flat.as_ref().expect("expected_flat");

    let arr = Array1::from(input_labels.clone());
    let t: Tensor<f64> = array1_usize_to_tensor(arr).expect("array1_usize_to_tensor");
    let actual = t.data().expect("data").to_vec();
    assert_close_f64(&actual, expected_flat, 1e-15, "array1_usize_to_tensor");
}

// ---------------------------------------------------------------------------
// tensor_to_array1_usize — Tensor<f64> → Array1<usize>
// ---------------------------------------------------------------------------

#[test]
fn tensor_to_array1_usize_matches_reference() {
    let file = load_fixtures();
    let f = find(&file, "adapter_tensor_to_array1_usize");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let expected_labels = f.expected_labels.as_ref().expect("expected_labels");

    let t = Tensor::from_storage(
        TensorStorage::cpu(input_flat.clone()),
        vec![input_flat.len()],
        false,
    )
    .expect("build tensor");
    let arr = tensor_to_array1_usize(&t).expect("tensor_to_array1_usize");
    let actual: Vec<usize> = arr.to_vec();
    assert_eq!(&actual, expected_labels, "tensor_to_array1_usize labels");
}

// ---------------------------------------------------------------------------
// Error-path checks (no fixture needed — pure structural)
// ---------------------------------------------------------------------------

#[test]
fn tensor_to_array1_rejects_2d_input() {
    let t = Tensor::from_storage(TensorStorage::cpu(vec![1.0_f64; 6]), vec![2, 3], false)
        .expect("build tensor");
    assert!(
        tensor_to_array1(&t).is_err(),
        "tensor_to_array1 must reject a 2-D tensor"
    );
}

#[test]
fn tensor_to_array2_rejects_1d_input() {
    let t = Tensor::from_storage(TensorStorage::cpu(vec![1.0_f64; 4]), vec![4], false)
        .expect("build tensor");
    assert!(
        tensor_to_array2(&t).is_err(),
        "tensor_to_array2 must reject a 1-D tensor"
    );
}

#[test]
fn tensor_to_array1_usize_rejects_negative() {
    let t = Tensor::from_storage(
        TensorStorage::cpu(vec![0.0_f64, 1.0, -1.0]),
        vec![3],
        false,
    )
    .expect("build tensor");
    assert!(
        tensor_to_array1_usize(&t).is_err(),
        "tensor_to_array1_usize must reject negative values"
    );
}

#[test]
fn tensor_to_array1_usize_rejects_nan() {
    let t = Tensor::from_storage(
        TensorStorage::cpu(vec![0.0_f64, f64::NAN]),
        vec![2],
        false,
    )
    .expect("build tensor");
    assert!(
        tensor_to_array1_usize(&t).is_err(),
        "tensor_to_array1_usize must reject NaN"
    );
}

// ---------------------------------------------------------------------------
// Round-trip identity: tensor → array → tensor must preserve all values.
// ---------------------------------------------------------------------------

#[test]
fn adapter_1d_round_trip_identity() {
    let file = load_fixtures();
    let f = find(&file, "adapter_tensor_to_array1");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let shape = f.shape.as_ref().expect("shape");

    let t_in = Tensor::from_storage(
        TensorStorage::cpu(input_flat.clone()),
        shape.clone(),
        false,
    )
    .expect("build tensor");
    let arr = tensor_to_array1(&t_in).expect("to array");
    let t_out = array1_to_tensor(arr).expect("back to tensor");

    let actual = t_out.data().expect("data").to_vec();
    assert_close_f64(&actual, input_flat, 1e-15, "1d round-trip");
}

#[test]
fn adapter_2d_round_trip_identity() {
    let file = load_fixtures();
    let f = find(&file, "adapter_tensor_to_array2");
    let input_flat = f.input_flat.as_ref().expect("input_flat");
    let shape = f.shape.as_ref().expect("shape");

    let t_in = Tensor::from_storage(
        TensorStorage::cpu(input_flat.clone()),
        shape.clone(),
        false,
    )
    .expect("build tensor");
    let arr = tensor_to_array2(&t_in).expect("to array2");
    let t_out = array2_to_tensor(arr).expect("back to tensor");

    let actual = t_out.data().expect("data").to_vec();
    assert_close_f64(&actual, input_flat, 1e-15, "2d round-trip");
}
