//! Conformance tests — `ferrotorch_ml::metrics` module.
//!
//! Tracking issue: <https://github.com/dollspace-gay/ferrotorch/issues/840>.
//!
//! Reference library: scikit-learn 1.5.2 (pinned).
//! Fixtures generated by `scripts/regenerate_ml_fixtures.py`.
//!
//! Organisation:
//! - Regression metrics (r2, mse, rmse, mae, mape, medae, max_error, evs)
//! - Classification metrics (accuracy, precision, recall, f1, roc_auc,
//!   log_loss, confusion_matrix, hamming, balanced_acc, mcc, kappa,
//!   brier, d2_brier, top_k, zero_one, avg_precision)
//! - Ranking metrics (dcg, ndcg, coverage_error, lrap, label_ranking_loss)
//! - Clustering metrics (ari, ami, nmi, homogeneity, completeness,
//!   v_measure, fowlkes_mallows, silhouette, davies_bouldin,
//!   calinski_harabasz)
//!
//! Divergences → `cascade_skip!()` with the filed tracking issue.

use std::path::PathBuf;

use ferrotorch_core::{Tensor, TensorStorage};
use ferrotorch_ml::metrics::{
    Average, accuracy_score, adjusted_mutual_info_score, adjusted_rand_score,
    average_precision_score, balanced_accuracy_score, brier_score_loss, calinski_harabasz_score,
    cohen_kappa_score, completeness_score, confusion_matrix, coverage_error, d2_brier_score,
    davies_bouldin_score, dcg_score, explained_variance_score, f1_score, fowlkes_mallows_score,
    hamming_loss, homogeneity_score, label_ranking_average_precision_score, label_ranking_loss,
    log_loss, matthews_corrcoef, max_error, mean_absolute_error, mean_absolute_percentage_error,
    mean_squared_error, median_absolute_error, ndcg_score, normalized_mutual_info_score,
    precision_score, r2_score, recall_score, roc_auc_score, root_mean_squared_error,
    silhouette_score, top_k_accuracy_score, v_measure_score, zero_one_loss,
};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Clone)]
struct FixtureFile {
    #[allow(dead_code, reason = "metadata kept for diagnostics")]
    metadata: serde_json::Value,
    fixtures: Vec<Fixture>,
}

// All array-typed fields use `serde_json::Value` to handle both 1-D
// (`[1.0, 2.0, ...]`) and 2-D (`[[...], [...]]`) JSON arrays that appear
// across regression / classification / ranking / clustering fixtures.
// Concrete extractions are done by the `as_f64_vec` / `as_2d_*` helpers below.
#[derive(Debug, Deserialize, Clone)]
struct Fixture {
    op: String,
    // Array fields stored as Value to tolerate 1-D and 2-D shapes.
    #[serde(default)]
    y_true: Option<serde_json::Value>,
    #[serde(default)]
    y_pred: Option<serde_json::Value>,
    #[serde(default)]
    y_score: Option<serde_json::Value>,
    #[serde(default)]
    y_prob: Option<serde_json::Value>,
    #[serde(default)]
    labels_true: Option<serde_json::Value>,
    #[serde(default)]
    labels_pred: Option<serde_json::Value>,
    #[serde(default)]
    x: Option<serde_json::Value>,
    #[serde(default)]
    labels: Option<serde_json::Value>,
    // `expected` is f64 for most ops but a nested array for confusion_matrix.
    // Store as Value and extract lazily via `expected_f64` / `expected_cm` helpers.
    #[serde(default)]
    expected: Option<serde_json::Value>,
    #[serde(default)]
    tol: Option<f64>,
    #[serde(flatten)]
    _rest: serde_json::Value,
}

/// Extract `expected` as f64. Panics if absent or not a JSON number.
fn expected_f64(f: &Fixture) -> f64 {
    f.expected
        .as_ref()
        .expect("expected field missing")
        .as_f64()
        .expect("expected field is not a number")
}

/// Extract `expected` as `Vec<Vec<usize>>` (for confusion_matrix).
fn expected_cm(f: &Fixture) -> Vec<Vec<usize>> {
    serde_json::from_value(f.expected.as_ref().expect("expected field missing").clone())
        .expect("expected field is not a Vec<Vec<usize>>")
}

/// Extract a flat `Vec<f64>` from a 1-D JSON array field.
fn as_f64_vec(v: &serde_json::Value, label: &str) -> Vec<f64> {
    v.as_array()
        .unwrap_or_else(|| panic!("{label}: expected JSON array"))
        .iter()
        .map(|x| {
            x.as_f64()
                .unwrap_or_else(|| panic!("{label}: expected f64 element, got {x}"))
        })
        .collect()
}

fn load_fixtures() -> FixtureFile {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json");
    let bytes = std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "read {} failed: {e}. Run python3 scripts/regenerate_ml_fixtures.py first.",
            p.display()
        )
    });
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", p.display()))
}

fn find(file: &FixtureFile, op: &str) -> Fixture {
    file.fixtures
        .iter()
        .find(|f| f.op == op)
        .unwrap_or_else(|| panic!("no fixture with op={op:?}"))
        .clone()
}

// ---------------------------------------------------------------------------
// Helper: build a 1-D Tensor<f64> from a slice
// ---------------------------------------------------------------------------

fn tensor1d(data: &[f64]) -> Tensor<f64> {
    Tensor::from_storage(TensorStorage::cpu(data.to_vec()), vec![data.len()], false)
        .expect("build 1-D tensor")
}

fn tensor2d(data: Vec<f64>, rows: usize, cols: usize) -> Tensor<f64> {
    Tensor::from_storage(TensorStorage::cpu(data), vec![rows, cols], false)
        .expect("build 2-D tensor")
}

// ---------------------------------------------------------------------------
// Tolerance helpers
// ---------------------------------------------------------------------------

fn check_f64(actual: f64, expected: f64, tol: f64, label: &str) {
    let diff = (actual - expected).abs();
    assert!(
        diff <= tol,
        "{label}: actual={actual:.8e}, expected={expected:.8e}, diff={diff:.3e} > tol={tol:.3e}"
    );
}

// ---------------------------------------------------------------------------
// Helper: parse 1-D or 2-D JSON value into a flat Vec<f64>
// ---------------------------------------------------------------------------

fn parse_score_1d(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .expect("score array")
        .iter()
        .map(|x| x.as_f64().expect("f64"))
        .collect()
}

fn parse_score_2d(v: &serde_json::Value) -> (Vec<f64>, usize, usize) {
    let rows_v = v.as_array().expect("outer array");
    let rows = rows_v.len();
    let mut flat = Vec::new();
    let mut cols = 0;
    for row in rows_v {
        let row_v = row.as_array().expect("inner array");
        cols = row_v.len();
        for x in row_v {
            flat.push(x.as_f64().expect("f64"));
        }
    }
    (flat, rows, cols)
}

// ============================================================================
// REGRESSION METRICS
// ============================================================================

#[test]
fn r2_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "r2_score");
    let yt = tensor1d(&as_f64_vec(f.y_true.as_ref().expect("y_true"), "r2/y_true"));
    let yp = tensor1d(&as_f64_vec(f.y_pred.as_ref().expect("y_pred"), "r2/y_pred"));
    let actual = r2_score(&yt, &yp).expect("r2_score");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "r2_score");
}

#[test]
fn r2_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "r2_score_perfect");
    let y = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "r2_perfect/y_true",
    ));
    let actual = r2_score(&y, &y).expect("r2_score_perfect");
    check_f64(actual, 1.0, 1e-12, "r2_score_perfect");
}

#[test]
fn r2_score_constant_baseline_is_zero() {
    let file = load_fixtures();
    let f = find(&file, "r2_score_constant_baseline");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "r2_const/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "r2_const/y_pred",
    ));
    let actual = r2_score(&yt, &yp).expect("r2_constant");
    check_f64(actual, 0.0, 1e-12, "r2_score_constant_baseline");
}

#[test]
fn mean_squared_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "mean_squared_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mse/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "mse/y_pred",
    ));
    let actual = mean_squared_error(&yt, &yp).expect("mse");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "mse");
}

#[test]
fn mean_squared_error_perfect_is_zero() {
    let file = load_fixtures();
    let f = find(&file, "mean_squared_error_perfect");
    let y = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mse_perfect/y_true",
    ));
    let actual = mean_squared_error(&y, &y).expect("mse_perfect");
    check_f64(actual, 0.0, 1e-12, "mse_perfect");
}

#[test]
fn root_mean_squared_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "root_mean_squared_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "rmse/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "rmse/y_pred",
    ));
    let actual = root_mean_squared_error(&yt, &yp).expect("rmse");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "rmse");
}

#[test]
fn root_mean_squared_error_perfect_is_zero() {
    let file = load_fixtures();
    let f = find(&file, "root_mean_squared_error_perfect");
    let y = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "rmse_perfect/y_true",
    ));
    let actual = root_mean_squared_error(&y, &y).expect("rmse_perfect");
    check_f64(actual, 0.0, 1e-12, "rmse_perfect");
}

#[test]
fn mean_absolute_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "mean_absolute_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mae/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "mae/y_pred",
    ));
    let actual = mean_absolute_error(&yt, &yp).expect("mae");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "mae");
}

#[test]
fn mean_absolute_error_perfect_is_zero() {
    let file = load_fixtures();
    let f = find(&file, "mean_absolute_error_perfect");
    let y = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mae_perfect/y_true",
    ));
    let actual = mean_absolute_error(&y, &y).expect("mae_perfect");
    check_f64(actual, 0.0, 1e-12, "mae_perfect");
}

// #841 fixed: ferrolearn returns MAPE as percentage; the wrapper now divides
// by 100 to produce the sklearn-compatible fraction.
#[test]
fn mean_absolute_percentage_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "mean_absolute_percentage_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mape/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "mape/y_pred",
    ));
    let actual = mean_absolute_percentage_error(&yt, &yp).expect("mape");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "mape");
}

#[test]
fn median_absolute_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "median_absolute_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "medae/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "medae/y_pred",
    ));
    let actual = median_absolute_error(&yt, &yp).expect("medae");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "medae");
}

#[test]
fn max_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "max_error");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "max_error/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "max_error/y_pred",
    ));
    let actual = max_error(&yt, &yp).expect("max_error");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "max_error");
}

#[test]
fn explained_variance_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "explained_variance_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "evs/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "evs/y_pred",
    ));
    let actual = explained_variance_score(&yt, &yp).expect("evs");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "evs");
}

// ============================================================================
// CLASSIFICATION METRICS
// ============================================================================

#[test]
fn accuracy_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "accuracy_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "acc/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "acc/y_pred",
    ));
    let actual = accuracy_score(&yt, &yp).expect("accuracy");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "accuracy");
}

#[test]
fn precision_score_binary_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "precision_score_binary");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "prec_bin/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "prec_bin/y_pred",
    ));
    let actual = precision_score(&yt, &yp, Average::Binary).expect("precision_binary");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "precision_binary",
    );
}

#[test]
fn recall_score_binary_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "recall_score_binary");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "rec_bin/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "rec_bin/y_pred",
    ));
    let actual = recall_score(&yt, &yp, Average::Binary).expect("recall_binary");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "recall_binary",
    );
}

#[test]
fn f1_score_binary_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "f1_score_binary");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "f1_bin/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "f1_bin/y_pred",
    ));
    let actual = f1_score(&yt, &yp, Average::Binary).expect("f1_binary");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "f1_binary",
    );
}

#[test]
fn precision_score_macro_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "precision_score_macro");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "prec_mac/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "prec_mac/y_pred",
    ));
    let actual = precision_score(&yt, &yp, Average::Macro).expect("precision_macro");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "precision_macro",
    );
}

#[test]
fn recall_score_macro_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "recall_score_macro");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "rec_mac/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "rec_mac/y_pred",
    ));
    let actual = recall_score(&yt, &yp, Average::Macro).expect("recall_macro");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "recall_macro",
    );
}

#[test]
fn f1_score_macro_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "f1_score_macro");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "f1_mac/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "f1_mac/y_pred",
    ));
    let actual = f1_score(&yt, &yp, Average::Macro).expect("f1_macro");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "f1_macro");
}

#[test]
fn roc_auc_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "roc_auc_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "roc_auc/y_true",
    ));
    let ys_vec = parse_score_1d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor1d(&ys_vec);
    let actual = roc_auc_score(&yt, &ys).expect("roc_auc");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "roc_auc");
}

#[test]
fn log_loss_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "log_loss");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "log_loss/y_true",
    ));
    let (flat, rows, cols) = parse_score_2d(f.y_prob.as_ref().expect("y_prob"));
    let yp = tensor2d(flat, rows, cols);
    let actual = log_loss(&yt, &yp).expect("log_loss");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "log_loss");
}

#[test]
fn confusion_matrix_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "confusion_matrix");
    let yt = tensor1d(&as_f64_vec(f.y_true.as_ref().expect("y_true"), "cm/y_true"));
    let yp = tensor1d(&as_f64_vec(f.y_pred.as_ref().expect("y_pred"), "cm/y_pred"));
    let actual = confusion_matrix(&yt, &yp).expect("confusion_matrix");
    let expected = expected_cm(&f);
    assert_eq!(actual, expected, "confusion_matrix");
}

#[test]
fn hamming_loss_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "hamming_loss");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "hamming/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "hamming/y_pred",
    ));
    let actual = hamming_loss(&yt, &yp).expect("hamming_loss");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "hamming_loss",
    );
}

#[test]
fn balanced_accuracy_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "balanced_accuracy_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "bal_acc/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "bal_acc/y_pred",
    ));
    let actual = balanced_accuracy_score(&yt, &yp, false).expect("balanced_accuracy");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "balanced_accuracy",
    );
}

#[test]
fn matthews_corrcoef_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "matthews_corrcoef");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "mcc/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "mcc/y_pred",
    ));
    let actual = matthews_corrcoef(&yt, &yp).expect("mcc");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "mcc");
}

#[test]
fn cohen_kappa_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "cohen_kappa_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "kappa/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "kappa/y_pred",
    ));
    let actual = cohen_kappa_score(&yt, &yp).expect("kappa");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "kappa");
}

#[test]
fn brier_score_loss_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "brier_score_loss");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "brier/y_true",
    ));
    let yp_vec = parse_score_1d(f.y_prob.as_ref().expect("y_prob"));
    let yp = tensor1d(&yp_vec);
    let actual = brier_score_loss(&yt, &yp).expect("brier");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "brier");
}

#[test]
fn d2_brier_score_perfect_is_one() {
    // d2_brier_score: perfect predictions → 1.0
    let y_true = tensor1d(&[0.0, 1.0, 1.0, 0.0]);
    let y_prob = tensor1d(&[0.0, 1.0, 1.0, 0.0]);
    let actual = d2_brier_score(&y_true, &y_prob).expect("d2_brier_perfect");
    check_f64(actual, 1.0, 1e-12, "d2_brier_perfect");
}

#[test]
fn top_k_accuracy_score_k1_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "top_k_accuracy_score_k1");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "topk1/y_true",
    ));
    let (flat, rows, cols) = parse_score_2d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor2d(flat, rows, cols);
    let actual = top_k_accuracy_score(&yt, &ys, 1).expect("top_k_k1");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "top_k_k1");
}

#[test]
fn top_k_accuracy_score_k2_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "top_k_accuracy_score_k2");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "topk2/y_true",
    ));
    let (flat, rows, cols) = parse_score_2d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor2d(flat, rows, cols);
    let actual = top_k_accuracy_score(&yt, &ys, 2).expect("top_k_k2");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-12), "top_k_k2");
}

#[test]
fn zero_one_loss_normalized_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "zero_one_loss_normalized");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "zo_norm/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "zo_norm/y_pred",
    ));
    let actual = zero_one_loss(&yt, &yp, true).expect("zero_one_normalized");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "zero_one_normalized",
    );
}

#[test]
fn zero_one_loss_count_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "zero_one_loss_count");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "zo_cnt/y_true",
    ));
    let yp = tensor1d(&as_f64_vec(
        f.y_pred.as_ref().expect("y_pred"),
        "zo_cnt/y_pred",
    ));
    let actual = zero_one_loss(&yt, &yp, false).expect("zero_one_count");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "zero_one_count",
    );
}

#[test]
fn average_precision_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "average_precision_score");
    let yt = tensor1d(&as_f64_vec(f.y_true.as_ref().expect("y_true"), "ap/y_true"));
    let ys_vec = parse_score_1d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor1d(&ys_vec);
    let actual = average_precision_score(&yt, &ys).expect("avg_precision");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "avg_precision",
    );
}

// ============================================================================
// RANKING METRICS
// ============================================================================

#[test]
fn ndcg_score_perfect_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "ndcg_score_perfect");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "ndcg_perf/y_true",
    ));
    let ys = tensor1d(&parse_score_1d(f.y_score.as_ref().expect("y_score")));
    let actual = ndcg_score(&yt, &ys, None).expect("ndcg_perfect");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "ndcg_perfect",
    );
}

#[test]
fn ndcg_score_imperfect_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "ndcg_score_imperfect");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "ndcg_imp/y_true",
    ));
    let ys = tensor1d(&parse_score_1d(f.y_score.as_ref().expect("y_score")));
    let actual = ndcg_score(&yt, &ys, None).expect("ndcg_imperfect");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "ndcg_imperfect",
    );
}

#[test]
fn dcg_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "dcg_score");
    let yt = tensor1d(&as_f64_vec(
        f.y_true.as_ref().expect("y_true"),
        "dcg/y_true",
    ));
    let ys = tensor1d(&parse_score_1d(f.y_score.as_ref().expect("y_score")));
    let actual = dcg_score(&yt, &ys, None).expect("dcg");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "dcg");
}

#[test]
fn label_ranking_average_precision_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "label_ranking_average_precision_score");
    // y_true and y_score are 2-D nested arrays.
    let (yt_flat, yt_rows, yt_cols) = parse_score_2d(f.y_true.as_ref().expect("y_true"));
    let yt = tensor2d(yt_flat, yt_rows, yt_cols);
    let (ys_flat, ys_rows, ys_cols) = parse_score_2d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor2d(ys_flat, ys_rows, ys_cols);
    let actual = label_ranking_average_precision_score(&yt, &ys).expect("lrap");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "lrap");
}

#[test]
fn label_ranking_loss_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "label_ranking_loss");
    let (yt_flat, yt_rows, yt_cols) = parse_score_2d(f.y_true.as_ref().expect("y_true"));
    let yt = tensor2d(yt_flat, yt_rows, yt_cols);
    let (ys_flat, ys_rows, ys_cols) = parse_score_2d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor2d(ys_flat, ys_rows, ys_cols);
    let actual = label_ranking_loss(&yt, &ys).expect("label_ranking_loss");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "label_ranking_loss",
    );
}

#[test]
fn coverage_error_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "coverage_error");
    let (yt_flat, yt_rows, yt_cols) = parse_score_2d(f.y_true.as_ref().expect("y_true"));
    let yt = tensor2d(yt_flat, yt_rows, yt_cols);
    let (ys_flat, ys_rows, ys_cols) = parse_score_2d(f.y_score.as_ref().expect("y_score"));
    let ys = tensor2d(ys_flat, ys_rows, ys_cols);
    let actual = coverage_error(&yt, &ys).expect("coverage_error");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "coverage_error",
    );
}

// ============================================================================
// CLUSTERING METRICS
// ============================================================================

#[test]
fn adjusted_rand_score_perfect_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "adjusted_rand_score_perfect");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "ari_perf/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "ari_perf/lp",
    ));
    let actual = adjusted_rand_score(&lt, &lp).expect("ari_perfect");
    check_f64(actual, 1.0, 1e-12, "ari_perfect");
}

#[test]
fn adjusted_rand_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "adjusted_rand_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "ari_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "ari_mix/lp",
    ));
    let actual = adjusted_rand_score(&lt, &lp).expect("ari_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "ari_mixed",
    );
}

#[test]
fn adjusted_mutual_info_score_perfect_is_one() {
    // Renamed from `adjusted_mutual_info_score_matches_sklearn` for cluster
    // naming consistency (Phase 2 audit-fix, #1064). Test body unchanged: the
    // fixture op `adjusted_mutual_info_score` records labels_true == labels_pred,
    // and sklearn's AMI on identical labels evaluates (very near) 1.0 modulo
    // baseline correction. Pair tested by `adjusted_mutual_info_score_mixed_matches_sklearn`.
    let file = load_fixtures();
    let f = find(&file, "adjusted_mutual_info_score");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "ami/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "ami/lp",
    ));
    let actual = adjusted_mutual_info_score(&lt, &lp).expect("ami");
    check_f64(actual, expected_f64(&f), f.tol.unwrap_or(1e-9), "ami");
}

#[test]
fn normalized_mutual_info_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "normalized_mutual_info_score");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "nmi/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "nmi/lp",
    ));
    let actual = normalized_mutual_info_score(&lt, &lp).expect("nmi");
    check_f64(actual, 1.0, 1e-9, "nmi_perfect");
}

#[test]
fn homogeneity_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "homogeneity_score_perfect");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "hom/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "hom/lp",
    ));
    let actual = homogeneity_score(&lt, &lp).expect("homogeneity");
    check_f64(actual, 1.0, 1e-9, "homogeneity_perfect");
}

#[test]
fn completeness_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "completeness_score_perfect");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "comp/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "comp/lp",
    ));
    let actual = completeness_score(&lt, &lp).expect("completeness");
    check_f64(actual, 1.0, 1e-9, "completeness_perfect");
}

#[test]
fn v_measure_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "v_measure_score_perfect");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "vmeas/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "vmeas/lp",
    ));
    let actual = v_measure_score(&lt, &lp).expect("v_measure");
    check_f64(actual, 1.0, 1e-9, "v_measure_perfect");
}

#[test]
fn fowlkes_mallows_score_perfect_is_one() {
    let file = load_fixtures();
    let f = find(&file, "fowlkes_mallows_score_perfect");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "fm/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "fm/lp",
    ));
    let actual = fowlkes_mallows_score(&lt, &lp).expect("fm");
    check_f64(actual, 1.0, 1e-12, "fm_perfect");
}

// ---------------------------------------------------------------------------
// Mixed-label clustering tests — Phase 2 audit-fix (closes #1063-#1068).
//
// The *_perfect_is_one tests above pass against `labels_true == labels_pred`
// fixtures asserting `expected = 1.0`. A stub returning 1.0 for identical
// inputs trivially passes them. The tests below load sklearn-derived expected
// values from non-trivial label pairs (3 true clusters merged into 2 predicted
// clusters), forcing the implementation to actually compute the metric.
// ---------------------------------------------------------------------------

#[test]
fn normalized_mutual_info_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "normalized_mutual_info_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "nmi_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "nmi_mix/lp",
    ));
    let actual = normalized_mutual_info_score(&lt, &lp).expect("nmi_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "nmi_mixed",
    );
}

#[test]
#[ignore = "#1073 ferrolearn-metrics AMI diverges from sklearn (0.225 vs 0.299 on mixed labels); #[ignore] until ferrolearn fix lands"]
fn adjusted_mutual_info_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "adjusted_mutual_info_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "ami_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "ami_mix/lp",
    ));
    let actual = adjusted_mutual_info_score(&lt, &lp).expect("ami_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "ami_mixed",
    );
}

#[test]
fn homogeneity_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "homogeneity_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "hom_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "hom_mix/lp",
    ));
    let actual = homogeneity_score(&lt, &lp).expect("homogeneity_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "homogeneity_mixed",
    );
}

#[test]
fn completeness_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "completeness_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "comp_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "comp_mix/lp",
    ));
    let actual = completeness_score(&lt, &lp).expect("completeness_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "completeness_mixed",
    );
}

#[test]
fn v_measure_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "v_measure_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "vmeas_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "vmeas_mix/lp",
    ));
    let actual = v_measure_score(&lt, &lp).expect("v_measure_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "v_measure_mixed",
    );
}

#[test]
fn fowlkes_mallows_score_mixed_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "fowlkes_mallows_score_mixed");
    let lt = tensor1d(&as_f64_vec(
        f.labels_true.as_ref().expect("labels_true"),
        "fm_mix/lt",
    ));
    let lp = tensor1d(&as_f64_vec(
        f.labels_pred.as_ref().expect("labels_pred"),
        "fm_mix/lp",
    ));
    let actual = fowlkes_mallows_score(&lt, &lp).expect("fm_mixed");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-12),
        "fm_mixed",
    );
}

#[test]
fn silhouette_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "silhouette_score");
    let (x_flat, x_rows, x_cols) = parse_score_2d(f.x.as_ref().expect("x"));
    let x = tensor2d(x_flat, x_rows, x_cols);
    let labels = tensor1d(&as_f64_vec(
        f.labels.as_ref().expect("labels"),
        "sil/labels",
    ));
    let actual = silhouette_score(&x, &labels).expect("silhouette");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "silhouette",
    );
}

#[test]
fn davies_bouldin_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "davies_bouldin_score");
    let (x_flat, x_rows, x_cols) = parse_score_2d(f.x.as_ref().expect("x"));
    let x = tensor2d(x_flat, x_rows, x_cols);
    let labels = tensor1d(&as_f64_vec(f.labels.as_ref().expect("labels"), "db/labels"));
    let actual = davies_bouldin_score(&x, &labels).expect("davies_bouldin");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "davies_bouldin",
    );
}

#[test]
fn calinski_harabasz_score_matches_sklearn() {
    let file = load_fixtures();
    let f = find(&file, "calinski_harabasz_score");
    let (x_flat, x_rows, x_cols) = parse_score_2d(f.x.as_ref().expect("x"));
    let x = tensor2d(x_flat, x_rows, x_cols);
    let labels = tensor1d(&as_f64_vec(f.labels.as_ref().expect("labels"), "ch/labels"));
    let actual = calinski_harabasz_score(&x, &labels).expect("calinski_harabasz");
    check_f64(
        actual,
        expected_f64(&f),
        f.tol.unwrap_or(1e-9),
        "calinski_harabasz",
    );
}

// ============================================================================
// Fixture sanity: verify all expected ops are present in the fixture file
// ============================================================================

#[test]
fn fixture_file_covers_every_metrics_op() {
    let file = load_fixtures();
    let ops: Vec<&str> = file.fixtures.iter().map(|f| f.op.as_str()).collect();

    let required = [
        "r2_score",
        "mean_squared_error",
        "root_mean_squared_error",
        "mean_absolute_error",
        "mean_absolute_percentage_error",
        "median_absolute_error",
        "max_error",
        "explained_variance_score",
        "accuracy_score",
        "precision_score_binary",
        "recall_score_binary",
        "f1_score_binary",
        "roc_auc_score",
        "log_loss",
        "confusion_matrix",
        "hamming_loss",
        "balanced_accuracy_score",
        "matthews_corrcoef",
        "cohen_kappa_score",
        "brier_score_loss",
        "top_k_accuracy_score_k1",
        "top_k_accuracy_score_k2",
        "zero_one_loss_normalized",
        "zero_one_loss_count",
        "average_precision_score",
        "ndcg_score_perfect",
        "ndcg_score_imperfect",
        "dcg_score",
        "label_ranking_average_precision_score",
        "label_ranking_loss",
        "coverage_error",
        "adjusted_rand_score_perfect",
        "adjusted_rand_score_mixed",
        "adjusted_mutual_info_score",
        "normalized_mutual_info_score",
        "homogeneity_score_perfect",
        "completeness_score_perfect",
        "v_measure_score_perfect",
        "fowlkes_mallows_score_perfect",
        "silhouette_score",
        "davies_bouldin_score",
        "calinski_harabasz_score",
    ];

    for r in &required {
        assert!(ops.contains(r), "fixture file missing required op {r:?}");
    }
}
